<?php
declare(strict_types=1);
namespace Moves\Boot;
use MovesCode\Router\Router;use Moves\Middleware\AuthMiddleware;use Moves\Middleware\GuestMiddleware;use Moves\Middleware\PermissionMiddleware;use Moves\Middleware\ProductAccessMiddleware;use Moves\Modules\Erp\ErpModule;
final class Routes{public static function register(Router $router):void{
ErpModule::register();
$router->namespace('Moves\\Controllers')->group('');
$router->get('/onboarding','OnboardingController:index','onboarding',GuestMiddleware::class);$router->post('/onboarding','OnboardingController:save','onboarding.save',GuestMiddleware::class);
if (\Moves\Core\Config::isDevelopment()) {
    $router->get('/layout', 'LayoutController:index', 'layout.home');
    $router->get('/layout/login', 'LayoutController:login', 'layout.login');
    $router->get('/layout/cadastro', 'LayoutController:signup', 'layout.signup');
    $router->get('/layout/recuperar-senha', 'LayoutController:forgot', 'layout.forgot');
    $router->get('/layout/auth/{mode}', 'LayoutController:authScreen', 'layout.auth.screen');
    $router->get('/layout/{product}/{page}', 'LayoutController:product', 'layout.product.page');
    $router->get('/layout/{product}', 'LayoutController:product', 'layout.product');
}
$router->get('/','AuthController:entry','home');$router->get('/site','Home:index','site.home');$router->get('/servicos','Home:services','site.services');$router->get('/projetos','Home:projects','site.projects');$router->get('/sobre','Home:about','site.about');$router->get('/conteudo','Home:content','site.content');$router->get('/conteudo/{slug}','Home:article','site.article');$router->get('/media/{id}','StudioModulesController:mediaFile','site.media.file');$router->get('/pagina/{slug}','Home:dynamicPage','site.dynamic.page');$router->get('/faq','Home:faq','site.faq');
$router->get('/help','HelpController:index','help.home');$router->get('/help/search','HelpController:search','help.search');$router->get('/help/products/{slug}','HelpController:product','help.product');$router->get('/help/categories/{slug}','HelpController:category','help.category');$router->get('/help/articles/{slug}','HelpController:article','help.article');$router->post('/help/articles/{slug}/feedback','HelpController:feedback','help.article.feedback');$router->get('/contato','Home:contact','site.contact');$router->post('/contato','Home:contactSubmit','site.contact.submit');
$router->get('/app','Home:app','app.home',AuthMiddleware::class);$router->get('/app/status','Home:appStatus','app.status',AuthMiddleware::class);$profileAccess=[AuthMiddleware::class,new PermissionMiddleware('profile.view')];$router->get('/profile','UserController:profile','profile',$profileAccess);$router->post('/profile','UserController:updateProfile','profile.update',$profileAccess);$router->post('/profile/password','UserController:updatePassword','profile.password',$profileAccess);$router->get('/profile/security/2fa','MfaController:index','security.2fa',$profileAccess);$router->post('/profile/security/2fa/start','MfaController:start','security.2fa.start',$profileAccess);$router->post('/profile/security/2fa/confirm','MfaController:confirm','security.2fa.confirm',$profileAccess);$router->post('/profile/security/2fa/recommendation/dismiss','MfaController:dismissRecommendation','security.2fa.recommendation.dismiss',$profileAccess);$router->get('/app/profile','UserController:appProfileRedirect','profile.app-redirect',AuthMiddleware::class);$router->get('/app/security/2fa','UserController:appSecurityRedirect','security.2fa.app-redirect',AuthMiddleware::class);$router->get('/day','DayController:index','platform.day',AuthMiddleware::class);$router->post('/day/tasks/{id}','DayController:task','day.task',AuthMiddleware::class);$router->post('/tenant/switch','TenantController:switch','tenant.switch',AuthMiddleware::class);$platformSettings=[AuthMiddleware::class,new PermissionMiddleware('settings.manage')];$router->get('/settings','PlatformSettingsController:index','platform.settings',$platformSettings);$router->post('/settings','PlatformSettingsController:save','platform.settings.save',$platformSettings);
$talk=[AuthMiddleware::class,new ProductAccessMiddleware('talk')];$support=[AuthMiddleware::class,new ProductAccessMiddleware('support')];$erp=[AuthMiddleware::class,new ProductAccessMiddleware('erp')];$studioProduct=new ProductAccessMiddleware('studio');
$router->get('/talk/channels/{id}/status','TalkController:whatsappStatus','talk.channels.status',$talk);
$router->post('/talk/channels','TalkController:channelSave','talk.channels.save',$talk);
$router->post('/talk/channels/{id}/connect','TalkController:channelConnect','talk.channels.connect',$talk);
$router->post('/talk/channels/{id}/disconnect','TalkController:channelDisconnect','talk.channels.disconnect',$talk);
$router->post('/talk/channels/{id}/remove','TalkController:channelRemove','talk.channels.remove',$talk);
$router->post('/talk/channels/{id}/logout','TalkController:channelLogout','talk.channels.logout',$talk);
$router->post('/talk/bridge/inbound','TalkBridgeController:inbound','talk.bridge.inbound');$router->get('/talk','TalkController:dashboard','talk.dashboard',$talk);$router->get('/talk/view/{view}','TalkController:dashboard','talk.view',$talk);$router->get('/talk/whatsapp/status','TalkController:whatsappStatus','talk.whatsapp.status',$talk);$router->get('/talk/queue','TalkController:queue','talk.queue',$talk);$router->post('/talk/queue','TalkController:queue','talk.queue.claim',$talk);$router->post('/talk/simulate','TalkController:simulate','talk.simulate',$talk);$router->get('/talk/tickets/{id}','TalkController:ticket','talk.ticket',$talk);$router->post('/talk/tickets/{id}','TalkController:ticket','talk.ticket.action',$talk);$router->get('/talk/attachments/{id}','TalkController:attachment','talk.attachment',$talk);$router->get('/talk/conversations','TalkController:conversations','talk.conversations',$talk);$router->get('/talk/contacts','TalkController:contacts','talk.contacts',$talk);$router->get('/talk/my-tickets','TalkController:myTickets','talk.my-tickets',$talk);$router->get('/talk/transfers','TalkController:transfers','talk.transfers',$talk);$router->get('/talk/history','TalkController:history','talk.history',$talk);$router->get('/talk/sync','TalkController:sync','talk.sync',$talk);$router->get('/talk/notifications','TalkController:notifications','talk.notifications',$talk);$router->post('/talk/notifications','TalkController:notifications','talk.notifications.action',$talk);$router->get('/talk/jack','TalkController:jack','talk.jack',$talk);$router->get('/talk/jack/settings','TalkController:jackSettings','talk.jack.settings',$talk);$router->post('/talk/jack/settings','TalkController:jackSettings','talk.jack.settings.save',$talk);$router->get('/talk/queues','TalkController:queues','talk.queues',$talk);$router->post('/talk/queues','TalkController:queues','talk.queues.save',$talk);$router->get('/talk/users','TalkController:users','talk.users',$talk);$router->post('/talk/users','TalkController:users','talk.users.presence',$talk);$router->get('/talk/reports','TalkController:reports','talk.reports',$talk);$router->get('/talk/settings','TalkController:settings','talk.settings',$talk);$router->post('/talk/settings','TalkController:settings','talk.settings.save',$talk);
$router->get('/support','SupportWorkspaceController:dashboard','platform.support',$support);$router->get('/support/inbox','SupportWorkspaceController:inbox','support.inbox',$support);$router->get('/support/my-tickets','SupportWorkspaceController:myTickets','support.my-tickets',$support);$router->get('/support/tickets','SupportWorkspaceController:tickets','support.tickets',$support);$router->get('/support/sla','SupportWorkspaceController:sla','support.sla',$support);$router->get('/support/users','SupportWorkspaceController:users','support.users',$support);$router->get('/support/reports','SupportWorkspaceController:reports','support.reports',$support);$router->get('/support/settings','SupportWorkspaceController:settings','support.settings',$support);$router->get('/support/articles','SupportController:articles','support.articles',$support);$router->get('/support/articles/create','SupportController:articleForm','support.articles.create',$support);$router->get('/support/drafts','SupportController:drafts','support.drafts',$support);$router->get('/support/revisions','SupportController:revisions','support.revisions',$support);$router->get('/support/trash','SupportController:trash','support.trash',$support);$router->get('/support/articles/{slug}/edit','SupportController:articleForm','support.articles.edit',$support);$router->post('/support/articles/save','SupportController:articleSave','support.articles.save',$support);$router->post('/support/articles/trash','SupportController:articleTrash','support.articles.trash',$support);$router->post('/support/articles/restore','SupportController:articleRestore','support.articles.restore',$support);$router->post('/support/articles/delete','SupportController:articleDelete','support.articles.delete',$support);$router->get('/support/products','SupportKnowledgeController:products','support.products',$support);$router->post('/support/products/save','SupportKnowledgeController:productSave','support.products.save',$support);$router->post('/support/products/delete','SupportKnowledgeController:productDelete','support.products.delete',$support);$router->get('/support/categories','SupportKnowledgeController:categories','support.categories',$support);$router->post('/support/categories/save','SupportKnowledgeController:categorySave','support.categories.save',$support);$router->post('/support/categories/delete','SupportKnowledgeController:categoryDelete','support.categories.delete',$support);$router->get('/support/tags','SupportKnowledgeController:tags','support.tags',$support);$router->post('/support/tags/save','SupportKnowledgeController:tagSave','support.tags.save',$support);$router->post('/support/tags/delete','SupportKnowledgeController:tagDelete','support.tags.delete',$support);
$router->get('/erp','PlatformController:erp','platform.erp',$erp);$users=[AuthMiddleware::class,$studioProduct,new PermissionMiddleware('users.manage')];$router->get('/studio/users','UserController:index','users.index',$users);$router->get('/studio/users/create','UserController:form','users.create',$users);$router->get('/studio/users/edit/{id}','UserController:form','users.edit',$users);$router->post('/studio/users/save','UserController:save','users.save',$users);$router->post('/studio/users/action','UserController:action','users.action',$users);$router->get('/studio/users/page/{page}','UserController:index','users.page',$users);
$content=[AuthMiddleware::class,$studioProduct,new PermissionMiddleware('content.manage')];$router->get('/studio','StudioController:dashboard','studio.home',[AuthMiddleware::class,$studioProduct,new PermissionMiddleware('studio.dashboard')]);$router->get('/studio/create','StudioController:create','studio.create',$content);$router->get('/studio/search','StudioSearchController:index','studio.search',[AuthMiddleware::class,$studioProduct,new PermissionMiddleware('studio.search')]);$technical=[AuthMiddleware::class,$studioProduct,new PermissionMiddleware('logs.manage')];$settings=[AuthMiddleware::class,$studioProduct,new PermissionMiddleware('settings.manage')];$router->get('/studio/versions','StudioController:versions','studio.versions',$settings);$router->post('/studio/versions','StudioController:versions','studio.versions.release',$settings);$router->get('/studio/logs','StudioController:logs','studio.logs',$technical);$router->post('/studio/logs','StudioController:logs','studio.logs.action',$technical);foreach(['pages','projects','articles','highlights','testimonials','faq'] as $module){$router->get('/studio/'.$module,'StudioModulesController:content','studio.'.$module,$content);$router->get('/studio/'.$module.'/create/{id}','StudioModulesController:content','studio.'.$module.'.create',$content);$router->get('/studio/'.$module.'/edit/{id}','StudioModulesController:content','studio.'.$module.'.edit',$content);$router->post('/studio/'.$module,'StudioModulesController:content','studio.'.$module.'.save',$content);}$router->get('/studio/content/preview/{id}','StudioModulesController:preview','studio.content.preview',$content);$router->get('/studio/categories','StudioModulesController:categories','studio.categories',$content);$router->post('/studio/categories','StudioModulesController:categories','studio.categories.save',$content);$router->get('/studio/tags','StudioModulesController:tags','studio.tags',$content);$router->post('/studio/tags','StudioModulesController:tags','studio.tags.save',$content);$router->get('/studio/trash','StudioModulesController:trash','studio.trash',$content);$router->post('/studio/trash','StudioModulesController:trash','studio.trash.action',$content);$router->get('/studio/menus','StudioModulesController:menus','studio.menus',$content);$router->post('/studio/menus','StudioModulesController:menus','studio.menus.save',$content);
$media=[AuthMiddleware::class,$studioProduct,new PermissionMiddleware('media.manage')];$proposal=[AuthMiddleware::class,$studioProduct,new PermissionMiddleware('proposals.manage')];$notice=[AuthMiddleware::class,$studioProduct,new PermissionMiddleware('notifications.manage')];$report=[AuthMiddleware::class,$studioProduct,new PermissionMiddleware('reports.view')];$router->get('/studio/media','StudioModulesController:media','studio.media',$media);$router->post('/studio/media','StudioModulesController:media','studio.media.save',$media);$router->get('/studio/media/library','StudioModulesController:mediaLibrary','studio.media.library',$content);$router->get('/studio/media/file/{id}','StudioModulesController:mediaFile','studio.media.file',$media);$router->get('/studio/proposals','StudioOperationsController:proposals','studio.proposals',$proposal);$router->post('/studio/proposals','StudioOperationsController:proposals','studio.proposals.save',$proposal);$router->get('/studio/notifications','StudioOperationsController:notifications','studio.notifications',$notice);$router->post('/studio/notifications','StudioOperationsController:notifications','studio.notifications.read',$notice);$router->get('/studio/reports','StudioOperationsController:reports','studio.reports',$report);$router->get('/studio/settings','SettingsController:index','settings.index',$settings);$router->post('/studio/settings','SettingsController:update','settings.update',$settings);$router->get('/studio/diagnostics','DiagnosticsController:index','diagnostics.index',[AuthMiddleware::class,$studioProduct,new PermissionMiddleware('diagnostics.view')]);
foreach(['/admin','/admin/search','/admin/versions','/admin/logs','/admin/pages','/admin/projects','/admin/articles','/admin/highlights','/admin/testimonials','/admin/faq','/admin/media','/admin/proposals','/admin/notifications','/admin/reports','/admin/settings','/admin/diagnostics','/admin/users','/admin/users/create'] as $legacy){$router->get($legacy,'LegacyStudioController:redirect');}$router->get('/admin/users/edit/{id}','LegacyStudioController:redirect');$router->get('/admin/users/page/{page}','LegacyStudioController:redirect');$router->get('/admin/media/file/{id}','LegacyStudioController:redirect');
$router->get('/first-access','InvitationController:acceptForm','first-access',GuestMiddleware::class);$router->post('/first-access','InvitationController:accept','first-access.accept',GuestMiddleware::class);$router->get('/login','AuthController:login','login',GuestMiddleware::class);$router->post('/login','AuthController:authenticate','login.authenticate',GuestMiddleware::class);$router->get('/login/2fa','AuthController:mfaChallenge','login.2fa',GuestMiddleware::class);$router->post('/login/2fa','AuthController:verifyMfaChallenge','login.2fa.verify',GuestMiddleware::class);$router->get('/forgot-password','PasswordRecoveryController:requestForm','password.forgot',GuestMiddleware::class);$router->post('/forgot-password','PasswordRecoveryController:requestCode','password.forgot.send',GuestMiddleware::class);$router->get('/password-recovery/code','PasswordRecoveryController:codeForm','password.code',GuestMiddleware::class);$router->post('/password-recovery/code','PasswordRecoveryController:verifyCode','password.code.verify',GuestMiddleware::class);$router->post('/password-recovery/resend','PasswordRecoveryController:resendCode','password.code.resend',GuestMiddleware::class);$router->get('/password-recovery/new-password','PasswordRecoveryController:newPasswordForm','password.reset',GuestMiddleware::class);$router->post('/password-recovery/new-password','PasswordRecoveryController:saveNewPassword','password.reset.save',GuestMiddleware::class);$router->post('/logout','AuthController:logout','logout',AuthMiddleware::class);Modules::boot($router);
}}
