<?php
declare(strict_types=1);
namespace Moves\Services\Talk\Transport;
use RuntimeException;
final class BaileysWhatsAppTransport implements WhatsAppTransport{
 public function __construct(private readonly string $baseUrl,private readonly string $token=''){}
 public function sendText(string $to,string $text):array{return $this->request('POST','/send/text',['to'=>$to,'text'=>$text]);}
 public function sendMedia(string $to,string $absolutePath,string $mimeType,?string $caption=null):array{throw new RuntimeException('Envio de mídia pelo bridge local ainda não está habilitado.');}
 public function status():array{try{$r=$this->request('GET','/status');return ['status'=>(string)($r['status']??'disconnected'),'connected'=>(bool)($r['connected']??false),'detail'=>(string)($r['detail']??''),'qr'=>$r['qr']??null,'profile'=>$r['profile']??null,'driver'=>'baileys'];}catch(\Throwable $e){return ['status'=>'disconnected','connected'=>false,'detail'=>'Bridge local indisponível: '.$e->getMessage(),'qr'=>null,'profile'=>null,'driver'=>'baileys'];}}
 private function request(string $method,string $path,?array $payload=null):array{if(!function_exists('curl_init'))throw new RuntimeException('Extensão PHP cURL não está habilitada.');$ch=curl_init(rtrim($this->baseUrl,'/').$path);if($ch===false)throw new RuntimeException('Falha ao iniciar bridge WhatsApp.');$headers=['Accept: application/json'];if($this->token!=='')$headers[]='Authorization: Bearer '.$this->token;$opt=[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>8,CURLOPT_HTTPHEADER=>$headers];if($method==='POST'){$headers[]='Content-Type: application/json';$opt[CURLOPT_POST]=true;$opt[CURLOPT_POSTFIELDS]=json_encode($payload??[],JSON_THROW_ON_ERROR);$opt[CURLOPT_HTTPHEADER]=$headers;}curl_setopt_array($ch,$opt);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);if($raw===false||$status<200||$status>=300)throw new RuntimeException($err!==''?$err:'HTTP '.$status);$data=json_decode((string)$raw,true);if(!is_array($data))throw new RuntimeException('Resposta inválida do bridge WhatsApp.');if(isset($data['error']))throw new RuntimeException((string)$data['error']);return $data;}
}