<?php declare(strict_types=1);
$channels=$channels??[];$channelQueues=$channelQueues??[];
$formatPhone=static function(?string $value):string{$digits=preg_replace('/\D+/','',(string)$value)??'';return preg_match('/^55(\d{2})(\d{5})(\d{4})$/',$digits,$m)===1?'('.$m[1].') '.$m[2].'-'.$m[3]:($digits!==''?$digits:'Não configurado');};
?>
<section class="talk-channels" data-talk-channels data-csrf="<?= $this->e((string)($_SESSION['_token']??'')) ?>">
  <div class="talk-channel-toolbar"><div><h2>WhatsApp</h2><p>Conecte e acompanhe os números desta administradora.</p></div><button class="studio-btn studio-btn-primary" type="button" data-channel-new><i class="icon-add-outline"></i> Adicionar canal</button></div>
  <div class="talk-channel-feedback" data-channel-feedback role="status" aria-live="polite" hidden></div>
  <?php if(isset($_GET['error'])): ?><div class="support-info is-error"><?= $this->e((string)$_GET['error']) ?></div><?php endif; ?>
  <?php if(!$channels): ?><div class="talk-channel-empty"><span class="talk-whatsapp-mark large"><i class="icon-logo-whatsapp"></i></span><h3>Nenhum WhatsApp conectado</h3><p>Conecte um número para começar a receber atendimentos pelo Moves Talk.</p><button class="studio-btn studio-btn-primary" type="button" data-channel-empty-new>Conectar WhatsApp</button></div><?php else: ?>
  <div class="talk-channel-list" role="table" aria-label="Canais WhatsApp"><div class="talk-channel-list-head" role="row"><span>Canal</span><span>Número</span><span>Status</span><span>Fila</span><span>Última atividade</span><span></span></div>
  <?php foreach($channels as $channel): $id=(int)$channel['id'];$state=(string)($channel['connection_status']??'disconnected');$phone=(string)($channel['phone_number']??''); ?><article class="talk-channel-row" role="row" data-channel-row="<?= $id ?>" data-channel-name="<?= $this->e((string)$channel['name']) ?>" data-status-url="/talk/channels/<?= $id ?>/status"><div class="talk-channel-name"><span class="talk-whatsapp-mark"><i class="icon-logo-whatsapp"></i></span><span><strong><?= $this->e((string)$channel['name']) ?></strong><small><?= $this->e((string)($channel['display_name']??'Canal WhatsApp')) ?></small></span></div><strong data-channel-phone data-channel-phone-value="<?= $this->e($phone) ?>"><?= $this->e($formatPhone($phone)) ?></strong><span class="talk-channel-health" data-channel-state data-state="<?= $this->e($state) ?>"><i></i><span><?= $this->e($state==='connected'?'Conectado':($state==='qr'?'Aguardando QR':ucfirst($state))) ?></span></span><span><?= $this->e((string)($channel['default_queue_name']??'—')) ?></span><span data-channel-activity><?= $this->e((string)($channel['last_connected_at']??'—')) ?></span><div class="talk-channel-menu"><details><summary aria-label="Ações do canal">•••</summary><div><button type="button" data-channel-edit='<?= $this->e(json_encode($channel,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT)) ?>'>Configurar</button><button type="button" data-channel-connect="<?= $id ?>">Reconectar</button><button type="button" data-channel-disconnect="<?= $id ?>">Desconectar</button><button class="danger" type="button" data-channel-remove="<?= $id ?>">Remover canal</button></div></details></div><small class="talk-channel-error" data-channel-error><?= $this->e((string)($channel['last_error']??'')) ?></small></article><?php endforeach; ?></div><?php endif; ?>
  <dialog class="talk-channel-dialog" data-channel-dialog><form method="post" action="/talk/channels"><?= $this->csrf() ?><input type="hidden" name="id" value="0"><header><h2 data-dialog-title>Novo canal</h2><button type="button" data-dialog-close aria-label="Fechar">×</button></header><label>Nome do canal<input name="name" maxlength="120" required placeholder="Ex.: WhatsApp Atendimento"></label><label>Nome de exibição<input name="display_name" maxlength="160" placeholder="Opcional"></label><label>Fila padrão<select name="default_queue_id"><option value="0">Sem fila padrão</option><?php foreach($channelQueues as $queue): ?><option value="<?= (int)$queue['id'] ?>"><?= $this->e((string)$queue['name']) ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label><footer><button class="studio-btn" type="button" data-dialog-close>Cancelar</button><button class="studio-btn studio-btn-primary" type="submit">Salvar canal</button></footer></form></dialog>
  <dialog class="talk-channel-dialog talk-connect-dialog" data-connect-dialog data-channel-id=""><div class="talk-connect-content"><header><div><h2>Conectar WhatsApp</h2><p>Use o WhatsApp no celular para conectar este número ao Moves Talk.</p></div><button type="button" data-connect-cancel aria-label="Fechar">×</button></header><div class="talk-connect-stage" data-connect-stage="starting"><span class="talk-spinner"></span><strong data-connect-title>Preparando o WhatsApp...</strong><p data-connect-detail>A conexão começa somente para o canal selecionado.</p><img data-connect-qr alt="QR Code para conectar o WhatsApp" hidden><ol data-connect-instructions hidden><li>Abra o WhatsApp no celular.</li><li>Acesse Configurações → Aparelhos conectados.</li><li>Escolha Conectar aparelho e leia o QR Code.</li></ol><div class="talk-connect-success" data-connect-success hidden><i class="icon-checkmark-circle-outline"></i><strong>WhatsApp conectado</strong><p>Número: <span data-connect-phone>—</span></p></div></div><footer><button class="studio-btn" type="button" data-connect-cancel>Cancelar</button><button class="studio-btn" type="button" data-connect-retry hidden>Gerar novo QR</button><button class="studio-btn studio-btn-primary" type="button" data-connect-done hidden>Concluir</button></footer></div></dialog>
  <dialog class="talk-channel-dialog talk-remove-dialog" data-remove-dialog data-channel-id=""><div><header><h2>Remover canal?</h2><button type="button" data-remove-cancel aria-label="Fechar">×</button></header><p>O número <strong data-remove-phone>—</strong> será removido do Moves Talk.</p><p>As conversas e o histórico não serão apagados.</p><footer><button class="studio-btn" type="button" data-remove-cancel>Cancelar</button><button class="studio-btn studio-btn-danger" type="button" data-remove-confirm>Remover</button></footer></div></dialog>
</section>
