ALTER TABLE talk_messages
    ADD COLUMN delivery_status VARCHAR(20) NOT NULL DEFAULT 'sent' AFTER direction,
    ADD COLUMN delivery_error VARCHAR(500) NULL AFTER delivery_status,
    ADD COLUMN delivery_updated_at DATETIME NULL AFTER delivery_error,
    ADD KEY talk_messages_tenant_delivery (tenant_id,direction,delivery_status,created_at);

CREATE TABLE talk_outbox (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT UNSIGNED NOT NULL,
    channel_id BIGINT UNSIGNED NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    message_id BIGINT UNSIGNED NOT NULL,
    type VARCHAR(30) NOT NULL DEFAULT 'text',
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    available_at DATETIME NOT NULL,
    locked_at DATETIME NULL,
    locked_by VARCHAR(100) NULL,
    processing_started_at DATETIME NULL,
    sent_at DATETIME NULL,
    failed_at DATETIME NULL,
    last_error VARCHAR(500) NULL,
    external_message_id VARCHAR(190) NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    payload JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY talk_outbox_tenant_idempotency (tenant_id,idempotency_key),
    UNIQUE KEY talk_outbox_tenant_message (tenant_id,message_id),
    UNIQUE KEY talk_outbox_tenant_id (tenant_id,id),
    KEY talk_outbox_dispatch (status,available_at,locked_at,id),
    KEY talk_outbox_tenant_status (tenant_id,status,available_at,id),
    KEY talk_outbox_channel (tenant_id,channel_id,status),
    CONSTRAINT talk_outbox_status_check CHECK (status IN ('pending','processing','sent','failed')),
    CONSTRAINT talk_outbox_tenant_fk FOREIGN KEY (tenant_id) REFERENCES talk_tenants(id) ON DELETE CASCADE,
    CONSTRAINT talk_outbox_channel_tenant_fk FOREIGN KEY (tenant_id,channel_id) REFERENCES talk_channels(tenant_id,id) ON DELETE RESTRICT,
    CONSTRAINT talk_outbox_ticket_tenant_fk FOREIGN KEY (tenant_id,ticket_id) REFERENCES talk_tickets(tenant_id,id) ON DELETE CASCADE,
    CONSTRAINT talk_outbox_message_tenant_fk FOREIGN KEY (tenant_id,message_id) REFERENCES talk_messages(tenant_id,id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
