CREATE TABLE user_preferences (
    user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    locale VARCHAR(10) NOT NULL DEFAULT 'pt-BR',
    theme VARCHAR(10) NOT NULL DEFAULT 'system',
    email_notifications TINYINT(1) NOT NULL DEFAULT 1,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT user_preferences_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
