CREATE TABLE IF NOT EXISTS studio_content_revisions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    content_id BIGINT UNSIGNED NOT NULL,
    type VARCHAR(30) NOT NULL,
    revision_number INT UNSIGNED NOT NULL,
    reason VARCHAR(30) NOT NULL,
    title VARCHAR(180) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    excerpt TEXT NULL,
    content LONGTEXT NULL,
    seo_title VARCHAR(160) NULL,
    seo_description VARCHAR(320) NULL,
    media_id BIGINT UNSIGNED NULL,
    category_id BIGINT UNSIGNED NULL,
    template VARCHAR(60) NULL,
    meta_json JSON NULL,
    status VARCHAR(20) NOT NULL,
    position INT NOT NULL DEFAULT 0,
    published_at DATETIME NULL,
    created_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY studio_revision_number (content_id, revision_number),
    KEY studio_revision_listing (content_id, created_at),
    CONSTRAINT studio_revision_content FOREIGN KEY (content_id) REFERENCES studio_content(id) ON DELETE CASCADE,
    CONSTRAINT studio_revision_author FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
