<?php
/** Moves Platform | Product Navigation */
$activeProduct=$activeProduct??'studio';$currentPage=$currentPage??'dashboard';
if($activeProduct==='day'){
$ariaLabel='Navegação do Meu Dia';$groups=['Principal'=>[['label'=>'Meu Dia','icon'=>'icon-sunny-outline','href'=>'/day','key'=>'today']], 'Conta'=>[['label'=>'Meu perfil','icon'=>'icon-person-outline','href'=>'/profile','key'=>'profile'],['label'=>'Segurança','icon'=>'icon-shield-checkmark-outline','href'=>'/profile/security/2fa','key'=>'security']], 'Administração'=>[['label'=>'Administradora e produtos','icon'=>'icon-settings-outline','href'=>'/settings','key'=>'settings']]];
}elseif($activeProduct==='erp'){
$ariaLabel='Navegação do ERP';$groups=['Principal'=>[['label'=>'Visão geral','icon'=>'icon-grid-outline','href'=>'/erp','key'=>'dashboard']], 'Cadastros'=>[['label'=>'Condomínios','icon'=>'icon-business','href'=>'/erp/condominiums','key'=>'condominiums'],['label'=>'Pessoas','icon'=>'icon-people-outline','href'=>'/erp/people','key'=>'people'],['label'=>'Unidades','icon'=>'icon-home-outline','href'=>'/erp/units','key'=>'units'],['label'=>'Fornecedores','icon'=>'icon-briefcase-outline','href'=>'/erp/suppliers','key'=>'suppliers']], 'Financeiro'=>[['label'=>'Plano de Contas','icon'=>'icon-list-outline','href'=>'/erp/chart-of-accounts','key'=>'chart-of-accounts'],['label'=>'Competências','icon'=>'icon-calendar-outline','href'=>'/erp/periods','key'=>'periods'],['label'=>'Contas a pagar','icon'=>'icon-card-outline','href'=>'/erp/payables','key'=>'payables'],['label'=>'Contas a receber','icon'=>'icon-wallet-outline','href'=>'/erp/receivables','key'=>'receivables'],['label'=>'Cobranças','icon'=>'icon-receipt-outline','href'=>'/erp/billing','key'=>'billing'],['label'=>'Movimentações','icon'=>'icon-swap-horizontal-outline','disabled'=>true]], 'Bancos'=>[['label'=>'Contas bancárias','icon'=>'icon-business-outline','href'=>'/erp/bank-accounts','key'=>'bank-accounts'],['label'=>'Conciliação','icon'=>'icon-git-compare-outline','href'=>'/erp/reconciliation','key'=>'reconciliation']], 'Administração'=>[['label'=>'Configurações','icon'=>'icon-settings-outline','href'=>'/settings','key'=>'settings']]];
}elseif($activeProduct==='support'){
$ariaLabel='Navegação do Suporte';$groups=['Principal'=>[['label'=>'Visão geral','icon'=>'icon-grid-outline','href'=>'/support','key'=>'dashboard']], 'Base de conhecimento'=>[['label'=>'Artigos','icon'=>'icon-newspaper-outline','href'=>'/support/articles','key'=>'articles'],['label'=>'Categorias','icon'=>'icon-folder-outline','href'=>'/support/categories','key'=>'categories'],['label'=>'Produtos','icon'=>'icon-cube-outline','href'=>'/support/products','key'=>'products'],['label'=>'Tags','icon'=>'icon-pricetag-outline','href'=>'/support/tags','key'=>'tags'],['label'=>'Rascunhos','icon'=>'icon-document-text-outline','href'=>'/support/drafts','key'=>'drafts'],['label'=>'Revisões','icon'=>'icon-time-outline','href'=>'/support/revisions','key'=>'revisions'],['label'=>'Lixeira','icon'=>'icon-trash-outline','href'=>'/support/trash','key'=>'trash']], 'Atendimento'=>[['label'=>'Caixa de entrada','icon'=>'icon-mail-outline','href'=>'/support/inbox','key'=>'inbox'],['label'=>'Meus chamados','icon'=>'icon-headset-outline','href'=>'/support/my-tickets','key'=>'my-tickets'],['label'=>'Todos','icon'=>'icon-chatbubbles-outline','href'=>'/support/tickets','key'=>'tickets'],['label'=>'SLA','icon'=>'icon-timer-outline','href'=>'/support/sla','key'=>'sla']], 'Gestão'=>[['label'=>'Usuários','icon'=>'icon-people-outline','href'=>'/support/users','key'=>'users'],['label'=>'Relatórios','icon'=>'icon-stats-chart-outline','href'=>'/support/reports','key'=>'reports'],['label'=>'Configurações','icon'=>'icon-settings-outline','href'=>'/support/settings','key'=>'settings']]];
}elseif($activeProduct==='talk'){
$ariaLabel='Navegação do Talk';$requestPath=(string)(parse_url($_SERVER['REQUEST_URI']??'/talk',PHP_URL_PATH)??'/talk');$talkView='inbox';if(preg_match('#^/talk/view/([^/]+)#',$requestPath,$match)){$talkView=(string)$match[1];}$groups=['Atendimento'=>[['label'=>'Conversas','icon'=>'icon-chatbubbles-outline','href'=>'/talk/view/inbox','view'=>'inbox','key'=>'dashboard'],['label'=>'Fila','icon'=>'icon-time-outline','href'=>'/talk/view/queue','view'=>'queue','key'=>'dashboard'],['label'=>'Contatos','icon'=>'icon-people-outline','href'=>'/talk/view/contacts','view'=>'contacts','key'=>'dashboard'],['label'=>'Histórico','icon'=>'icon-time-outline','href'=>'/talk/view/history','view'=>'history','key'=>'dashboard']], 'WhatsApp'=>[['label'=>'Conexão','icon'=>'icon-logo-whatsapp','href'=>'/talk/view/connection','view'=>'connection','key'=>'dashboard']], 'Automação'=>[['label'=>'Jack','icon'=>'icon-sparkles-outline','href'=>'/talk/view/jack','view'=>'jack','key'=>'dashboard']], 'Gestão'=>[['label'=>'Equipe','icon'=>'icon-people-outline','href'=>'/talk/view/team','view'=>'team','key'=>'dashboard'],['label'=>'Configurações','icon'=>'icon-settings-outline','href'=>'/talk/view/settings','view'=>'settings','key'=>'dashboard']]];
}else{
$ariaLabel='Navegação do CMS';$groups=['Visão geral'=>[['label'=>'Dashboard','icon'=>'icon-grid-outline','href'=>'/studio','key'=>'dashboard'],['label'=>'Criar','icon'=>'icon-add-outline','href'=>'/studio/create','key'=>'create'],['label'=>'Relatórios','icon'=>'icon-stats-chart-outline','href'=>'/studio/reports','key'=>'reports'],['label'=>'Notificações','icon'=>'icon-notifications-outline','href'=>'/studio/notifications','key'=>'notifications'],['label'=>'Propostas','icon'=>'icon-document-text-outline','href'=>'/studio/proposals','key'=>'proposals']], 'Conteúdo'=>[['label'=>'Páginas','icon'=>'icon-copy-outline','href'=>'/studio/pages','key'=>'pages'],['label'=>'Projetos','icon'=>'icon-briefcase-outline','href'=>'/studio/projects','key'=>'projects'],['label'=>'Artigos','icon'=>'icon-newspaper-outline','href'=>'/studio/articles','key'=>'articles'],['label'=>'Mídia','icon'=>'icon-image-outline','href'=>'/studio/media','key'=>'media'],['label'=>'Destaques','icon'=>'icon-star-outline','href'=>'/studio/highlights','key'=>'highlights'],['label'=>'Depoimentos','icon'=>'icon-chatbubble-outline','href'=>'/studio/testimonials','key'=>'testimonials'],['label'=>'FAQ','icon'=>'icon-help-circle-outline','href'=>'/studio/faq','key'=>'faq'],['label'=>'Categorias','icon'=>'icon-folder-outline','href'=>'/studio/categories','key'=>'categories'],['label'=>'Tags','icon'=>'icon-pricetag-outline','href'=>'/studio/tags','key'=>'tags'],['label'=>'Menus','icon'=>'icon-menu-outline','href'=>'/studio/menus','key'=>'menus'],['label'=>'Lixeira','icon'=>'icon-trash-outline','href'=>'/studio/trash','key'=>'trash']], 'Gestão'=>[['label'=>'Usuários','icon'=>'icon-people-outline','href'=>'/studio/users','key'=>'users'],['label'=>'Configurações','icon'=>'icon-settings-outline','href'=>'/studio/settings','key'=>'settings'],['label'=>'Versões','icon'=>'icon-pricetag-outline','href'=>'/studio/versions','key'=>'versions'],['label'=>'Log','icon'=>'icon-bug-outline','href'=>'/studio/logs','key'=>'logs']]];
}
?>
<nav class="product-nav" aria-label="<?= $this->e($ariaLabel) ?>"><?php foreach($groups as $group=>$items): ?><div class="nav-section"><?= $this->e($group) ?></div><?php foreach($items as $item): ?><?php $active=$currentPage===($item['key']??''); if($activeProduct==='talk'&&isset($talkView)){$active=(string)($item['view']??'inbox')===$talkView;} ?><?php if(!empty($item['disabled'])): ?><span class="nav-disabled" aria-disabled="true" title="Disponível em uma próxima etapa"><i class="<?= $this->e($item['icon']) ?>"></i><span><?= $this->e($item['label']) ?></span><small>Em breve</small></span><?php else: ?><a href="<?= $this->e($item['href']) ?>" class="<?= $active?'active':'' ?>" <?= $active?'aria-current="page"':'' ?>><i class="<?= $this->e($item['icon']) ?>"></i><span><?= $this->e($item['label']) ?></span></a><?php endif; ?><?php endforeach; ?><?php endforeach; ?></nav>
