<?php

declare(strict_types=1);

require dirname(__DIR__) . '/vendor/autoload.php';

use Moves\Boot\Connection;
use Moves\Boot\Environment;
use Moves\Services\Support\ArticleService;
use Moves\Services\Support\CategoryService;
use Moves\Services\Support\ProductService;
use MovesCode\Model\Connection as ModelConnection;

Environment::load(dirname(__DIR__));
$pdo = Connection::getInstance();
ModelConnection::configure($pdo);
$refreshExisting = in_array('--refresh-existing', $argv ?? [], true);

$authorId = (int) $pdo->query("SELECT id FROM users WHERE status = 'active' ORDER BY (role = 'admin') DESC, id ASC LIMIT 1")->fetchColumn();
if ($authorId <= 0) {
    throw new RuntimeException('Nenhum autor ativo foi encontrado.');
}

// Remove exclusivamente os registros descartáveis conhecidos das rodadas de homologação anteriores.
$testArticleSlugs = ['tes', 'sadasdas', 'teste-estabilizacao-base', 'teste-de-integracao-taxonomy-2a'];
$placeholders = implode(',', array_fill(0, count($testArticleSlugs), '?'));
$statement = $pdo->prepare("DELETE FROM support_articles WHERE slug IN ({$placeholders})");
$statement->execute($testArticleSlugs);
foreach ([
    ['support_categories', ['test', 'categoria-2a-taxonomy-teste']],
    ['support_products', ['teste', 'produto-2a-taxonomy-teste']],
    ['support_tags', ['teste-estabilizacao', 'support', 'tag-2a-taxonomy-atualizada']],
] as [$table, $slugs]) {
    $placeholders = implode(',', array_fill(0, count($slugs), '?'));
    $statement = $pdo->prepare("DELETE FROM {$table} WHERE slug IN ({$placeholders})");
    $statement->execute($slugs);
}

$productService = new ProductService();
$categoryService = new CategoryService();
$articleService = new ArticleService();

$documentationMedia = static function (string $name, string $alt) use ($pdo, $authorId): int {
    $statement = $pdo->prepare('SELECT id FROM studio_media WHERE name=? LIMIT 1');
    $statement->execute([$name]);
    $id = $statement->fetchColumn();
    if ($id !== false) {
        $pdo->prepare('UPDATE studio_media SET alt_text=? WHERE id=?')->execute([$alt, (int) $id]);
        return (int) $id;
    }
    $path = dirname(__DIR__) . '/storage/media/' . $name;
    if (!is_file($path)) {
        throw new RuntimeException('Screenshot documental ausente: ' . $path);
    }
    [$width, $height] = getimagesize($path) ?: [null, null];
    $pdo->prepare('INSERT INTO studio_media(name,alt_text,path,mime,size,width,height,created_by) VALUES(?,?,?,?,?,?,?,?)')
        ->execute([$name, $alt, $path, 'image/png', filesize($path), $width, $height, $authorId]);
    return (int) $pdo->lastInsertId();
};

$screenshots = [
    'support-list' => $documentationMedia('help-support-articles.png', 'Lista real de artigos do Moves Support com busca, filtros e ação Novo artigo.'),
    'support-editor' => $documentationMedia('help-support-editor.png', 'Tela real de criação de artigo do Moves Support com o Moves Editor e classificação.'),
    'cms-articles' => $documentationMedia('help-cms-articles.png', 'Lista real de artigos do Moves CMS com busca e filtros de publicação.'),
    'cms-media' => $documentationMedia('help-cms-media.png', 'Biblioteca de Mídia real do Moves CMS com arquivos e ação de envio.'),
];

$figure = static fn (int $mediaId, string $alt, string $caption): string => '<figure><img src="/media/' . $mediaId . '" alt="' . htmlspecialchars($alt, ENT_QUOTES, 'UTF-8') . '" loading="lazy"><figcaption>' . htmlspecialchars($caption, ENT_QUOTES, 'UTF-8') . '</figcaption></figure>';

$findId = static function (string $table, string $slug) use ($pdo): ?int {
    $statement = $pdo->prepare("SELECT id FROM {$table} WHERE slug = ? LIMIT 1");
    $statement->execute([$slug]);
    $id = $statement->fetchColumn();
    return $id === false ? null : (int) $id;
};

$product = static function (string $name, string $slug, string $description) use ($findId, $productService, $authorId): int {
    return $findId('support_products', $slug)
        ?? (int) $productService->create($name, $description, $authorId)->id;
};

$category = static function (string $name, string $slug, int $productId, int $position, string $description) use ($findId, $categoryService): int {
    return $findId('support_categories', $slug)
        ?? (int) $categoryService->create($name, $productId, null, $description, $position)->id;
};

$products = [
    'platform' => $product('Moves Platform', 'moves-platform', 'Visão geral, acesso, usuários e administração da plataforma Moves.'),
    'support' => $product('Moves Support', 'moves-support', 'Base de conhecimento e workspace de atendimento do Moves Support.'),
    'editor' => $product('Moves Editor', 'moves-editor', 'Editor visual oficial usado para produzir conteúdo no ecossistema Moves.'),
    'cms' => $product('Moves CMS', 'moves-cms', 'Criação, organização e publicação do conteúdo do site pelo Moves Studio.'),
];

$categories = [
    'start' => $category('Primeiros passos', 'primeiros-passos', $products['platform'], 10, 'Orientações iniciais para conhecer e acessar o Moves.'),
    'users' => $category('Usuários', 'usuarios', $products['platform'], 20, 'Gestão e consulta de usuários da plataforma.'),
    'kb' => $category('Base de conhecimento', 'base-de-conhecimento', $products['support'], 10, 'Conceitos e operação da Knowledge Base.'),
    'articles' => $category('Artigos', 'artigos', $products['support'], 20, 'Criação, publicação, pesquisa e ciclo editorial.'),
    'organization' => $category('Organização do conteúdo', 'organizacao-do-conteudo', $products['support'], 30, 'Produtos, categorias, tags, revisões e lixeira.'),
    'service' => $category('Atendimento', 'atendimento', $products['support'], 40, 'Interface preparada para o futuro motor de chamados.'),
    'editor' => $category('Moves Editor', 'moves-editor', $products['editor'], 10, 'Uso do editor visual oficial.'),
    'media' => $category('Imagens e mídia', 'imagens-e-midia', $products['editor'], 20, 'Upload, biblioteca e apresentação de imagens.'),
    'cms-start' => $category('CMS · Primeiros passos', 'cms-primeiros-passos', $products['cms'], 10, 'Visão geral e primeiros fluxos do Moves CMS.'),
    'cms-content' => $category('CMS · Conteúdo e publicação', 'cms-conteudo-publicacao', $products['cms'], 20, 'Páginas, artigos, projetos, status, URLs e SEO.'),
    'cms-media' => $category('CMS · Editor e mídia', 'cms-editor-midia', $products['cms'], 30, 'Moves Editor, imagens de capa e biblioteca oficial.'),
];

$articles = [
    ['Conhecendo o Moves', 'conhecendo-o-moves', 'platform', 'start', ['primeiros-passos'], 'Uma visão geral da plataforma Moves e de como seus produtos compartilham a mesma experiência.', '<h2>Para que serve</h2><p>O Moves reúne produtos administrativos em uma plataforma única, com navegação, identidade e autenticação consistentes. Cada produto mantém responsabilidades próprias, mas utiliza a mesma base segura.</p><h2>Como acessar</h2><ol><li>Entre na aplicação com uma conta ativa.</li><li>Use o seletor de produtos no topo para escolher o workspace.</li><li>Confirme o nome do produto na navegação lateral antes de alterar dados.</li></ol><h2>Comportamento esperado</h2><p>Somente módulos habilitados aparecem para o usuário. O Moves Support concentra documentação e, futuramente, atendimento. O conteúdo exibido sempre deve refletir registros reais.</p>'],
    ['Conhecendo o Moves Support', 'conhecendo-o-moves-support', 'support', 'kb', ['primeiros-passos','artigos'], 'Entenda o workspace de documentação e atendimento do Moves Support.', '<h2>Visão geral</h2><p>O Moves Support organiza a Base de Conhecimento em Artigos, Produtos, Categorias e Tags. O dashboard resume os registros publicados, rascunhos e alterações recentes.</p><h2>Como acessar</h2><p>Abra o produto Support pelo seletor e use a barra lateral. A seção Conhecimento contém todo o ciclo editorial; a seção Atendimento apresenta as áreas que receberão o motor de chamados.</p><h2>Importante</h2><p>A Knowledge Base está operacional. Caixa de entrada, Meus chamados, Todos os chamados e SLA possuem layout final, mas o backend de atendimento será habilitado em uma etapa posterior.</p>'],
    ['Como funciona a Base de Conhecimento', 'como-funciona-a-base-de-conhecimento', 'support', 'kb', ['artigos','categorias','produtos','tags'], 'Conheça a estrutura que conecta artigos, produtos, categorias, tags e pesquisa.', '<h2>Estrutura</h2><p>Artigos são a unidade editorial. Cada artigo pode pertencer a um Produto e a uma Categoria, receber várias Tags e armazenar informações de SEO, autoria e publicação.</p><h2>Fluxo recomendado</h2><ol><li>Cadastre ou escolha o Produto.</li><li>Defina uma Categoria coerente.</li><li>Escreva e revise o Artigo.</li><li>Preencha SEO e Tags.</li><li>Salve como rascunho ou publique.</li></ol><h2>Resultados</h2><p>Busca, filtros, dashboard e relatórios consultam o banco em tempo real. Itens enviados à lixeira deixam de participar das métricas normais.</p>'],
    ['Como criar um artigo', 'como-criar-um-artigo', 'support', 'articles', ['artigos','editor','seo'], 'Passo a passo para cadastrar um artigo completo e seguro no Moves Support.', '<h2>Antes de começar</h2><p>Use uma conta com acesso à Base de Conhecimento e confirme qual Produto e Categoria receberão o artigo.</p><h2>1. Abra a lista de artigos</h2><p>No Support, selecione <strong>Artigos</strong>. A tela reúne busca, filtros, status e as ações editoriais.</p>' . $figure($screenshots['support-list'], 'Lista de artigos do Moves Support com o botão Novo artigo.', 'Na Base de conhecimento, selecione Novo artigo no canto superior direito.') . '<h2>2. Inicie o conteúdo</h2><p>Selecione <strong>Novo artigo</strong>. Informe título, slug e resumo; depois produza o texto no Moves Editor.</p>' . $figure($screenshots['support-editor'], 'Formulário de novo artigo do Moves Support com editor e painéis laterais.', 'O formulário organiza conteúdo, publicação, classificação, capa e SEO em uma única tela.') . '<h2>3. Classifique e revise</h2><ol><li>Escolha autor, Produto e Categoria.</li><li>Associe Tags úteis, sem criar sinônimos desnecessários.</li><li>Defina a capa e confira o ALT.</li><li>Preencha meta title, meta description, focus keyword, canonical e Robots quando aplicável.</li></ol><div class="help-callout help-callout-tip"><strong>Dica</strong><p>Use headings H2 e H3 para que o índice público seja criado automaticamente.</p></div><h2>4. Salve ou publique</h2><p>Use Rascunho para revisão interna ou Publicado para disponibilizar o artigo na Central de Ajuda.</p><h2>Resultado esperado</h2><p>O slug é normalizado e precisa ser único. O conteúdo é sanitizado no servidor. Após salvar, o artigo aparece nas listas, busca e métricas compatíveis com seu status.</p><h2>Problemas comuns</h2><ul><li>Slug duplicado: escolha um endereço diferente.</li><li>Imagem sem ALT: volte à biblioteca e descreva a informação visual.</li><li>Artigo não aparece no Help Center: confira status, data de publicação e lixeira.</li></ul>'],
    ['Como editar e publicar um artigo', 'como-editar-e-publicar-um-artigo', 'support', 'articles', ['artigos','revisoes'], 'Edite conteúdo, altere o estado editorial e publique com segurança.', '<h2>Editar</h2><p>Na lista de Artigos, abra o registro desejado. Revise título, resumo, conteúdo, classificação, SEO e capa antes de salvar.</p><h2>Publicar e arquivar</h2><p>Publicado torna o registro elegível para consumo público quando essa integração estiver ativa. Rascunho mantém o trabalho interno. Arquivado preserva o conteúdo sem mantê-lo como publicação ativa.</p><h2>Revisões</h2><p>Quando título, resumo ou conteúdo mudam, o Support salva um snapshot anterior em Revisões. Esse snapshot é uma revisão de conteúdo e não um backup integral do artigo.</p>'],
    ['Como organizar artigos com Produtos e Categorias', 'como-organizar-artigos-com-produtos-e-categorias', 'support', 'organization', ['produtos','categorias'], 'Use Produtos e Categorias para criar uma taxonomia clara e sustentável.', '<h2>Produtos</h2><p>Produto identifica a área principal sobre a qual o artigo fala, como Moves Support ou Moves Editor.</p><h2>Categorias</h2><p>Categoria agrupa assuntos dentro do mesmo Produto e pode formar uma hierarquia. A categoria pai precisa pertencer ao mesmo Produto.</p><h2>Boas práticas</h2><ul><li>Evite nomes duplicados ou genéricos.</li><li>Escolha uma única categoria principal por artigo.</li><li>Não exclua estruturas em uso; primeiro reorganize seus artigos.</li></ul>'],
    ['Como utilizar Tags', 'como-utilizar-tags', 'support', 'organization', ['tags','artigos'], 'Classifique temas transversais com tags úteis e consistentes.', '<h2>Para que servem</h2><p>Tags conectam artigos por temas que atravessam Produtos e Categorias, como SEO, imagens ou revisões.</p><h2>Como usar</h2><p>No formulário do artigo, selecione as tags existentes ou informe as previstas pela interface. Ao salvar, as relações são sincronizadas sem apagar os artigos.</p><h2>Boas práticas</h2><p>Prefira termos curtos, reutilizáveis e sem duplicações. Categoria define o assunto principal; tag acrescenta contexto.</p>'],
    ['Como utilizar o Moves Editor', 'como-utilizar-o-moves-editor', 'editor', 'editor', ['editor','artigos'], 'Conheça os recursos de edição visual e HTML do Moves Editor 1.0.0.', '<h2>Onde o editor aparece</h2><p>O Moves Editor é usado nos formulários editoriais do Support e do CMS.</p>' . $figure($screenshots['support-editor'], 'Moves Editor aberto no formulário de novo artigo do Support.', 'A barra de ferramentas fica acima da área de conteúdo; classificação e publicação permanecem nos painéis laterais.') . '<h2>Modos de edição</h2><p>O modo Visual oferece formatação direta. O modo HTML permite revisar a marcação produzida. Alterne entre eles sem sair do formulário.</p><h2>Recursos</h2><ul><li>Headings, parágrafo e formatação em negrito, itálico e sublinhado.</li><li>Listas, citação, código, links, alinhamento e recuo.</li><li>Tabelas e imagens com ALT, legenda, alinhamento e largura.</li><li>Preview, tela cheia, contador e estimativa de leitura.</li></ul><h2>Usando o Moves Editor no CMS</h2><p>Em Páginas e Artigos, produza o conteúdo no editor e use a Biblioteca de Mídia para inserir imagens administradas pelo sistema. Salve e reabra o registro para confirmar a persistência.</p><div class="help-callout help-callout-important"><strong>Segurança</strong><p>O servidor remove scripts, eventos e URLs perigosas. Vídeo externo só é aceito por embed controlado do YouTube sem cookies ou Vimeo.</p></div>'],
    ['Como inserir e configurar imagens', 'como-inserir-e-configurar-imagens', 'editor', 'media', ['editor','imagens'], 'Envie ou selecione imagens e configure acessibilidade, legenda e dimensões.', '<h2>Inserir imagem</h2><p>No Moves Editor, use a ação de imagem e selecione um arquivo da biblioteca oficial. Para a capa, use Escolher da biblioteca no painel lateral.</p><h2>Configuração</h2><p>Informe texto alternativo objetivo, legenda quando necessária, largura em porcentagem ou pixels e alinhamento. O texto ALT descreve a informação visual para acessibilidade.</p><h2>Verificação</h2><p>Salve, reabra o artigo e confirme imagem, ALT, legenda, dimensão e alinhamento. A mídia continua administrada pela tabela studio_media.</p>'],
    ['Como funciona o SEO dos artigos', 'como-funciona-o-seo-dos-artigos', 'support', 'articles', ['seo','artigos'], 'Preencha título, descrição, palavra-chave, canonical e diretivas de indexação.', '<h2>Campos</h2><p>Meta title identifica a página nos resultados de busca. Meta description resume o benefício. Focus keyword registra o tema principal. Canonical aponta para a URL preferencial quando necessário.</p><h2>Boas práticas</h2><p>Use textos naturais, específicos e coerentes com o conteúdo. Não repita palavras-chave artificialmente e não informe canonical sem necessidade.</p><h2>Robots</h2><p>As opções index e follow controlam as diretivas editoriais armazenadas. O SEO não substitui conteúdo útil, hierarquia clara e URLs estáveis.</p>'],
    ['Como funcionam os Rascunhos', 'como-funcionam-os-rascunhos', 'support', 'articles', ['rascunhos','artigos'], 'Entenda rascunhos salvos e a recuperação local do Moves Editor.', '<h2>Rascunho editorial</h2><p>Um artigo com status Rascunho fica salvo no banco e pode ser localizado pela página Rascunhos e pelos filtros.</p><h2>Rascunho local</h2><p>Durante a edição, o navegador mantém uma cópia temporária vinculada ao documento. A recuperação só é oferecida para o mesmo artigo quando a cópia é relevante e diferente.</p><h2>Após salvar</h2><p>O rascunho local é removido quando o servidor confirma o salvamento. Em caso de erro, ele permanece disponível para evitar perda de trabalho.</p>'],
    ['Como funcionam as Revisões', 'como-funcionam-as-revisoes', 'support', 'organization', ['revisoes','artigos'], 'Consulte snapshots anteriores de título, resumo e conteúdo.', '<h2>Quando são criadas</h2><p>Uma revisão é criada antes de salvar mudanças em título, resumo ou conteúdo de um artigo existente.</p><h2>O que contém</h2><p>O snapshot guarda título, resumo, conteúdo, autor da alteração e data. A listagem permite localizar e visualizar essas informações.</p><h2>Limitação atual</h2><p>Revisões são histórico de conteúdo, não backup completo. A restauração automática de snapshot fica planejada para uma versão posterior após validação transacional específica.</p>'],
    ['Como funciona a Lixeira', 'como-funciona-a-lixeira', 'support', 'organization', ['lixeira','artigos'], 'Remova, restaure ou exclua definitivamente artigos com segurança.', '<h2>Mover para a lixeira</h2><p>A ação remove o artigo das listagens, métricas e relatórios normais sem apagar imediatamente seus dados.</p><h2>Restaurar</h2><p>Restaurar devolve o artigo com slug, conteúdo, autor, classificação, tags, SEO, mídia e revisões preservados.</p><h2>Excluir definitivamente</h2><p>A exclusão permanente apaga o artigo e seus relacionamentos dependentes. Use apenas em registros descartáveis ou quando houver certeza de que não será necessário recuperar.</p>'],
    ['Como pesquisar e filtrar artigos', 'como-pesquisar-e-filtrar-artigos', 'support', 'articles', ['artigos','produtos','categorias'], 'Combine busca, Produto, Categoria, status e paginação sem perder o contexto.', '<h2>Busca</h2><p>Informe parte do título, resumo ou slug na caixa de pesquisa.</p><h2>Filtros</h2><p>Combine Produto, Categoria e status editorial. A consulta é executada no servidor e a paginação preserva os parâmetros ativos.</p><h2>Resultado esperado</h2><p>A lista e o total devem refletir somente os registros compatíveis. Limpe os campos ou use a ação correspondente para retornar à visão completa.</p>'],
    ['Como funciona a Caixa de entrada', 'como-funciona-a-caixa-de-entrada', 'support', 'service', ['atendimento'], 'Conheça o layout preparado para a futura entrada operacional de chamados.', '<h2>Estado atual</h2><p>A Caixa de entrada possui layout final com lista de chamados, área de atendimento e painel de detalhes.</p><h2>Funcionamento planejado</h2><p>Quando o motor de atendimento for habilitado, novos chamados aparecerão na lista, a conversa ocupará o painel central e solicitante, status e histórico serão exibidos nos detalhes.</p><h2>Disponibilidade</h2><p>O backend de tickets ainda não está habilitado. O estado vazio é intencional e não representa falha da Knowledge Base.</p>'],
    ['Como funcionarão Meus chamados', 'como-funcionarao-meus-chamados', 'support', 'service', ['atendimento'], 'Entenda a visão preparada para chamados atribuídos ao usuário autenticado.', '<h2>Objetivo</h2><p>Meus chamados exibirá somente tickets sob responsabilidade do usuário autenticado.</p><h2>Layout preparado</h2><p>A página já reserva busca, filtros e colunas de chamado, assunto, solicitante, prioridade, status e atualização.</p><h2>Disponibilidade</h2><p>A atribuição e a consulta de tickets dependem do futuro motor de atendimento. Nenhum registro fictício é exibido enquanto essa integração não estiver ativa.</p>'],
    ['Como funcionará a visão Todos os chamados', 'como-funcionara-a-visao-todos-os-chamados', 'support', 'service', ['atendimento'], 'Conheça a visão administrativa planejada para supervisão de tickets.', '<h2>Objetivo</h2><p>Todos os chamados será a visão de supervisão para pesquisar e acompanhar tickets de toda a operação autorizada.</p><h2>Layout preparado</h2><p>A tela prevê filtros por status, prioridade, Produto e responsável, além de paginação e colunas operacionais.</p><h2>Disponibilidade</h2><p>O layout está concluído; permissões, filas e dados dependerão do backend de tickets futuro.</p>'],
    ['Como funcionará o SLA', 'como-funcionara-o-sla', 'support', 'service', ['sla','atendimento'], 'Entenda o espaço preparado para políticas reais de tempo de atendimento.', '<h2>Objetivo</h2><p>SLA organizará compromissos de primeira resposta e resolução por prioridade e horário de atendimento.</p><h2>Layout preparado</h2><p>A interface prevê prioridade, primeira resposta, resolução, horário e status.</p><h2>Disponibilidade</h2><p>Nenhuma política fictícia foi criada. O backend de SLA será habilitado junto ao motor de chamados, após definição das regras operacionais reais.</p>'],
    ['Como funciona a área de Usuários', 'como-funciona-a-area-de-usuarios', 'platform', 'users', ['usuarios'], 'Consulte usuários reais e refine a lista por busca, perfil e situação.', '<h2>Como acessar</h2><p>No Moves Support, abra Usuários na navegação lateral.</p><h2>Recursos</h2><p>A página consulta usuários reais e permite buscar por nome ou e-mail, além de filtrar perfil e status.</p><h2>Segurança</h2><p>Senhas e dados sensíveis não aparecem na listagem. Alterações de identidade e permissões continuam sujeitas às regras centrais da plataforma.</p>'],
    ['Como funcionam os Relatórios do Support', 'como-funcionam-os-relatorios-do-support', 'support', 'kb', ['artigos','revisoes','produtos'], 'Acompanhe métricas reais da Knowledge Base por status e classificação.', '<h2>Indicadores</h2><p>Relatórios consolida artigos ativos, publicados, rascunhos, arquivados, Produtos, Categorias, Tags e Revisões.</p><h2>Distribuições</h2><p>Os painéis agrupam artigos por status, Produto e Categoria usando consultas reais ao banco.</p><h2>Regras</h2><p>Artigos na lixeira não entram nas métricas normais. Os números mudam após criar, publicar, arquivar, restaurar ou excluir registros.</p>'],
    ['Conhecendo o Moves CMS', 'conhecendo-o-moves-cms', 'cms', 'cms-start', ['cms','primeiros-passos'], 'Entenda o CMS do Moves Studio, as áreas disponíveis e o fluxo real de publicação.', '<h2>O que é o Moves CMS</h2><p>O Moves CMS é a área do Moves Studio usada para administrar o conteúdo público do site. Ele reúne Páginas, Projetos, Artigos, Destaques, Depoimentos, FAQ e a Biblioteca de Mídia.</p><div class="help-callout help-callout-note"><strong>CMS e Base de Conhecimento são áreas diferentes</strong><p>O CMS publica o site institucional. A Base de Conhecimento organiza a documentação exibida nesta Central de Ajuda.</p></div><h2>Como acessar</h2><ol><li>Entre no Moves com uma conta que possua a permissão de conteúdo.</li><li>Abra <strong>CMS</strong> no seletor de aplicativos.</li><li>Use a navegação lateral para escolher o tipo de conteúdo.</li></ol><h2>Fluxo geral</h2><ol><li>Crie ou abra um registro.</li><li>Preencha conteúdo, classificação, imagem e SEO disponíveis.</li><li>Salve como Rascunho ou altere para Publicado.</li><li>Abra o site público para conferir o resultado.</li></ol><p>Continue em <a href="/help/articles/como-criar-um-conteudo-no-moves-cms">Como criar um conteúdo no Moves CMS</a>.</p>'],
    ['Visão geral do Moves CMS', 'visao-geral-do-moves-cms', 'cms', 'cms-start', ['cms','dashboard'], 'Conheça os indicadores e atalhos reais exibidos no painel inicial do CMS.', '<h2>O que o painel apresenta</h2><p>A visão geral consulta o banco e resume Páginas, Projetos, Artigos, Usuários, Propostas e o estado básico do ambiente. Os cartões levam às respectivas listas quando a conta possui permissão.</p><h2>Ações rápidas</h2><p>Os atalhos abrem diretamente os formulários de nova Página, novo Artigo e novo Projeto, além das áreas de Mídia e Configurações.</p><div class="help-callout help-callout-important"><strong>Os números são operacionais</strong><p>As contagens refletem registros reais; elas não são exemplos fixos da interface.</p></div><h2>Resultado esperado</h2><p>Após criar ou alterar conteúdo, volte ao painel para conferir a atualização dos indicadores compatíveis.</p>'],
    ['Como criar um conteúdo no Moves CMS', 'como-criar-um-conteudo-no-moves-cms', 'cms', 'cms-content', ['cms','conteudo','publicacao'], 'Passo a passo real para criar, classificar, salvar e publicar conteúdo no CMS.', '<h2>Antes de começar</h2><p>Confirme o tipo correto: Página, Projeto, Artigo, Destaque, Depoimento ou FAQ. Os campos variam conforme o tipo.</p><h2>1. Abra o módulo</h2><p>No CMS, escolha o tipo de conteúdo. A lista apresenta os registros reais e seus status.</p>' . $figure($screenshots['cms-articles'], 'Lista de artigos do Moves CMS com busca, status e ações.', 'A lista de Artigos é o ponto de partida para criar ou localizar conteúdo editorial.') . '<h2>2. Preencha o registro</h2><ol><li>Informe o título. O sistema sugere um slug que pode ser ajustado antes de salvar.</li><li>Preencha resumo e conteúdo quando esses campos estiverem disponíveis.</li><li>Para Artigo, Projeto ou FAQ, escolha ou crie a categoria pelo próprio formulário.</li><li>Selecione uma imagem da Biblioteca de Mídia quando necessário.</li><li>Revise título e descrição de SEO.</li><li>Escolha Rascunho ou Publicado e salve.</li></ol><div class="help-callout help-callout-tip"><strong>Dica</strong><p>Salve como Rascunho enquanto o texto ainda estiver em revisão. Somente conteúdo Publicado pode ser consumido pelas páginas públicas.</p></div><h2>Resultado esperado</h2><p>O registro volta a aparecer na lista do módulo, com título, status e data atualizados.</p>'],
    ['Como editar um conteúdo no Moves CMS', 'como-editar-um-conteudo-no-moves-cms', 'cms', 'cms-content', ['cms','conteudo','revisao'], 'Localize um registro, altere seus campos e confirme a persistência no CMS.', '<h2>Localizar e abrir</h2><ol><li>Abra o módulo do conteúdo.</li><li>Use a busca por texto ou o filtro de status.</li><li>Selecione a ação de edição na linha correspondente.</li></ol><h2>Alterar e salvar</h2><p>Atualize apenas os campos necessários, revise o status e salve. Reabra o registro para confirmar texto, mídia, categoria e SEO.</p><h2>Revisões</h2><p>Páginas e Artigos registram snapshots anteriores quando o conteúdo é alterado. A tela de Revisões permite consultar e restaurar uma versão disponível.</p><div class="help-callout help-callout-warning"><strong>Atenção ao slug</strong><p>Alterar o slug muda a URL pública do conteúdo. Verifique links existentes antes de confirmar.</p></div>'],
    ['Status e fluxo de publicação no Moves CMS', 'status-e-fluxo-de-publicacao-no-moves-cms', 'cms', 'cms-content', ['cms','publicacao','rascunho'], 'Entenda os três status reais: Rascunho, Publicado e Arquivado.', '<h2>Status disponíveis</h2><ul><li><strong>Rascunho:</strong> registro persistido no banco, ainda fora do consumo público.</li><li><strong>Publicado:</strong> conteúdo elegível para aparecer no site.</li><li><strong>Arquivado:</strong> conteúdo preservado no CMS, mas retirado do fluxo de publicação.</li></ul><h2>Fluxo recomendado</h2><p>Novo → Rascunho → Publicado → Arquivado.</p><div class="help-callout help-callout-note"><strong>Sem lixeira no CMS nesta versão</strong><p>A exclusão disponível nos módulos do CMS é definitiva. A lixeira documentada no Moves Support pertence à Base de Conhecimento, não ao CMS.</p></div>'],
    ['Como criar e gerenciar páginas no Moves CMS', 'como-criar-e-gerenciar-paginas-no-moves-cms', 'cms', 'cms-content', ['cms','pagina','seo'], 'Crie páginas institucionais com rota pública automática, template, mídia e SEO.', '<h2>Página e Artigo</h2><p>Página atende conteúdos institucionais acessados por uma URL própria. Artigo pertence à listagem de conteúdos e pode usar categoria e data de publicação.</p><h2>Criar uma página</h2><ol><li>Abra <strong>Páginas</strong> e selecione nova página.</li><li>Informe título, slug, resumo e conteúdo.</li><li>Escolha template, imagem e status quando disponíveis.</li><li>Revise SEO e salve.</li></ol><h2>Rota automática</h2><p>Ao salvar, o slug define a rota pública em <code>/pagina/{slug}</code>. Não é necessário criar arquivo de rota manualmente.</p><h2>Gerenciar</h2><p>Use busca e filtro de status para localizar a página. Páginas também participam do histórico de revisões.</p>'],
    ['Como utilizar a Biblioteca de Mídia no Moves CMS', 'como-utilizar-a-biblioteca-de-midia-no-moves-cms', 'cms', 'cms-media', ['cms','midia','imagens'], 'Envie, pesquise, selecione e reutilize imagens armazenadas na biblioteca oficial.', '<h2>Como acessar</h2><p>No CMS, abra <strong>Mídia</strong>. A biblioteca consulta registros reais de <code>studio_media</code>.</p>' . $figure($screenshots['cms-media'], 'Biblioteca de Mídia do Moves CMS com arquivos reais e controles de envio.', 'A Biblioteca de Mídia centraliza imagens reutilizadas pelo CMS, Support e Help Center.') . '<h2>Enviar e organizar</h2><ol><li>Selecione a ação de envio.</li><li>Escolha um arquivo aceito e conclua o upload.</li><li>Informe um texto ALT útil.</li><li>Use busca e seleção para localizar a mídia.</li></ol><h2>Usar no conteúdo</h2><p>A imagem pode ser escolhida como capa ou inserida pelo Moves Editor. O sistema mantém o vínculo pelo identificador da mídia.</p><div class="help-callout help-callout-warning"><strong>Exclusão protegida</strong><p>Uma mídia associada diretamente a conteúdo ou à capa de um artigo do Support não pode ser removida. Verifique o uso antes de excluir.</p></div><h2>Limitações atuais</h2><p>A biblioteca armazena ALT e dimensões. Não existe campo independente de legenda no cadastro da mídia; a legenda é definida no contexto do editor. A listagem atual retorna até 200 registros e não possui paginação.</p>'],
    ['Como definir a imagem de capa no Moves CMS', 'como-definir-a-imagem-de-capa-no-moves-cms', 'cms', 'cms-media', ['cms','midia','capa'], 'Selecione uma imagem existente em studio_media para representar o conteúdo.', '<h2>Selecionar a capa</h2><ol><li>Abra o formulário do conteúdo.</li><li>Na seção de imagem, abra a Biblioteca de Mídia.</li><li>Pesquise e selecione a imagem desejada.</li><li>Confirme o formulário e salve.</li></ol><h2>Acessibilidade</h2><p>Cadastre um ALT que explique a informação relevante da imagem sem repetir mecanicamente o título.</p><h2>Resultado esperado</h2><p>Ao reabrir o registro, a mídia selecionada continua vinculada e pode ser consumida pelo site público.</p>'],
    ['Como organizar conteúdos com Categorias no Moves CMS', 'como-organizar-conteudos-com-categorias-no-moves-cms', 'cms', 'cms-content', ['cms','categorias'], 'Crie e associe categorias nos módulos que oferecem classificação.', '<h2>Onde categorias estão disponíveis</h2><p>Na versão atual, Artigos, Projetos e FAQ permitem associar uma categoria. A criação pode ser feita pelo próprio formulário.</p><h2>Como usar</h2><ol><li>Abra o formulário do conteúdo.</li><li>Escolha uma categoria existente ou informe uma nova categoria na ação disponível.</li><li>Salve o registro.</li></ol><div class="help-callout help-callout-note"><strong>Limitação atual</strong><p>O CMS ainda não possui uma tela própria para editar, contar ou excluir categorias. Não há hierarquia de categorias nos módulos de conteúdo.</p></div>'],
    ['Como configurar SEO no Moves CMS', 'como-configurar-seo-no-moves-cms', 'cms', 'cms-content', ['cms','seo'], 'Configure os campos reais de título e descrição usados como metadados públicos.', '<h2>Campos disponíveis</h2><ul><li><strong>Título SEO:</strong> título alternativo para mecanismos de busca e compartilhamento.</li><li><strong>Descrição SEO:</strong> resumo curto do conteúdo.</li></ul><h2>Comportamento automático</h2><p>Quando os campos não são preenchidos, o sistema usa o título e o resumo do conteúdo como fallback. Isso mantém metadados básicos sem exigir duplicação de texto.</p><h2>Boa prática</h2><p>Escreva para pessoas, use termos coerentes com a página e evite repetição artificial.</p><div class="help-callout help-callout-note"><strong>Campos não disponíveis</strong><p>Focus keyword, canonical e controles Robots não fazem parte do CMS atual. Esses campos existem na Base de Conhecimento do Support, que possui modelo editorial próprio.</p></div>'],
    ['Como funcionam URLs e Slugs no Moves CMS', 'como-funcionam-urls-e-slugs-no-moves-cms', 'cms', 'cms-content', ['cms','slug','url'], 'Entenda a geração do slug, unicidade e impacto da alteração da URL.', '<h2>Geração</h2><p>O formulário sugere um slug a partir do título. Ao salvar, o servidor normaliza caracteres e garante uma versão utilizável na URL.</p><h2>Unicidade</h2><p>O slug precisa ser único dentro do tipo de conteúdo. Em caso de conflito, ajuste o valor antes de salvar.</p><h2>Rotas públicas</h2><p>Páginas usam <code>/pagina/{slug}</code>. Artigos usam <code>/conteudo/{slug}</code>.</p><div class="help-callout help-callout-warning"><strong>Alterações quebram links antigos</strong><p>A versão atual não cria redirecionamento automático quando o slug muda.</p></div>'],
    ['Como funcionam Rascunhos e Revisões no Moves CMS', 'como-funcionam-rascunhos-e-revisoes-no-moves-cms', 'cms', 'cms-content', ['cms','rascunho','revisao'], 'Diferencie o status Rascunho do histórico de versões de Páginas e Artigos.', '<h2>Rascunho persistido</h2><p>Ao salvar com status Rascunho, o conteúdo fica registrado no banco e pode ser localizado pelos filtros do módulo. O Moves Editor do CMS não possui autosave local nesta versão.</p><h2>Revisões</h2><p>Ao alterar uma Página ou Artigo, o CMS preserva um snapshot com os principais campos editoriais, autor e data. A tela de Revisões permite consultar e restaurar versões existentes.</p><h2>Escopo</h2><p>Projetos, Destaques, Depoimentos e FAQ não participam do mesmo histórico de revisões nesta versão.</p>'],
    ['Como pesquisar e filtrar conteúdos no Moves CMS', 'como-pesquisar-e-filtrar-conteudos-no-moves-cms', 'cms', 'cms-content', ['cms','busca'], 'Localize conteúdo pelos filtros realmente disponíveis nas listas do CMS.', '<h2>Busca</h2><p>As listas permitem pesquisar texto associado ao conteúdo.</p><h2>Status</h2><p>Combine a busca com Rascunho, Publicado ou Arquivado para reduzir o conjunto exibido.</p><h2>Limites atuais</h2><p>As listas retornam até 200 registros e ainda não oferecem paginação nem filtros específicos por autor ou categoria.</p>'],
];

$created = 0;
$updated = 0;
$preserved = 0;
foreach ($articles as [$title, $slug, $productKey, $categoryKey, $tags, $excerpt, $content]) {
    $existing = $articleService->findBySlug($slug);
    $arguments = [
        $title, $products[$productKey], $categories[$categoryKey], $excerpt, $content,
        $authorId, $slug, null, $title . ' | Moves', $excerpt,
        $tags[0] ?? null, null, true, true, $tags, 'published',
    ];
    if ($existing === null) {
        $articleService->create(...$arguments);
        $created++;
        continue;
    }
    if (!$refreshExisting) {
        $preserved++;
        continue;
    }
    $articleService->update(
        (int) $existing->id, $title, $products[$productKey], $categories[$categoryKey],
        $excerpt, $content, 'published', $authorId, $authorId, $slug, null,
        $title . ' | Moves', $excerpt, $tags[0] ?? null, null, true, true, $tags
    );
    $updated++;
}

echo "Moves Support KB: {$created} criado(s), {$updated} atualizado(s), {$preserved} preservado(s)." . PHP_EOL;
echo $refreshExisting
    ? "Modo explícito --refresh-existing: conteúdo oficial existente foi atualizado." . PHP_EOL
    : "Modo seguro: artigos existentes não foram sobrescritos. Use --refresh-existing somente para uma atualização editorial intencional." . PHP_EOL;
