<?php

declare(strict_types=1);

require dirname(__DIR__) . '/vendor/autoload.php';

use Moves\Boot\Connection;
use Moves\Boot\Environment;
use Moves\Core\Config;
use Moves\Services\Platform\CompanyService;

Environment::load(dirname(__DIR__));
$base=rtrim((string)Config::get('APP_URL',''),'/');$database=(string)Config::get('DB_DATABASE','');$host=(string)parse_url($base,PHP_URL_HOST);
if(Config::environment()!=='testing'||!preg_match('/^moves_codex_erp_people_[a-zA-Z0-9_]+$/',$database)||!in_array(gethostbyname($host),['127.0.0.1','::1'],true)){
    throw new RuntimeException('People E2E requer APP_ENV=testing, APP_URL local e DB_DATABASE moves_codex_erp_people_*.');
}
$pdo=Connection::getInstance();$suffix=bin2hex(random_bytes(5));$password='MovesERP-People-QA-2026!';
$seedTenant=static function(string $name,string $slug,string $email,bool $erpEnabled=true)use($pdo,$password):array{
    $pdo->prepare("INSERT INTO users(name,email,password,status,role) VALUES(?,?,?,'active','user')")->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT)]);$user=(int)$pdo->lastInsertId();
    $pdo->prepare("INSERT INTO talk_tenants(name,slug,status) VALUES(?,?,'active')")->execute([$name,$slug]);$tenant=(int)$pdo->lastInsertId();
    (new CompanyService($pdo))->ensureRoles($tenant);$roleQuery=$pdo->prepare("SELECT id FROM platform_roles WHERE tenant_id=? AND slug='owner'");$roleQuery->execute([$tenant]);$role=(int)$roleQuery->fetchColumn();
    $pdo->prepare("INSERT INTO talk_tenant_users(tenant_id,user_id,role,role_id,status,is_default) VALUES(?,?,'admin',?,'active',1)")->execute([$tenant,$user,$role]);
    $pdo->prepare("INSERT INTO platform_tenant_products(tenant_id,product,enabled) VALUES(?,'erp',?)")->execute([$tenant,$erpEnabled?1:0]);
    $taxSuffix=substr(hash('sha256',$slug),0,10);$pdo->prepare("INSERT INTO erp_administrators(tenant_id,legal_name,trade_name,tax_id,status) VALUES(?,?,?,?, 'active')")->execute([$tenant,$name,$name,'Q'.$taxSuffix]);$administrator=(int)$pdo->lastInsertId();
    $pdo->prepare("INSERT INTO erp_scope_grants(user_id,capability,scope_type,scope_id) VALUES(?,'erp.access','administrator',?)")->execute([$user,$administrator]);
    $pdo->prepare("INSERT INTO erp_condominiums(administrator_id,legal_name,trade_name,tax_id,status,city,state) VALUES(?,?,?,?, 'active','São Paulo','SP')")->execute([$administrator,'Residencial '.$name,'Residencial '.$name,'C'.$taxSuffix]);$condo=(int)$pdo->lastInsertId();
    return ['user'=>$user,'tenant'=>$tenant,'administrator'=>$administrator,'condo'=>$condo,'email'=>$email];
};
$a=$seedTenant('Administradora QA A','people-a-'.$suffix,'people-a-'.$suffix.'@example.test');$b=$seedTenant('Administradora QA B','people-b-'.$suffix,'people-b-'.$suffix.'@example.test');$noErp=$seedTenant('Administradora sem ERP','people-noerp-'.$suffix,'people-noerp-'.$suffix.'@example.test',false);
$pdo->prepare("INSERT INTO erp_condominiums(administrator_id,legal_name,trade_name,tax_id,status,city,state) VALUES(?,?,?,?,'active','São Paulo','SP')")->execute([$a['administrator'],'Residencial QA A2','Residencial QA A2','C'.substr(hash('sha256','second'.$suffix),0,10)]);$a['condo2']=(int)$pdo->lastInsertId();
$checkCount=0;$check=static function(bool $ok,string $label)use(&$checkCount):void{if(!$ok)throw new RuntimeException('FAIL: '.$label);++$checkCount;echo 'PASS: '.$label.PHP_EOL;};
$cookieA=tempnam(sys_get_temp_dir(),'moves-people-a-');$cookieB=tempnam(sys_get_temp_dir(),'moves-people-b-');$cookieNoErp=tempnam(sys_get_temp_dir(),'moves-people-noerp-');
$makeClient=static function(string $cookie)use($base):Closure{
    $curl=curl_init();if(!$curl instanceof CurlHandle)throw new RuntimeException('cURL indisponível.');
    curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_COOKIEFILE=>$cookie,CURLOPT_COOKIEJAR=>$cookie,CURLOPT_PROXY=>'',CURLOPT_TIMEOUT=>15]);
    return static function(string $path,?array $data=null)use($curl,$base):array{
        curl_setopt($curl,CURLOPT_URL,$base.$path);if($data===null){curl_setopt($curl,CURLOPT_HTTPGET,true);curl_setopt($curl,CURLOPT_POST,false);}else{curl_setopt($curl,CURLOPT_POST,true);curl_setopt($curl,CURLOPT_POSTFIELDS,http_build_query($data));}
        $raw=curl_exec($curl);if(!is_string($raw))throw new RuntimeException('HTTP falhou: '.curl_error($curl));$size=(int)curl_getinfo($curl,CURLINFO_HEADER_SIZE);$headers=substr($raw,0,$size);preg_match('/^Location:\s*(.+)$/mi',$headers,$location);return ['status'=>(int)curl_getinfo($curl,CURLINFO_RESPONSE_CODE),'location'=>trim($location[1]??''),'body'=>substr($raw,$size)];
    };
};
$csrf=static function(string $body):string{if(!preg_match('/name="_token"\s+value="([^"]+)"/',$body,$m))throw new RuntimeException('CSRF ausente na página.');return html_entity_decode($m[1],ENT_QUOTES|ENT_HTML5);};
$requestA=$makeClient((string)$cookieA);$loginPage=$requestA('/login');$check($loginPage['status']===200,'login tenant A HTTP 200');$authA=$requestA('/login',['email'=>$a['email'],'password'=>$password,'_token'=>$csrf($loginPage['body'])]);$check($authA['status']===302&&str_ends_with($authA['location'],'/day'),'autenticação A direciona para Meu Dia');
$people=$requestA('/erp/people');$units=$requestA('/erp/units');$check($people['status']===200&&str_contains($people['body'],'Nenhuma pessoa encontrada'),'Pessoas responde 200 com empty state real');$check($units['status']===200&&str_contains($units['body'],'Nenhuma unidade encontrada'),'Unidades responde 200 com empty state real');$check(str_contains($people['body'],'erp.css')&&str_contains($people['body'],'Navegação do ERP'),'shell, sidebar e CSS carregados');
$form=$requestA('/erp/units/new');$check($form['status']===200&&str_contains($form['body'],'Cadastrar unidade'),'formulário de unidade carrega');
$unitToken=$csrf($form['body']);$createUnit=$requestA('/erp/units',['_token'=>$unitToken,'condominium_id'=>(string)$a['condo'],'block'=>'Torre A','code'=>'201','complement'=>'Fundos']);$check($createUnit['status']===302&&str_contains($createUnit['location'],'/erp/units/'),'unidade salva por HTTP');preg_match('~/erp/units/(\d+)~',$createUnit['location'],$unitMatch);$unitId=(int)($unitMatch[1]??0);$check($unitId>0,'unidade persistida com identificador');
$unitEdit=$requestA('/erp/units/'.$unitId.'/edit');$check($unitEdit['status']===200&&str_contains($unitEdit['body'],'value="201"')&&str_contains($unitEdit['body'],'value="Fundos"')&&str_contains($unitEdit['body'],'Condomínio, bloco e situação são preservados')&&!str_contains($unitEdit['body'],'name="block"')&&!str_contains($unitEdit['body'],'name="condominium_id"'),'formulário de edição mantém o escopo estrutural');
$editToken=$csrf($unitEdit['body']);$editResponse=$requestA('/erp/units/'.$unitId.'/edit',['_token'=>$editToken,'code'=>'201-A','complement'=>'Fundos — acesso lateral']);$check($editResponse['status']===302&&str_ends_with($editResponse['location'],'/erp/units/'.$unitId),'identificador e complemento atualizados por HTTP');
$unitQuery=$pdo->prepare('SELECT condominium_id,block_id,code,complement,status FROM erp_units WHERE id=?');$unitQuery->execute([$unitId]);$editedUnit=$unitQuery->fetch(PDO::FETCH_ASSOC);$check($editedUnit!==false&&$editedUnit['code']==='201-A'&&$editedUnit['complement']==='Fundos — acesso lateral'&&(int)$editedUnit['condominium_id']===$a['condo']&&$editedUnit['block_id']!==null&&$editedUnit['status']==='active','MySQL persiste edição sem alterar condomínio, bloco ou situação');
$check(str_contains($requestA('/erp/units/'.$unitId)['body'],'201-A')&&str_contains($requestA('/erp/units/'.$unitId)['body'],'Fundos — acesso lateral'),'detalhe da unidade exibe os valores atualizados');
$updatedAudit=$pdo->prepare("SELECT COUNT(*) FROM platform_audit_events WHERE tenant_id=? AND event_type='erp.unit.updated' AND subject_id=?");$updatedAudit->execute([$a['tenant'],$unitId]);$check((int)$updatedAudit->fetchColumn()===1,'edição registra evento de auditoria tenant-scoped');
$createExtraUnit=static function(int $condominium,string $code)use($requestA,$unitToken,$check):int{$response=$requestA('/erp/units',['_token'=>$unitToken,'condominium_id'=>(string)$condominium,'block'=>'Torre A','code'=>$code]);$check($response['status']===302&&str_contains($response['location'],'/erp/units/'),'unidade adicional '.$code.' salva');preg_match('~/erp/units/(\d+)~',$response['location'],$match);return (int)($match[1]??0);};$unit301=$createExtraUnit($a['condo'],'301');$unit402=$createExtraUnit($a['condo'],'402');$unit101=$createExtraUnit($a['condo2'],'101');
$duplicateEdit=$requestA('/erp/units/'.$unitId.'/edit');$duplicateResponse=$requestA('/erp/units/'.$unitId.'/edit',['_token'=>$csrf($duplicateEdit['body']),'code'=>'301','complement'=>'não deve persistir']);$unitQuery->execute([$unitId]);$afterDuplicate=$unitQuery->fetch(PDO::FETCH_ASSOC);$check($duplicateResponse['status']===302&&$afterDuplicate['code']==='201-A'&&$afterDuplicate['complement']==='Fundos — acesso lateral','identificador duplicado no condomínio não altera a unidade');$updatedAudit->execute([$a['tenant'],$unitId]);$check((int)$updatedAudit->fetchColumn()===1,'tentativa duplicada não gera auditoria de mutação');
$personForm=$requestA('/erp/people/new');$personToken=$csrf($personForm['body']);$createPerson=$requestA('/erp/people',['_token'=>$personToken,'entity_type'=>'person','full_name'=>'João Investidor '.$suffix,'document_type'=>'cpf','document_number'=>'12345678901','email'=>'joao@example.test','phone'=>'11999990000','create_link'=>'1','condominium_id'=>(string)$a['condo'],'unit_id'=>(string)$unitId,'role'=>'owner','ownership_fraction_pct'=>'37.5','starts_at'=>'2024-01-01']);$check($createPerson['status']===302&&str_contains($createPerson['location'],'/erp/people/'),'pessoa e vínculo inicial salvos por HTTP');preg_match('~/erp/people/(\d+)~',$createPerson['location'],$personMatch);$personId=(int)($personMatch[1]??0);$check($personId>0,'pessoa persistida com identificador');
$detail=$requestA('/erp/people/'.$personId);$linkToken=$csrf($detail['body']);foreach([[$a['condo'],$unit301],[$a['condo'],$unit402],[$a['condo2'],$unit101]] as [$condo,$extraUnit]){$added=$requestA('/erp/people/'.$personId.'/links',['_token'=>$linkToken,'condominium_id'=>(string)$condo,'unit_id'=>(string)$extraUnit,'role'=>'owner','starts_at'=>date('Y-m-d')]);$check($added['status']===302,'investidor ganha vínculo em outra unidade/condomínio');}
$secondPersonForm=$requestA('/erp/people/new');$secondPerson=$requestA('/erp/people',['_token'=>$csrf($secondPersonForm['body']),'entity_type'=>'person','full_name'=>'Maria Coproprietária '.$suffix,'create_link'=>'1','condominium_id'=>(string)$a['condo'],'unit_id'=>(string)$unitId,'role'=>'owner','starts_at'=>date('Y-m-d')]);$check($secondPerson['status']===302,'segunda coproprietária vinculada à unidade');$detail=$requestA('/erp/people/'.$personId);$unitDetail=$requestA('/erp/units/'.$unitId);$check($detail['status']===200&&str_contains($detail['body'],'João Investidor '.$suffix)&&str_contains($detail['body'],'Proprietário')&&str_contains($detail['body'],'101')&&str_contains($detail['body'],'37,5000%'),'detalhe de pessoa exibe múltiplos vínculos');$check($unitDetail['status']===200&&str_contains($unitDetail['body'],'João Investidor '.$suffix)&&str_contains($unitDetail['body'],'Maria Coproprietária '.$suffix)&&str_contains($unitDetail['body'],'37,5000%'),'detalhe da unidade exibe dois proprietários atuais');$unitList=$requestA('/erp/units');$check($unitList['status']===200&&preg_match('/(?:João Investidor|Maria Coproprietária) '.preg_quote($suffix,'/').' \+1/u',$unitList['body'])===1,'listagem resume múltiplos proprietários sem depender da ordem');
$linkStmt=$pdo->prepare('SELECT id FROM erp_person_links WHERE administrator_id=? AND person_id=?');$linkStmt->execute([$a['administrator'],$personId]);$linkId=(int)$linkStmt->fetchColumn();$closeToken=$csrf($detail['body']);$closed=$requestA('/erp/people/'.$personId.'/links/'.$linkId.'/close',['_token'=>$closeToken,'ends_at'=>date('Y-m-d')]);$check($closed['status']===302,'encerramento de vínculo POST redireciona');$history=$requestA('/erp/people/'.$personId);$check($history['status']===200&&str_contains($history['body'],'Histórico'),'vínculo encerrado permanece no histórico');
$fractionBefore=(int)$pdo->query('SELECT COUNT(*) FROM erp_person_links WHERE ownership_fraction_pct IS NOT NULL')->fetchColumn();$invalidFraction=$requestA('/erp/people/'.$personId.'/links',['_token'=>$csrf($detail['body']),'condominium_id'=>(string)$a['condo'],'unit_id'=>(string)$unitId,'role'=>'resident','ownership_fraction_pct'=>'20','starts_at'=>date('Y-m-d')]);$check($invalidFraction['status']===302&&str_contains($invalidFraction['location'],'/erp/people/'.$personId),'fração em vínculo que não é de proprietário é recusada');$check((int)$pdo->query('SELECT COUNT(*) FROM erp_person_links WHERE ownership_fraction_pct IS NOT NULL')->fetchColumn()===$fractionBefore,'vínculo inválido não persiste fração');$directConstraint=false;try{$pdo->exec('UPDATE erp_person_links SET ownership_fraction_pct=101 WHERE id='.(int)$pdo->query('SELECT id FROM erp_person_links WHERE ownership_fraction_pct IS NOT NULL LIMIT 1')->fetchColumn());}catch(PDOException){$directConstraint=true;}$check($directConstraint,'constraint MySQL bloqueia percentual acima de 100 em escrita direta');
$csrfRejected=$requestA('/erp/units',['_token'=>'bad','condominium_id'=>(string)$a['condo'],'block'=>'','code'=>'csrf']);$check($csrfRejected['status']===302&&str_contains($csrfRejected['location'],'/erp/units/new'),'POST sem CSRF não cria unidade');
$counts=$pdo->prepare('SELECT COUNT(*) FROM erp_person_links WHERE administrator_id=? AND person_id=?');$counts->execute([$a['administrator'],$personId]);$linksBeforeCrossTenant=(int)$counts->fetchColumn();$crossCondo=$requestA('/erp/people/'.$personId.'/links',['_token'=>$csrf($history['body']),'condominium_id'=>(string)$b['condo'],'unit_id'=>'','role'=>'resident','starts_at'=>date('Y-m-d')]);$check($crossCondo['status']===302,'vínculo para condomínio de B é recusado sem exposição');$counts->execute([$a['administrator'],$personId]);$check((int)$counts->fetchColumn()===$linksBeforeCrossTenant,'POST recusado não adiciona vínculo cruzado');
$supplierForm=$requestA('/erp/suppliers/new');$check($supplierForm['status']===200&&str_contains($supplierForm['body'],'Cadastrar fornecedor')&&str_contains($supplierForm['body'],'Pessoa jurídica'),'formulário de fornecedor funcional por HTTP');
$categoryQuery=$pdo->prepare("SELECT id FROM erp_supplier_categories WHERE administrator_id=? AND slug='elevadores'");$categoryQuery->execute([$a['administrator']]);$supplierCategory=(int)$categoryQuery->fetchColumn();$supplierName='Fornecedor E2E '.$suffix;
$supplierCreate=$requestA('/erp/suppliers',['_token'=>$csrf($supplierForm['body']),'entity_type'=>'organization','full_name'=>$supplierName,'trade_name'=>'Elevadores '.$suffix,'document_type'=>'cnpj','document_number'=>'11222333000181','email'=>'fornecedor@example.test','phone'=>'11988887777','category_id'=>(string)$supplierCategory,'condominium_ids'=>[(string)$a['condo']],'starts_at'=>date('Y-m-d')]);$check($supplierCreate['status']===302&&str_contains($supplierCreate['location'],'/erp/suppliers/'),'fornecedor criado e associado a condomínio por HTTP');preg_match('~/erp/suppliers/(\d+)~',$supplierCreate['location'],$supplierMatch);$supplierId=(int)($supplierMatch[1]??0);$check($supplierId>0,'fornecedor persistido com identificador');
$supplierDetail=$requestA('/erp/suppliers/'.$supplierId);$check($supplierDetail['status']===200&&str_contains($supplierDetail['body'],$supplierName)&&str_contains($supplierDetail['body'],'Elevadores')&&str_contains($supplierDetail['body'],'Condomínios atendidos'),'detalhe do fornecedor mostra identidade, categoria e atendimento');
$supplierList=$requestA('/erp/suppliers?q='.rawurlencode($supplierName).'&category='.$supplierCategory.'&condominium='.$a['condo'].'&status=active');$check($supplierList['status']===200&&str_contains($supplierList['body'],$supplierName)&&str_contains($supplierList['body'],'name="status"'),'busca e filtros encontram fornecedor ativo');
$supplierPerson=(int)$pdo->query('SELECT person_id FROM erp_suppliers WHERE id='.$supplierId)->fetchColumn();$personReuse=$pdo->prepare('SELECT COUNT(*) FROM erp_people WHERE administrator_id=? AND id=? AND document_number=?');$personReuse->execute([$a['administrator'],$supplierPerson,'11222333000181']);$check((int)$personReuse->fetchColumn()===1,'fornecedor reutiliza uma identidade do domínio Pessoas');
$supplierAudit=$pdo->prepare('SELECT COUNT(*) FROM platform_audit_events WHERE tenant_id=? AND subject_id=? AND event_type=?');$supplierAudit->execute([$a['tenant'],$supplierId,'erp.supplier.created']);$check((int)$supplierAudit->fetchColumn()===1,'criação do fornecedor registra auditoria');$supplierLinkAudit=$pdo->prepare("SELECT COUNT(*) FROM platform_audit_events WHERE tenant_id=? AND event_type='erp.supplier_condominium.created' AND metadata LIKE ?");$supplierLinkAudit->execute([$a['tenant'],'%'.$supplierId.'%']);$check((int)$supplierLinkAudit->fetchColumn()===1,'associação inicial do condomínio registra auditoria');
$supplierFormAgain=$requestA('/erp/suppliers/new');$supplierCounts=$pdo->prepare('SELECT COUNT(*) FROM erp_suppliers WHERE administrator_id=?');$supplierCounts->execute([$a['administrator']]);$supplierCountBeforeDuplicate=(int)$supplierCounts->fetchColumn();$duplicateSupplier=$requestA('/erp/suppliers',['_token'=>$csrf($supplierFormAgain['body']),'entity_type'=>'organization','full_name'=>'Duplicado '.$suffix,'document_type'=>'cnpj','document_number'=>'11222333000181','category_id'=>(string)$supplierCategory]);$supplierCounts->execute([$a['administrator']]);$check($duplicateSupplier['status']===302&&(int)$supplierCounts->fetchColumn()===$supplierCountBeforeDuplicate,'documento já qualificado não cria fornecedor duplicado');
$supplierCsrf=$csrf($supplierDetail['body']);$invalidSupplierCsrf=$requestA('/erp/suppliers/'.$supplierId.'/status',['_token'=>'invalid','status'=>'inactive']);$check($invalidSupplierCsrf['status']===302,'alteração de situação exige CSRF');$supplierState=$pdo->prepare('SELECT status FROM erp_suppliers WHERE administrator_id=? AND id=?');$supplierState->execute([$a['administrator'],$supplierId]);$check($supplierState->fetchColumn()==='active','POST sem CSRF mantém fornecedor ativo');
$supplierDetail=$requestA('/erp/suppliers/'.$supplierId);$linkTwo=$requestA('/erp/suppliers/'.$supplierId.'/condominiums',['_token'=>$csrf($supplierDetail['body']),'condominium_id'=>(string)$a['condo2'],'starts_at'=>date('Y-m-d')]);$check($linkTwo['status']===302,'fornecedor pode atender outro condomínio da mesma administradora');$supplierLinks=$pdo->prepare('SELECT id,condominium_id,status FROM erp_supplier_condominiums WHERE administrator_id=? AND supplier_id=? ORDER BY id');$supplierLinks->execute([$a['administrator'],$supplierId]);$supplierLinkRows=$supplierLinks->fetchAll(PDO::FETCH_ASSOC);$check(count($supplierLinkRows)===2&&(int)$supplierLinkRows[1]['condominium_id']===$a['condo2'],'vínculos com condomínios persistem no tenant atual');
$overlap=$requestA('/erp/suppliers/'.$supplierId.'/condominiums',['_token'=>$csrf($requestA('/erp/suppliers/'.$supplierId)['body']),'condominium_id'=>(string)$a['condo'],'starts_at'=>date('Y-m-d')]);$supplierLinks->execute([$a['administrator'],$supplierId]);$check($overlap['status']===302&&count($supplierLinks->fetchAll(PDO::FETCH_ASSOC))===2,'período de atendimento sobreposto não duplica vínculo');
$closeSupplierLink=$requestA('/erp/suppliers/'.$supplierId.'/condominiums/'.$supplierLinkRows[1]['id'].'/close',['_token'=>$csrf($requestA('/erp/suppliers/'.$supplierId)['body']),'ends_at'=>date('Y-m-d')]);$check($closeSupplierLink['status']===302,'encerramento do atendimento preserva fluxo HTTP');$supplierLinks->execute([$a['administrator'],$supplierId]);$supplierLinkRows=$supplierLinks->fetchAll(PDO::FETCH_ASSOC);$check($supplierLinkRows[1]['status']==='inactive','encerramento mantém o vínculo no histórico');
$supplierDetail=$requestA('/erp/suppliers/'.$supplierId);$deactivateSupplier=$requestA('/erp/suppliers/'.$supplierId.'/status',['_token'=>$csrf($supplierDetail['body']),'status'=>'inactive']);$check($deactivateSupplier['status']===302,'inativação do fornecedor responde por HTTP');$supplierState->execute([$a['administrator'],$supplierId]);$supplierLinks->execute([$a['administrator'],$supplierId]);$supplierLinkRows=$supplierLinks->fetchAll(PDO::FETCH_ASSOC);$check($supplierState->fetchColumn()==='inactive'&&$supplierLinkRows[0]['status']==='inactive','inativação encerra atendimento vigente e preserva histórico');$supplierAudit->execute([$a['tenant'],$supplierId,'erp.supplier.status_changed']);$check((int)$supplierAudit->fetchColumn()===1,'mudança de situação registra auditoria');
$requestB=$makeClient((string)$cookieB);$loginB=$requestB('/login');$authB=$requestB('/login',['email'=>$b['email'],'password'=>$password,'_token'=>$csrf($loginB['body'])]);$check($authB['status']===302&&str_ends_with($authB['location'],'/day'),'autenticação B direciona para Meu Dia');
$check($requestB('/erp/suppliers/'.$supplierId)['status']===404,'tenant B não acessa detalhe do fornecedor A');$bSupplierForm=$requestB('/erp/suppliers/new');$check($bSupplierForm['status']===200&&!str_contains($bSupplierForm['body'],$supplierName),'tenant B não lista identidade exclusiva de fornecedor A');$bSupplierPost=$requestB('/erp/suppliers/'.$supplierId.'/status',['_token'=>$csrf($bSupplierForm['body']),'status'=>'active']);$supplierState->execute([$a['administrator'],$supplierId]);$check($bSupplierPost['status']===302&&$supplierState->fetchColumn()==='inactive','tenant B não reativa fornecedor A por POST');$bCrossCondominium=$requestB('/erp/suppliers/'.$supplierId.'/condominiums',['_token'=>$csrf($bSupplierForm['body']),'condominium_id'=>(string)$b['condo'],'starts_at'=>date('Y-m-d')]);$supplierLinks->execute([$a['administrator'],$supplierId]);$check($bCrossCondominium['status']===302&&count($supplierLinks->fetchAll(PDO::FETCH_ASSOC))===2,'tenant B não associa fornecedor A a condomínio B');
$check($requestB('/erp/people/'.$personId)['status']===404,'tenant B não acessa detalhe da pessoa A');$check($requestB('/erp/units/'.$unitId)['status']===404,'tenant B não acessa detalhe da unidade A');$check($requestB('/erp/units/'.$unitId.'/edit')['status']===404,'tenant B não acessa formulário de edição da unidade A');$bUnitForm=$requestB('/erp/units/new');$bForbiddenEdit=$requestB('/erp/units/'.$unitId.'/edit',['_token'=>$csrf($bUnitForm['body']),'code'=>'999','complement'=>'cross-tenant']);$unitQuery->execute([$unitId]);$afterForbiddenEdit=$unitQuery->fetch(PDO::FETCH_ASSOC);$check($bForbiddenEdit['status']===404&&$afterForbiddenEdit['code']==='201-A'&&$afterForbiddenEdit['complement']==='Fundos — acesso lateral','tenant B não altera unidade A por POST');$bPeopleList=$requestB('/erp/people');$check($bPeopleList['status']===200&&!str_contains($bPeopleList['body'],'João Investidor '.$suffix),'tenant B não lista nem infere pessoa exclusiva de A');$bPersonForm=$requestB('/erp/people/new');$bCreated=$requestB('/erp/people',['_token'=>$csrf($bPersonForm['body']),'entity_type'=>'person','full_name'=>'Pessoa B '.$suffix]);preg_match('~/erp/people/(\d+)~',$bCreated['location'],$bPersonMatch);$bPersonId=(int)($bPersonMatch[1]??0);$bDetail=$requestB('/erp/people/'.$bPersonId);$bPost=$requestB('/erp/people/'.$bPersonId.'/links',['_token'=>$csrf($bDetail['body']),'condominium_id'=>(string)$b['condo'],'unit_id'=>(string)$unitId,'role'=>'owner','starts_at'=>date('Y-m-d')]);$check($bPost['status']===302,'tenant B não consegue criar vínculo usando unidade de A');
$pdo->prepare("INSERT INTO erp_blocks(condominium_id,code,name) VALUES(?,?,'Torre B')")->execute([$b['condo'],'B-'.$suffix]);$blockB=(int)$pdo->lastInsertId();$crossBlockRejected=false;try{$pdo->prepare('UPDATE erp_units SET block_id=? WHERE id=?')->execute([$blockB,$unitId]);}catch(PDOException){$crossBlockRejected=true;}$unitQuery->execute([$unitId]);$afterCrossBlock=$unitQuery->fetch(PDO::FETCH_ASSOC);$check($crossBlockRejected&&$afterCrossBlock['block_id']!==null&&(int)$afterCrossBlock['block_id']!==$blockB,'FK MySQL impede associar unidade A ao bloco do condomínio B');
$counts->execute([$a['administrator'],$personId]);$check((int)$counts->fetchColumn()===$linksBeforeCrossTenant,'tentativa de B não altera registros de A');
$noErpRequest=$makeClient((string)$cookieNoErp);$noErpLogin=$noErpRequest('/login');$noErpAuth=$noErpRequest('/login',['email'=>$noErp['email'],'password'=>$password,'_token'=>$csrf($noErpLogin['body'])]);$check($noErpAuth['status']===302&&str_ends_with($noErpAuth['location'],'/day'),'tenant sem produto ERP não recebe autorização');$noErpPage=$noErpRequest('/erp/people');$check($noErpPage['status']===403,'tenant com papel ERP mas entitlement desligado recebe 403');
$noRoleEmail='erp-no-permission-'.$suffix.'@example.test';$pdo->prepare("INSERT INTO users(name,email,password,status,role) VALUES(?,?,?,'active','user')")->execute(['Atendente sem ERP',$noRoleEmail,password_hash($password,PASSWORD_DEFAULT)]);$noRoleUser=(int)$pdo->lastInsertId();$agentRole=$pdo->prepare("SELECT id FROM platform_roles WHERE tenant_id=? AND slug='agent'");$agentRole->execute([$a['tenant']]);$pdo->prepare("INSERT INTO talk_tenant_users(tenant_id,user_id,role,role_id,status,is_default) VALUES(?,?,'agent',?,'active',0)")->execute([$a['tenant'],$noRoleUser,(int)$agentRole->fetchColumn()]);$cookieNoPermission=tempnam(sys_get_temp_dir(),'moves-people-nopermission-');$noPermissionRequest=$makeClient((string)$cookieNoPermission);$noPermissionLogin=$noPermissionRequest('/login');$noPermissionAuth=$noPermissionRequest('/login',['email'=>$noRoleEmail,'password'=>$password,'_token'=>$csrf($noPermissionLogin['body'])]);$check($noPermissionAuth['status']===302,'usuário sem erp.access pode autenticar');$noPermissionPage=$noPermissionRequest('/erp/people');$check($noPermissionPage['status']===302&&str_ends_with($noPermissionPage['location'],'/day'),'usuário sem erp.access é barrado pelo middleware de permissão');
$asset=$requestA('/themes/admin/css/erp.css');$check($asset['status']===200,'asset CSS ERP responde HTTP 200');
@unlink((string)$cookieA);@unlink((string)$cookieB);@unlink((string)$cookieNoErp);@unlink((string)$cookieNoPermission);echo "OK: $checkCount verificações HTTP ERP Pessoas/Unidades/Fornecedores.\n";
