<?php

declare(strict_types=1);

require dirname(__DIR__) . '/vendor/autoload.php';

use Moves\Boot\Connection;
use Moves\Boot\Environment;
use Moves\Core\Config;
use Moves\Services\Platform\CompanyService;

Environment::load(dirname(__DIR__));
$base=rtrim((string)Config::get('APP_URL',''),'/');$database=(string)Config::get('DB_DATABASE','');$host=(string)parse_url($base,PHP_URL_HOST);
if(Config::environment()!=='testing'||!preg_match('/^moves_codex_erp_people_[a-zA-Z0-9_]+$/',$database)||!in_array(gethostbyname($host),['127.0.0.1','::1'],true)){
    throw new RuntimeException('People E2E requer APP_ENV=testing, APP_URL local e DB_DATABASE moves_codex_erp_people_*.');
}
$pdo=Connection::getInstance();$suffix=bin2hex(random_bytes(5));$password='MovesERP-People-QA-2026!';
$seedTenant=static function(string $name,string $slug,string $email,bool $erpEnabled=true)use($pdo,$password):array{
    $pdo->prepare("INSERT INTO users(name,email,password,status,role) VALUES(?,?,?,'active','user')")->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT)]);$user=(int)$pdo->lastInsertId();
    $pdo->prepare("INSERT INTO talk_tenants(name,slug,status) VALUES(?,?,'active')")->execute([$name,$slug]);$tenant=(int)$pdo->lastInsertId();
    (new CompanyService($pdo))->ensureRoles($tenant);$roleQuery=$pdo->prepare("SELECT id FROM platform_roles WHERE tenant_id=? AND slug='owner'");$roleQuery->execute([$tenant]);$role=(int)$roleQuery->fetchColumn();
    $pdo->prepare("INSERT INTO talk_tenant_users(tenant_id,user_id,role,role_id,status,is_default) VALUES(?,?,'admin',?,'active',1)")->execute([$tenant,$user,$role]);
    $pdo->prepare("INSERT INTO platform_tenant_products(tenant_id,product,enabled) VALUES(?,'erp',?)")->execute([$tenant,$erpEnabled?1:0]);
    $taxSuffix=substr(hash('sha256',$slug),0,10);$pdo->prepare("INSERT INTO erp_administrators(tenant_id,legal_name,trade_name,tax_id,status) VALUES(?,?,?,?, 'active')")->execute([$tenant,$name,$name,'Q'.$taxSuffix]);$administrator=(int)$pdo->lastInsertId();
    $pdo->prepare("INSERT INTO erp_scope_grants(user_id,capability,scope_type,scope_id) VALUES(?,'erp.access','administrator',?)")->execute([$user,$administrator]);
    $pdo->prepare("INSERT INTO erp_condominiums(administrator_id,legal_name,trade_name,tax_id,status,city,state) VALUES(?,?,?,?, 'active','São Paulo','SP')")->execute([$administrator,'Residencial '.$name,'Residencial '.$name,'C'.$taxSuffix]);$condo=(int)$pdo->lastInsertId();
    return ['user'=>$user,'tenant'=>$tenant,'administrator'=>$administrator,'condo'=>$condo,'email'=>$email];
};
$a=$seedTenant('Administradora QA A','people-a-'.$suffix,'people-a-'.$suffix.'@example.test');$b=$seedTenant('Administradora QA B','people-b-'.$suffix,'people-b-'.$suffix.'@example.test');$noErp=$seedTenant('Administradora sem ERP','people-noerp-'.$suffix,'people-noerp-'.$suffix.'@example.test',false);
$pdo->prepare("INSERT INTO erp_condominiums(administrator_id,legal_name,trade_name,tax_id,status,city,state) VALUES(?,?,?,?,'active','São Paulo','SP')")->execute([$a['administrator'],'Residencial QA A2','Residencial QA A2','C'.substr(hash('sha256','second'.$suffix),0,10)]);$a['condo2']=(int)$pdo->lastInsertId();
$checkCount=0;$check=static function(bool $ok,string $label)use(&$checkCount):void{if(!$ok)throw new RuntimeException('FAIL: '.$label);++$checkCount;echo 'PASS: '.$label.PHP_EOL;};
$cookieA=tempnam(sys_get_temp_dir(),'moves-people-a-');$cookieB=tempnam(sys_get_temp_dir(),'moves-people-b-');$cookieNoErp=tempnam(sys_get_temp_dir(),'moves-people-noerp-');
$makeClient=static function(string $cookie)use($base):Closure{
    $curl=curl_init();if(!$curl instanceof CurlHandle)throw new RuntimeException('cURL indisponível.');
    curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_COOKIEFILE=>$cookie,CURLOPT_COOKIEJAR=>$cookie,CURLOPT_PROXY=>'',CURLOPT_TIMEOUT=>15]);
    return static function(string $path,?array $data=null)use($curl,$base):array{
        curl_setopt($curl,CURLOPT_URL,$base.$path);if($data===null){curl_setopt($curl,CURLOPT_HTTPGET,true);curl_setopt($curl,CURLOPT_POST,false);}else{curl_setopt($curl,CURLOPT_POST,true);curl_setopt($curl,CURLOPT_POSTFIELDS,http_build_query($data));}
        $raw=curl_exec($curl);if(!is_string($raw))throw new RuntimeException('HTTP falhou: '.curl_error($curl));$size=(int)curl_getinfo($curl,CURLINFO_HEADER_SIZE);$headers=substr($raw,0,$size);preg_match('/^Location:\s*(.+)$/mi',$headers,$location);return ['status'=>(int)curl_getinfo($curl,CURLINFO_RESPONSE_CODE),'location'=>trim($location[1]??''),'body'=>substr($raw,$size)];
    };
};
$csrf=static function(string $body):string{if(!preg_match('/name="_token"\s+value="([^"]+)"/',$body,$m))throw new RuntimeException('CSRF ausente na página.');return html_entity_decode($m[1],ENT_QUOTES|ENT_HTML5);};
$requestA=$makeClient((string)$cookieA);$loginPage=$requestA('/login');$check($loginPage['status']===200,'login tenant A HTTP 200');$authA=$requestA('/login',['email'=>$a['email'],'password'=>$password,'_token'=>$csrf($loginPage['body'])]);$check($authA['status']===302&&str_ends_with($authA['location'],'/day'),'autenticação A direciona para Meu Dia');
$people=$requestA('/erp/people');$units=$requestA('/erp/units');$check($people['status']===200&&str_contains($people['body'],'Nenhuma pessoa encontrada'),'Pessoas responde 200 com empty state real');$check($units['status']===200&&str_contains($units['body'],'Nenhuma unidade encontrada'),'Unidades responde 200 com empty state real');$check(str_contains($people['body'],'erp.css')&&str_contains($people['body'],'Navegação do ERP'),'shell, sidebar e CSS carregados');
$form=$requestA('/erp/units/new');$check($form['status']===200&&str_contains($form['body'],'Cadastrar unidade'),'formulário de unidade carrega');
$unitToken=$csrf($form['body']);$createUnit=$requestA('/erp/units',['_token'=>$unitToken,'condominium_id'=>(string)$a['condo'],'block'=>'Torre A','code'=>'201','complement'=>'Fundos']);$check($createUnit['status']===302&&str_contains($createUnit['location'],'/erp/units/'),'unidade salva por HTTP');preg_match('~/erp/units/(\d+)~',$createUnit['location'],$unitMatch);$unitId=(int)($unitMatch[1]??0);$check($unitId>0,'unidade persistida com identificador');
$createExtraUnit=static function(int $condominium,string $code)use($requestA,$unitToken,$check):int{$response=$requestA('/erp/units',['_token'=>$unitToken,'condominium_id'=>(string)$condominium,'block'=>'Torre A','code'=>$code]);$check($response['status']===302&&str_contains($response['location'],'/erp/units/'),'unidade adicional '.$code.' salva');preg_match('~/erp/units/(\d+)~',$response['location'],$match);return (int)($match[1]??0);};$unit301=$createExtraUnit($a['condo'],'301');$unit402=$createExtraUnit($a['condo'],'402');$unit101=$createExtraUnit($a['condo2'],'101');
$personForm=$requestA('/erp/people/new');$personToken=$csrf($personForm['body']);$createPerson=$requestA('/erp/people',['_token'=>$personToken,'entity_type'=>'person','full_name'=>'João Investidor '.$suffix,'document_type'=>'cpf','document_number'=>'12345678901','email'=>'joao@example.test','phone'=>'11999990000','create_link'=>'1','condominium_id'=>(string)$a['condo'],'unit_id'=>(string)$unitId,'role'=>'owner','starts_at'=>'2024-01-01']);$check($createPerson['status']===302&&str_contains($createPerson['location'],'/erp/people/'),'pessoa e vínculo inicial salvos por HTTP');preg_match('~/erp/people/(\d+)~',$createPerson['location'],$personMatch);$personId=(int)($personMatch[1]??0);$check($personId>0,'pessoa persistida com identificador');
$detail=$requestA('/erp/people/'.$personId);$linkToken=$csrf($detail['body']);foreach([[$a['condo'],$unit301],[$a['condo'],$unit402],[$a['condo2'],$unit101]] as [$condo,$extraUnit]){$added=$requestA('/erp/people/'.$personId.'/links',['_token'=>$linkToken,'condominium_id'=>(string)$condo,'unit_id'=>(string)$extraUnit,'role'=>'owner','starts_at'=>date('Y-m-d')]);$check($added['status']===302,'investidor ganha vínculo em outra unidade/condomínio');}
$secondPersonForm=$requestA('/erp/people/new');$secondPerson=$requestA('/erp/people',['_token'=>$csrf($secondPersonForm['body']),'entity_type'=>'person','full_name'=>'Maria Coproprietária '.$suffix,'create_link'=>'1','condominium_id'=>(string)$a['condo'],'unit_id'=>(string)$unitId,'role'=>'owner','starts_at'=>date('Y-m-d')]);$check($secondPerson['status']===302,'segunda coproprietária vinculada à unidade');$detail=$requestA('/erp/people/'.$personId);$unitDetail=$requestA('/erp/units/'.$unitId);$check($detail['status']===200&&str_contains($detail['body'],'João Investidor '.$suffix)&&str_contains($detail['body'],'Proprietário')&&str_contains($detail['body'],'101'),'detalhe de pessoa exibe múltiplos vínculos');$check($unitDetail['status']===200&&str_contains($unitDetail['body'],'João Investidor '.$suffix)&&str_contains($unitDetail['body'],'Maria Coproprietária '.$suffix),'detalhe da unidade exibe dois proprietários atuais');$unitList=$requestA('/erp/units');$check($unitList['status']===200&&preg_match('/(?:João Investidor|Maria Coproprietária) '.preg_quote($suffix,'/').' \+1/u',$unitList['body'])===1,'listagem resume múltiplos proprietários sem depender da ordem');
$linkStmt=$pdo->prepare('SELECT id FROM erp_person_links WHERE administrator_id=? AND person_id=?');$linkStmt->execute([$a['administrator'],$personId]);$linkId=(int)$linkStmt->fetchColumn();$closeToken=$csrf($detail['body']);$closed=$requestA('/erp/people/'.$personId.'/links/'.$linkId.'/close',['_token'=>$closeToken,'ends_at'=>date('Y-m-d')]);$check($closed['status']===302,'encerramento de vínculo POST redireciona');$history=$requestA('/erp/people/'.$personId);$check($history['status']===200&&str_contains($history['body'],'Histórico'),'vínculo encerrado permanece no histórico');
$csrfRejected=$requestA('/erp/units',['_token'=>'bad','condominium_id'=>(string)$a['condo'],'block'=>'','code'=>'csrf']);$check($csrfRejected['status']===302&&str_contains($csrfRejected['location'],'/erp/units/new'),'POST sem CSRF não cria unidade');
$counts=$pdo->prepare('SELECT COUNT(*) FROM erp_person_links WHERE administrator_id=? AND person_id=?');$counts->execute([$a['administrator'],$personId]);$linksBeforeCrossTenant=(int)$counts->fetchColumn();$crossCondo=$requestA('/erp/people/'.$personId.'/links',['_token'=>$csrf($history['body']),'condominium_id'=>(string)$b['condo'],'unit_id'=>'','role'=>'resident','starts_at'=>date('Y-m-d')]);$check($crossCondo['status']===302,'vínculo para condomínio de B é recusado sem exposição');$counts->execute([$a['administrator'],$personId]);$check((int)$counts->fetchColumn()===$linksBeforeCrossTenant,'POST recusado não adiciona vínculo cruzado');
$requestB=$makeClient((string)$cookieB);$loginB=$requestB('/login');$authB=$requestB('/login',['email'=>$b['email'],'password'=>$password,'_token'=>$csrf($loginB['body'])]);$check($authB['status']===302&&str_ends_with($authB['location'],'/day'),'autenticação B direciona para Meu Dia');
$check($requestB('/erp/people/'.$personId)['status']===404,'tenant B não acessa detalhe da pessoa A');$check($requestB('/erp/units/'.$unitId)['status']===404,'tenant B não acessa detalhe da unidade A');$bPeopleList=$requestB('/erp/people');$check($bPeopleList['status']===200&&!str_contains($bPeopleList['body'],'João Investidor '.$suffix),'tenant B não lista nem infere pessoa exclusiva de A');$bPersonForm=$requestB('/erp/people/new');$bCreated=$requestB('/erp/people',['_token'=>$csrf($bPersonForm['body']),'entity_type'=>'person','full_name'=>'Pessoa B '.$suffix]);preg_match('~/erp/people/(\d+)~',$bCreated['location'],$bPersonMatch);$bPersonId=(int)($bPersonMatch[1]??0);$bDetail=$requestB('/erp/people/'.$bPersonId);$bPost=$requestB('/erp/people/'.$bPersonId.'/links',['_token'=>$csrf($bDetail['body']),'condominium_id'=>(string)$b['condo'],'unit_id'=>(string)$unitId,'role'=>'owner','starts_at'=>date('Y-m-d')]);$check($bPost['status']===302,'tenant B não consegue criar vínculo usando unidade de A');
$counts->execute([$a['administrator'],$personId]);$check((int)$counts->fetchColumn()===$linksBeforeCrossTenant,'tentativa de B não altera registros de A');
$noErpRequest=$makeClient((string)$cookieNoErp);$noErpLogin=$noErpRequest('/login');$noErpAuth=$noErpRequest('/login',['email'=>$noErp['email'],'password'=>$password,'_token'=>$csrf($noErpLogin['body'])]);$check($noErpAuth['status']===302&&str_ends_with($noErpAuth['location'],'/day'),'tenant sem produto ERP não recebe autorização');$noErpPage=$noErpRequest('/erp/people');$check($noErpPage['status']===403,'tenant com papel ERP mas entitlement desligado recebe 403');
$noRoleEmail='erp-no-permission-'.$suffix.'@example.test';$pdo->prepare("INSERT INTO users(name,email,password,status,role) VALUES(?,?,?,'active','user')")->execute(['Atendente sem ERP',$noRoleEmail,password_hash($password,PASSWORD_DEFAULT)]);$noRoleUser=(int)$pdo->lastInsertId();$agentRole=$pdo->prepare("SELECT id FROM platform_roles WHERE tenant_id=? AND slug='agent'");$agentRole->execute([$a['tenant']]);$pdo->prepare("INSERT INTO talk_tenant_users(tenant_id,user_id,role,role_id,status,is_default) VALUES(?,?,'agent',?,'active',0)")->execute([$a['tenant'],$noRoleUser,(int)$agentRole->fetchColumn()]);$cookieNoPermission=tempnam(sys_get_temp_dir(),'moves-people-nopermission-');$noPermissionRequest=$makeClient((string)$cookieNoPermission);$noPermissionLogin=$noPermissionRequest('/login');$noPermissionAuth=$noPermissionRequest('/login',['email'=>$noRoleEmail,'password'=>$password,'_token'=>$csrf($noPermissionLogin['body'])]);$check($noPermissionAuth['status']===302,'usuário sem erp.access pode autenticar');$noPermissionPage=$noPermissionRequest('/erp/people');$check($noPermissionPage['status']===302&&str_ends_with($noPermissionPage['location'],'/day'),'usuário sem erp.access é barrado pelo middleware de permissão');
$asset=$requestA('/themes/admin/css/erp.css');$check($asset['status']===200,'asset CSS ERP responde HTTP 200');
@unlink((string)$cookieA);@unlink((string)$cookieB);@unlink((string)$cookieNoErp);@unlink((string)$cookieNoPermission);echo "OK: $checkCount verificações HTTP ERP Pessoas/Unidades.\n";
