<?php

declare(strict_types=1);

require dirname(__DIR__).'/vendor/autoload.php';

use Moves\Boot\Connection;
use Moves\Boot\Environment;
use Moves\Core\Config;
use Moves\Modules\Erp\Suppliers\SupplierCategoryRepository;
use Moves\Services\Platform\CompanyService;
use Moves\Services\Platform\CondominiumService;

Environment::load(dirname(__DIR__));$base=rtrim((string)Config::get('APP_URL',''),'/');$database=(string)Config::get('DB_DATABASE','');$host=(string)parse_url($base,PHP_URL_HOST);
if(Config::environment()!=='testing'||!preg_match('/^moves_codex_erp_people_[a-zA-Z0-9_]+$/',$database)||!is_string($host)||!in_array(gethostbyname($host),['127.0.0.1','::1'],true))throw new RuntimeException('Directory E2E requer APP_ENV=testing, host local e DB_DATABASE moves_codex_erp_people_*.');
$pdo=Connection::getInstance();$suffix=bin2hex(random_bytes(5));$password='Moves-Directory-QA-2026!';
$cnpj=static function(string $base)use($suffix):string{$base=preg_replace('/\D+/','',$base)??'';if(strlen($base)!==12)throw new RuntimeException('Base CNPJ inválida.');$base=substr($base,0,2).substr(sprintf('%010u',crc32($suffix.$base)),-10);$digit=static function(string $value,array $weights):int{$sum=0;foreach($weights as $i=>$weight)$sum+=(int)$value[$i]*$weight;$mod=$sum%11;return $mod<2?0:11-$mod;};$first=$digit($base,[5,4,3,2,9,8,7,6,5,4,3,2]);$second=$digit($base.$first,[6,5,4,3,2,9,8,7,6,5,4,3,2]);return $base.$first.$second;};
$seed=static function(string $name,string $slug)use($pdo,$password,$suffix):array{$email=$slug.'-'.$suffix.'@example.test';$pdo->prepare("INSERT INTO users(name,email,password,status,role) VALUES(?,?,?,'active','user')")->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT)]);$user=(int)$pdo->lastInsertId();$tenantSlug=$slug.'-'.$suffix;$pdo->prepare("INSERT INTO talk_tenants(name,slug,status) VALUES(?,?,'active')")->execute([$name,$tenantSlug]);$tenant=(int)$pdo->lastInsertId();(new CompanyService($pdo))->ensureRoles($tenant);$role=$pdo->prepare("SELECT id FROM platform_roles WHERE tenant_id=? AND slug='owner'");$role->execute([$tenant]);$roleId=(int)$role->fetchColumn();$pdo->prepare("INSERT INTO talk_tenant_users(tenant_id,user_id,role,role_id,status,is_default) VALUES(?,?,'owner',?,'active',1)")->execute([$tenant,$user,$roleId]);$pdo->prepare("INSERT INTO platform_tenant_products(tenant_id,product,enabled) VALUES(?,'erp',1)")->execute([$tenant]);$pdo->prepare("INSERT INTO erp_administrators(tenant_id,legal_name,trade_name,tax_id,status) VALUES(?,?,?,?,'active')")->execute([$tenant,$name,$name,'TENANT-'.$tenant]);$administrator=(int)$pdo->lastInsertId();$grant=$pdo->prepare("INSERT INTO erp_scope_grants(user_id,capability,scope_type,scope_id) VALUES(?,?,'administrator',?)");foreach(['erp.cadastros.read','erp.cadastros.write'] as $capability)$grant->execute([$user,$capability,$administrator]);return ['email'=>$email,'user'=>$user,'tenant'=>$tenant,'administrator'=>$administrator];};
$a=$seed('Administradora Directory A','directory-a');$b=$seed('Administradora Directory B','directory-b');$categories=new SupplierCategoryRepository($pdo);$categories->ensureDefaults($a['administrator']);$categories->ensureDefaults($b['administrator']);$condoService=new CondominiumService($pdo);
$aCondo=$condoService->save($a['tenant'],['legal_name'=>'Residencial Alfa '.$suffix,'trade_name'=>'Alfa '.$suffix,'tax_id'=>$cnpj('200000000001'),'email'=>'alfa@example.test','phone'=>'1133334444','street'=>'Rua A','address_number'=>'10','district'=>'Centro','city'=>'São Paulo','state'=>'SP'],$a['user']);$aCondo2=$condoService->save($a['tenant'],['legal_name'=>'Residencial Beta '.$suffix,'tax_id'=>$cnpj('200000000002')],$a['user']);$bCondo=$condoService->save($b['tenant'],['legal_name'=>'Residencial B '.$suffix,'tax_id'=>$cnpj('300000000001')],$b['user']);
$pdo->prepare("INSERT INTO erp_people(administrator_id,entity_type,full_name,document_type,document_number,status,created_by_user_id) VALUES(?,'person',?,'cpf','52998224725','active',?)")->execute([$a['administrator'],'Pessoa PF existente '.$suffix,$a['user']]);$existingPerson=(int)$pdo->lastInsertId();
$block=$pdo->prepare("INSERT INTO erp_blocks(condominium_id,code,name) VALUES(?,'T-A','Torre A')");$block->execute([$aCondo]);$blockId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO erp_units(condominium_id,block_id,code,status) VALUES(?,?, '101','active'),(?,?, '102','active')")->execute([$aCondo,$blockId,$aCondo,$blockId]);
$managerName='Síndica QA '.$suffix;$pdo->prepare("INSERT INTO erp_people(administrator_id,entity_type,full_name,status,created_by_user_id) VALUES(?,'person',?,'active',?)")->execute([$a['administrator'],$managerName,$a['user']]);$managerId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO erp_person_links(administrator_id,person_id,condominium_id,role,starts_at,status,source,created_by_user_id) VALUES(?,?,?,'manager',CURRENT_DATE,'active','staff',?)")->execute([$a['administrator'],$managerId,$aCondo,$a['user']]);
$category=$pdo->prepare("SELECT id FROM erp_supplier_categories WHERE administrator_id=? AND slug='elevadores'");$category->execute([$a['administrator']]);$categoryA=(int)$category->fetchColumn();$category->execute([$b['administrator']]);$categoryB=(int)$category->fetchColumn();$checkCount=0;$check=static function(bool $ok,string $label)use(&$checkCount):void{if(!$ok)throw new RuntimeException('FAIL: '.$label);++$checkCount;echo 'PASS: '.$label.PHP_EOL;};
$csrf=static function(string $body):string{if(!preg_match('/name="_token"\s+value="([^"]+)"/',$body,$m))throw new RuntimeException('Token CSRF ausente.');return html_entity_decode($m[1],ENT_QUOTES|ENT_HTML5);};$cookieA=tempnam(sys_get_temp_dir(),'moves-directory-a-');$cookieB=tempnam(sys_get_temp_dir(),'moves-directory-b-');
$client=static function(string $cookie)use($base):Closure{$curl=curl_init();if(!$curl instanceof CurlHandle)throw new RuntimeException('cURL indisponível.');curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_COOKIEFILE=>$cookie,CURLOPT_COOKIEJAR=>$cookie,CURLOPT_PROXY=>'',CURLOPT_TIMEOUT=>15]);return static function(string $path,?array $data=null)use($curl,$base):array{curl_setopt($curl,CURLOPT_URL,$base.$path);if($data===null){curl_setopt($curl,CURLOPT_HTTPGET,true);curl_setopt($curl,CURLOPT_POST,false);}else{curl_setopt($curl,CURLOPT_POST,true);curl_setopt($curl,CURLOPT_POSTFIELDS,http_build_query($data));}$raw=curl_exec($curl);if(!is_string($raw))throw new RuntimeException('Falha HTTP: '.curl_error($curl));$size=(int)curl_getinfo($curl,CURLINFO_HEADER_SIZE);$headers=substr($raw,0,$size);preg_match('/^Location:\s*(.+)$/mi',$headers,$location);return ['status'=>(int)curl_getinfo($curl,CURLINFO_RESPONSE_CODE),'location'=>trim($location[1]??''),'body'=>substr($raw,$size)];};};
$requestA=$client((string)$cookieA);$login=$requestA('/login');$auth=$requestA('/login',['email'=>$a['email'],'password'=>$password,'_token'=>$csrf($login['body'])]);$check($auth['status']===302&&str_ends_with($auth['location'],'/day'),'login autorizado direciona para Meu Dia (HTTP '.$auth['status'].' '.$auth['location'].')');
$condos=$requestA('/erp/condominiums');$check($condos['status']===200&&str_contains($condos['body'],'Alfa '.$suffix)&&!str_contains($condos['body'],'Edifício Unique'),'lista real de condomínios sem demo');$search=$requestA('/erp/condominiums?q='.rawurlencode($cnpj('200000000001')));$check($search['status']===200&&str_contains($search['body'],'Alfa '.$suffix),'busca de condomínio por CNPJ');$detail=$requestA('/erp/condominiums/'.$aCondo);$check($detail['status']===200&&str_contains($detail['body'],$managerName)&&str_contains($detail['body'],'101')&&str_contains($detail['body'],'São Paulo'),'detalhe mostra endereço, unidades e síndico atual');$check($requestA('/erp/condominiums/'.$bCondo)['status']===404,'IDOR de condomínio de tenant B negado');
$condoForm=$requestA('/erp/condominiums/new');$createdCondo=$requestA('/erp/condominiums',['_token'=>$csrf($condoForm['body']),'legal_name'=>'Condomínio Criado '.$suffix,'tax_id'=>$cnpj('400000000001'),'street'=>'Rua Nova','city'=>'São Paulo','state'=>'SP','postal_code'=>'01000000']);preg_match('~/erp/condominiums/(\d+)~',$createdCondo['location'],$newCondoMatch);$newCondo=(int)($newCondoMatch[1]??0);$check($createdCondo['status']===302&&$newCondo>0&&$requestA('/erp/condominiums/'.$newCondo)['status']===200,'criação de condomínio persiste no cadastro canônico');$before=(int)$pdo->query('SELECT COUNT(*) FROM erp_condominiums WHERE administrator_id='.(int)$a['administrator'])->fetchColumn();$invalidCondo=$requestA('/erp/condominiums',['_token'=>$csrf($condoForm['body']),'legal_name'=>'CNPJ inválido '.$suffix,'tax_id'=>'11222333000182']);$after=(int)$pdo->query('SELECT COUNT(*) FROM erp_condominiums WHERE administrator_id='.(int)$a['administrator'])->fetchColumn();$check($invalidCondo['status']===302&&$before===$after,'CNPJ inválido não cria condomínio');$badCsrf=$requestA('/erp/condominiums',['_token'=>'invalid','legal_name'=>'CSRF '.$suffix,'tax_id'=>$cnpj('400000000002')]);$check($badCsrf['status']===302&&(int)$pdo->query('SELECT COUNT(*) FROM erp_condominiums WHERE administrator_id='.(int)$a['administrator'])->fetchColumn()===$after,'CSRF inválido bloqueia criação de condomínio');
$suppliers=$requestA('/erp/suppliers');$check($suppliers['status']===200&&str_contains($suppliers['body'],'Nenhum fornecedor encontrado')&&!str_contains($suppliers['body'],'Fornecedor demonstrativo'),'lista real de fornecedores sem demo');
$supplierForm=$requestA('/erp/suppliers/new');$check($supplierForm['status']===200&&str_contains($supplierForm['body'],'Pessoa física')&&str_contains($supplierForm['body'],'Pessoa jurídica'),'formulário aceita PF e PJ');
$category->execute([$a['administrator']]);$categoryA=(int)$category->fetchColumn();$category->execute([$b['administrator']]);$categoryB=(int)$category->fetchColumn();$personDoc=$cnpj('500000000001');
$supplierRowsBefore=(int)$pdo->query('SELECT COUNT(*) FROM erp_suppliers WHERE administrator_id='.(int)$a['administrator'])->fetchColumn();$invalidSupplierCsrf=$requestA('/erp/suppliers',['_token'=>'invalid','entity_type'=>'organization','full_name'=>'CSRF fornecedor '.$suffix,'document_type'=>'cnpj','document_number'=>$personDoc,'category_id'=>(string)$categoryA]);$check($invalidSupplierCsrf['status']===302&&(int)$pdo->query('SELECT COUNT(*) FROM erp_suppliers WHERE administrator_id='.(int)$a['administrator'])->fetchColumn()===$supplierRowsBefore,'CSRF inválido bloqueia criação de fornecedor');
$createdSupplier=$requestA('/erp/suppliers',['_token'=>$csrf($supplierForm['body']),'entity_type'=>'organization','full_name'=>'Elevadores XYZ '.$suffix,'trade_name'=>'XYZ','document_type'=>'cnpj','document_number'=>$personDoc,'email'=>'xyz@example.test','phone'=>'11900001111','category_id'=>(string)$categoryA,'condominium_ids'=>[(string)$aCondo,(string)$aCondo2],'starts_at'=>'2026-01-01']);preg_match('~/erp/suppliers/(\d+)~',$createdSupplier['location'],$supplierMatch);$supplierId=(int)($supplierMatch[1]??0);$check($createdSupplier['status']===302&&$supplierId>0,'fornecedor PJ persistido e associado a dois condomínios');
$supplierDetail=$requestA('/erp/suppliers/'.$supplierId);$check($supplierDetail['status']===200&&str_contains($supplierDetail['body'],'Elevadores XYZ '.$suffix)&&str_contains($supplierDetail['body'],'Alfa '.$suffix)&&str_contains($supplierDetail['body'],'Beta '.$suffix),'detalhe do fornecedor mostra vínculos N:N');$list=$requestA('/erp/suppliers');$check($list['status']===200&&str_contains($list['body'],'CNPJ')&&str_contains($list['body'],'Elevadores'),'lista exibe documento e categoria');
$duplicate=$requestA('/erp/suppliers',['_token'=>$csrf($supplierForm['body']),'entity_type'=>'organization','full_name'=>'Duplicado '.$suffix,'document_type'=>'cnpj','document_number'=>$personDoc,'category_id'=>(string)$categoryA]);$supplierCount=(int)$pdo->query('SELECT COUNT(*) FROM erp_suppliers WHERE administrator_id='.(int)$a['administrator'])->fetchColumn();$check($duplicate['status']===302&&$supplierCount===1,'documento duplicado reutiliza a pessoa e não duplica fornecedor');
$existingSupplier=$requestA('/erp/suppliers',['_token'=>$csrf($supplierForm['body']),'existing_person_id'=>(string)$existingPerson,'category_id'=>(string)$categoryA,'condominium_ids'=>[(string)$aCondo],'starts_at'=>'2026-01-01']);preg_match('~/erp/suppliers/(\d+)~',$existingSupplier['location'],$existingSupplierMatch);$existingSupplierId=(int)($existingSupplierMatch[1]??0);$check($existingSupplier['status']===302&&$existingSupplierId>0&&(int)$pdo->query('SELECT COUNT(*) FROM erp_people WHERE administrator_id='.(int)$a['administrator'])->fetchColumn()===3,'pessoa existente é qualificada como fornecedor sem duplicação');
$pfSupplier=$requestA('/erp/suppliers',['_token'=>$csrf($supplierForm['body']),'entity_type'=>'person','full_name'=>'Eletricista Autônomo '.$suffix,'document_type'=>'cpf','document_number'=>'11144477735','category_id'=>(string)$categoryA]);preg_match('~/erp/suppliers/(\d+)~',$pfSupplier['location'],$pfMatch);$pfId=(int)($pfMatch[1]??0);$check($pfSupplier['status']===302&&$pfId>0&&str_contains($requestA('/erp/suppliers/'.$pfId)['body'],'CPF'),'novo fornecedor PF criado');$add=$requestA('/erp/suppliers/'.$pfId.'/condominiums',['_token'=>$csrf($requestA('/erp/suppliers/'.$pfId)['body']),'condominium_id'=>(string)$newCondo,'starts_at'=>'2026-01-01']);$check($add['status']===302&&str_contains($requestA('/erp/suppliers/'.$pfId)['body'],'Condomínio Criado '.$suffix),'atendimento novo associado ao mesmo fornecedor');$closePage=$requestA('/erp/suppliers/'.$pfId);$linkQuery=$pdo->prepare('SELECT id FROM erp_supplier_condominiums WHERE administrator_id=? AND supplier_id=? AND condominium_id=? ORDER BY id DESC LIMIT 1');$linkQuery->execute([$a['administrator'],$pfId,$newCondo]);$linkId=(int)$linkQuery->fetchColumn();$closed=$requestA('/erp/suppliers/'.$pfId.'/condominiums/'.$linkId.'/close',['_token'=>$csrf($closePage['body']),'ends_at'=>date('Y-m-d')]);$check($closed['status']===302&&str_contains($requestA('/erp/suppliers/'.$pfId)['body'],'Histórico'),'atendimento encerrado mantém histórico');
$requestB=$client((string)$cookieB);$loginB=$requestB('/login');$authB=$requestB('/login',['email'=>$b['email'],'password'=>$password,'_token'=>$csrf($loginB['body'])]);$check($authB['status']===302&&str_ends_with($authB['location'],'/day'),'login tenant B direciona para Meu Dia');$check($requestB('/erp/condominiums')['status']===200&&!str_contains($requestB('/erp/condominiums')['body'],'Alfa '.$suffix),'tenant B não lista condomínio de A');$check($requestB('/erp/condominiums/'.$aCondo)['status']===404,'tenant B não abre condomínio de A por ID');$check($requestB('/erp/suppliers/'.$supplierId)['status']===404,'tenant B não abre fornecedor de A por ID');$check(!str_contains($requestB('/erp/suppliers')['body'],'Elevadores XYZ '.$suffix),'tenant B não lista fornecedor exclusivo de A');
$supplierFormB=$requestB('/erp/suppliers/new');$supplierB=$requestB('/erp/suppliers',['_token'=>$csrf($supplierFormB['body']),'entity_type'=>'person','full_name'=>'Prestador B '.$suffix,'document_type'=>'cpf','document_number'=>'52998224725','category_id'=>(string)$categoryB]);preg_match('~/erp/suppliers/(\d+)~',$supplierB['location'],$supplierBMatch);$supplierBId=(int)($supplierBMatch[1]??0);$check($supplierB['status']===302&&$supplierBId>0,'tenant B cadastra fornecedor próprio');$crossB=$requestB('/erp/suppliers/'.$supplierBId.'/condominiums',['_token'=>$csrf($requestB('/erp/suppliers/'.$supplierBId)['body']),'condominium_id'=>(string)$aCondo,'starts_at'=>'2026-01-01']);$check($crossB['status']===302&&(int)$pdo->query('SELECT COUNT(*) FROM erp_supplier_condominiums WHERE administrator_id='.(int)$b['administrator'].' AND supplier_id='.(int)$supplierBId)->fetchColumn()===0,'tenant B não associa fornecedor ao condomínio A');$crossA=$requestA('/erp/suppliers/'.$supplierId.'/condominiums',['_token'=>$csrf($requestA('/erp/suppliers/'.$supplierId)['body']),'condominium_id'=>(string)$bCondo,'starts_at'=>'2026-01-01']);$check($crossA['status']===302&&(int)$pdo->query('SELECT COUNT(*) FROM erp_supplier_condominiums WHERE administrator_id='.(int)$a['administrator'].' AND supplier_id='.(int)$supplierId.' AND condominium_id='.(int)$bCondo)->fetchColumn()===0,'tenant A não associa fornecedor ao condomínio B');$check($requestA('/erp/suppliers/'.$supplierBId)['status']===404,'tenant A não abre fornecedor de B');
$asset=$requestA('/themes/admin/css/erp.css');$check($asset['status']===200,'asset CSS ERP responde HTTP 200');@unlink((string)$cookieA);@unlink((string)$cookieB);echo "OK: $checkCount verificações HTTP ERP Condomínios/Fornecedores.\n";
