<?php
$this->layout('layouts/default', ['title'=>$title,'currentPage'=>'talk']);
?>
<section class="talk-page"><header class="talk-page-heading"><div><h1>Talk</h1><p>Atenda, organize e resolva. Tudo em um só lugar.</p></div><div class="talk-page-actions"><span class="talk-presence"><i></i> Online</span><button type="button" class="talk-new-button">＋ Novo atendimento</button></div></header><div class="talk-workspace" data-talk-workspace data-sync-url="/talk/sync<?= !empty($selectedConversation['id']) ? '?ticket_id='.(int)$selectedConversation['id'] : '' ?>" data-revision="0">
    <aside class="talk-list" aria-label="Conversas">
        <header class="talk-list-tabs"><button type="button" class="active" data-talk-filter="all" aria-pressed="true">Abertos <span data-talk-total-count><?= count($conversations) ?></span></button><button type="button" data-talk-filter="mine" aria-pressed="false">Meus <span data-talk-mine-count><?= (int)($mineCount ?? 0) ?></span></button><button type="button" data-talk-filter="resolved" aria-pressed="false">Resolvidos</button><span class="talk-sync-state" data-talk-sync-state role="status">Conectando…</span></header>
        <label class="talk-search"><span aria-hidden="true">⌕</span><span class="sr-only">Buscar conversas</span><input type="search" placeholder="Buscar atendimentos..." data-talk-search></label>
        <div class="talk-filters" aria-label="Filtros"><button type="button" data-talk-filter="queue" aria-pressed="false">Fila <span data-talk-queue-count><?= (int)($queueCount ?? 0) ?></span></button><select data-talk-filter-queue aria-label="Filtrar por fila"><option value="">Todas as filas</option><?php foreach(array_values(array_unique(array_filter(array_column($conversations,'queue_name')))) as $queueName): ?><option><?= htmlspecialchars((string)$queueName, ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select><select data-talk-filter-priority aria-label="Filtrar por prioridade"><option value="">Todas prioridades</option><option value="urgent">Urgente</option><option value="high">Alta</option><option value="normal">Normal</option><option value="low">Baixa</option></select></div>
        <div class="talk-list-body" aria-live="polite">
            <?php if (!$conversations): ?><div class="talk-empty"><strong>Nenhuma conversa disponível.</strong><p>Novas conversas aparecerão aqui quando o canal Talk estiver conectado.</p></div><?php else: ?>
                <?php foreach ($conversations as $conversation):
                    $status = (string)($conversation['status'] ?? '');
                    $isQueue = $status === 'queued';
                    $search = mb_strtolower(trim(implode(' ', [(string)($conversation['contact_name'] ?? ''), (string)($conversation['contact_phone'] ?? ''), (string)($conversation['protocol'] ?? ''), (string)($conversation['subject'] ?? '')])));
                ?>
                    <a class="talk-conversation<?= (int)($selectedConversation['id'] ?? 0)===(int)$conversation['id'] ? ' is-selected' : '' ?>" href="/talk/tickets/<?= (int)$conversation['id'] ?>" data-talk-conversation data-scope="<?= $isQueue ? 'queue' : 'mine' ?>" data-queue="<?= htmlspecialchars((string)($conversation['queue_name'] ?? ''), ENT_QUOTES, 'UTF-8') ?>" data-priority="<?= htmlspecialchars((string)($conversation['priority'] ?? 'normal'), ENT_QUOTES, 'UTF-8') ?>" data-search="<?= htmlspecialchars($search, ENT_QUOTES, 'UTF-8') ?>"<?= (int)($selectedConversation['id'] ?? 0)===(int)$conversation['id'] ? ' aria-current="true"' : '' ?>>
                        <span class="talk-conversation-main"><strong><?= htmlspecialchars((string)($conversation['contact_name'] ?? 'Contato'), ENT_QUOTES, 'UTF-8') ?></strong><small><?= htmlspecialchars((string)($conversation['subject'] ?? $conversation['protocol'] ?? ''), ENT_QUOTES, 'UTF-8') ?></small></span>
                        <span class="talk-conversation-meta"><small><?= $isQueue ? 'Fila' : htmlspecialchars((string)($conversation['assigned_name'] ?? 'Meu atendimento'), ENT_QUOTES, 'UTF-8') ?></small><small><?= htmlspecialchars((string)($conversation['priority'] ?? 'normal'), ENT_QUOTES, 'UTF-8') ?></small><?php if(!empty($conversation['sla_due_at'])): ?><small class="talk-sla<?= strtotime((string)$conversation['sla_due_at']) < time() ? ' is-late' : '' ?>">SLA <?= htmlspecialchars(date('H:i', strtotime((string)$conversation['sla_due_at'])), ENT_QUOTES, 'UTF-8') ?></small><?php endif; ?></span>
                    </a>
                <?php endforeach; ?>
            <?php endif; ?>
            <div class="talk-empty" data-talk-filter-empty hidden><strong>Nenhuma conversa encontrada.</strong><p>Ajuste a busca ou os filtros para ver outros atendimentos.</p></div>
        </div>
    </aside>
    <main class="talk-thread" aria-label="Conversa ativa">
        <?php if (!$selectedConversation): ?>
            <div class="talk-thread-empty"><span aria-hidden="true">◌</span><strong>Selecione uma conversa</strong><p>Escolha uma conversa na lista para visualizar mensagens e responder.</p></div>
        <?php else: ?>
            <header class="talk-thread-header"><div><strong><?= htmlspecialchars((string)$selectedConversation['contact_name'], ENT_QUOTES, 'UTF-8') ?></strong><small><?= htmlspecialchars((string)$selectedConversation['protocol'], ENT_QUOTES, 'UTF-8') ?></small></div><div class="talk-ticket-actions">
                <?php if (($selectedConversation['status'] ?? '') === 'queued'): ?><form method="post"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="action" value="claim"><button type="submit">Assumir</button></form><?php endif; ?>
                <?php if (!empty($canOperateTicket) && in_array(($selectedConversation['status'] ?? ''), ['assigned','open'], true)): ?><form method="post"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="action" value="return"><button type="submit">Retornar à fila</button></form><form method="post" data-confirm="Finalizar este atendimento?"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="action" value="close"><button type="submit">Finalizar</button></form><?php endif; ?>
                <?php if (!empty($canManageTalk) && ($selectedConversation['status'] ?? '') === 'closed'): ?><form method="post"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="action" value="reopen"><button type="submit">Reabrir</button></form><?php endif; ?>
            </div></header>
            <div class="talk-messages" aria-live="polite" data-talk-messages data-ticket-id="<?= (int)$selectedConversation['id'] ?>">
                <?php if (empty($selectedConversation['messages'])): ?><div class="talk-empty"><strong>Ainda não há mensagens.</strong><p>As mensagens desta conversa aparecerão aqui.</p></div><?php else: foreach ($selectedConversation['messages'] as $message): $messageMetadata=json_decode((string)($message['metadata'] ?? '{}'),true);if(!is_array($messageMetadata))$messageMetadata=[];$deliveryStatus=(string)($messageMetadata['delivery_status']??(($message['direction']??'')==='outbound'?'sent':''));$deliveryLabels=['sent'=>'Enviado','delivered'=>'Entregue','read'=>'Lido','failed'=>'Falha no envio']; ?><article class="talk-message <?= ($message['direction'] ?? '') === 'outbound' ? 'is-outbound' : 'is-inbound' ?><?= $deliveryStatus === 'failed' ? ' has-delivery-failed' : '' ?>" data-message-id="<?= (int)($message['id']??0) ?>" data-delivery-status="<?= htmlspecialchars($deliveryStatus,ENT_QUOTES,'UTF-8') ?>"><p><?= nl2br(htmlspecialchars((string)($message['body'] ?? ''), ENT_QUOTES, 'UTF-8')) ?></p><small><?= htmlspecialchars((string)($message['sender_name'] ?? ($messageMetadata['agent_name'] ?? (($message['direction'] ?? '') === 'outbound' ? 'Atendente' : $selectedConversation['contact_name'])), ENT_QUOTES, 'UTF-8') ?> · <?= htmlspecialchars((string)($message['sent_at'] ?? ''), ENT_QUOTES, 'UTF-8') ?><?= ($message['direction'] ?? '') === 'outbound' ? ' · '.htmlspecialchars((string)($deliveryLabels[$deliveryStatus]??$deliveryStatus), ENT_QUOTES, 'UTF-8') : '' ?></small><?php if($deliveryStatus==='failed'&&($message['direction']??'')==='outbound'&&!empty($canOperateTicket)): ?><form method="post" class="talk-message-retry"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="action" value="retry_message"><input type="hidden" name="message_id" value="<?= (int)($message['id']??0) ?>"><button type="submit">Reenviar</button></form><?php endif; ?></article><?php endforeach; endif; ?>
            </div>
            <?php if (!empty($selectedConversation['attachments'])): ?><div class="talk-attachments" aria-label="Anexos"><?php foreach ($selectedConversation['attachments'] as $attachment): $attachmentUrl='/talk/attachments/'.(int)$attachment['id']; $attachmentMime=(string)($attachment['mime_type'] ?? ''); ?><article class="talk-attachment"><?php if (str_starts_with($attachmentMime, 'image/')): ?><a href="<?= $attachmentUrl ?>" target="_blank" rel="noopener"><img src="<?= $attachmentUrl ?>" alt="<?= htmlspecialchars((string)$attachment['original_name'], ENT_QUOTES, 'UTF-8') ?>" loading="lazy"></a><?php elseif (str_starts_with($attachmentMime, 'audio/')): ?><audio controls preload="metadata" src="<?= $attachmentUrl ?>">Seu navegador não suporta áudio.</audio><?php elseif (str_starts_with($attachmentMime, 'video/')): ?><video controls preload="metadata" src="<?= $attachmentUrl ?>">Seu navegador não suporta vídeo.</video><?php endif; ?><a href="<?= $attachmentUrl ?>" target="_blank" rel="noopener"><?= htmlspecialchars((string)$attachment['original_name'], ENT_QUOTES, 'UTF-8') ?> <small><?= number_format(((int)$attachment['size_bytes']) / 1024, 0, ',', '.') ?> KB</small></a></article><?php endforeach; ?></div><?php endif; ?>
            <?php if (!empty($selectedConversation['action_status'])): ?><p class="talk-composer-feedback" role="status"><?= htmlspecialchars((string)$selectedConversation['action_status'], ENT_QUOTES, 'UTF-8') ?></p><?php endif; ?>
            <?php if (!empty($selectedConversation['outbound_error'])): ?><p class="talk-composer-feedback is-error" role="alert"><?= htmlspecialchars((string)$selectedConversation['outbound_error'], ENT_QUOTES, 'UTF-8') ?><?php if (!empty($selectedConversation['outbound_draft'])): ?> A mensagem foi preservada para tentar novamente.<?php endif; ?></p><?php elseif (!empty($selectedConversation['outbound_status'])): ?><p class="talk-composer-feedback" role="status">Mensagem enviada.</p><?php endif; ?>
            <?php if (!empty($canOperateTicket)): ?>
            <form class="talk-composer" method="post" data-talk-composer>
                <input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(), ENT_QUOTES, 'UTF-8') ?>">
                <input type="hidden" name="action" value="send">
                <label class="sr-only" for="talk-message-body">Mensagem</label>
                <textarea id="talk-message-body" name="body" rows="1" maxlength="4000" placeholder="Digite uma mensagem" required data-talk-composer-body><?= htmlspecialchars((string)($selectedConversation['outbound_draft'] ?? ''), ENT_QUOTES, 'UTF-8') ?></textarea>
                <button type="submit" data-talk-send>Enviar</button>
            </form>
            <form class="talk-attachment-form" method="post" enctype="multipart/form-data" data-talk-attachment-form>
                <input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(), ENT_QUOTES, 'UTF-8') ?>">
                <input type="hidden" name="action" value="attachment">
                <label><span class="sr-only">Selecionar anexo</span><input type="file" name="attachment" required accept=".jpg,.jpeg,.png,.webp,.pdf,.txt,.mp3,.ogg,.m4a,.mp4" data-talk-attachment></label>
                <button type="submit">Anexar</button>
                <small>Até 10 MB. Imagem, PDF, texto, áudio ou vídeo.</small>
            </form>
            <?php else: ?><p class="talk-composer-feedback" role="status">Assuma este atendimento para responder.</p><?php endif; ?>
        <?php endif; ?>
    </main>
    <aside class="talk-context" aria-label="Contexto do contato">
        <header><p class="customer-eyebrow">CONTEXTO</p><h2>Contato</h2></header>
        <?php if (!$selectedConversation): ?><div class="talk-empty"><strong>Nenhum contato selecionado.</strong><p>Dados do contato, condomínio, unidade, tags, chamados e notas aparecerão aqui.</p></div><?php else: ?><dl class="talk-contact-details"><div><dt>Contato</dt><dd><?= htmlspecialchars((string)$selectedConversation['contact_name'], ENT_QUOTES, 'UTF-8') ?></dd></div><div><dt>Telefone</dt><dd><?= htmlspecialchars((string)($selectedConversation['contact_phone'] ?? '—'), ENT_QUOTES, 'UTF-8') ?></dd></div><div><dt>Fila</dt><dd><?= htmlspecialchars((string)($selectedConversation['queue_name'] ?? '—'), ENT_QUOTES, 'UTF-8') ?></dd></div><div><dt>Prioridade</dt><dd><?= htmlspecialchars((string)($selectedConversation['priority'] ?? 'normal'), ENT_QUOTES, 'UTF-8') ?></dd></div><div><dt>Condomínio</dt><dd><?= !empty($selectedConversation['condominium_id']) ? '#'.(int)$selectedConversation['condominium_id'] : 'Não identificado' ?></dd></div></dl><?php if(!empty($canOperateTicket)): ?><details class="talk-context-section"><summary>Identificar condomínio</summary><form method="post"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="action" value="condominium"><label>ID do condomínio<input type="number" name="condominium_id" min="1" inputmode="numeric" value="<?= !empty($selectedConversation['condominium_id'])?(int)$selectedConversation['condominium_id']:'' ?>" placeholder="Ex.: 125"></label><small>O vínculo será aplicado ao contato e aos próximos chamados. O protocolo deste chamado não será alterado.</small><button type="submit">Salvar vínculo</button></form></details><?php endif; ?>
        <?php if (!empty($canOperateTicket)): ?>
        <details class="talk-context-section"><summary>Transferir atendimento</summary><form method="post"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="action" value="transfer"><label>Fila<select name="to_queue_id"><option value="">Manter fila atual</option><?php foreach (($selectedConversation['queues'] ?? []) as $queue): if (($queue['status'] ?? '') !== 'active') continue; ?><option value="<?= (int)$queue['id'] ?>"><?= htmlspecialchars((string)$queue['name'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label><label>Atendente<select name="to_user_id"><option value="">Somente para a fila</option><?php foreach (($selectedConversation['eligible_users'] ?? []) as $agent): ?><option value="<?= (int)$agent['id'] ?>"><?= htmlspecialchars((string)$agent['name'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label><label>Motivo<textarea name="reason" maxlength="500"></textarea></label><button type="submit">Transferir</button></form></details>
        <details class="talk-context-section"><summary>Nota interna</summary><form method="post"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="action" value="note"><label><span class="sr-only">Nota interna</span><textarea name="note" maxlength="2000" required placeholder="Adicionar nota para a equipe"></textarea></label><button type="submit">Adicionar nota</button></form></details>
        <?php endif; ?>
        <details class="talk-context-section" open><summary>Tags</summary><?php if (!empty($canOperateTicket)): ?><form method="post"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="action" value="tags"><div class="talk-tag-options"><?php $activeTags=array_map('intval',array_column($selectedConversation['tags'] ?? [],'id')); foreach(($selectedConversation['available_tags'] ?? []) as $tag): ?><label><input type="checkbox" name="tag_ids[]" value="<?= (int)$tag['id'] ?>"<?= in_array((int)$tag['id'],$activeTags,true)?' checked':'' ?>><?= htmlspecialchars((string)$tag['name'], ENT_QUOTES, 'UTF-8') ?></label><?php endforeach; ?></div><button type="submit">Salvar tags</button></form><?php else: ?><p><?php if(empty($selectedConversation['tags'])): ?>Sem tags.<?php else: ?><?= htmlspecialchars(implode(', ',array_column($selectedConversation['tags'],'name')), ENT_QUOTES, 'UTF-8') ?><?php endif; ?></p><?php endif; ?></details>
        <details class="talk-context-section"><summary>Histórico recente</summary><?php if(empty($selectedConversation['contact_history'])): ?><p>Nenhum chamado anterior visível.</p><?php else: foreach($selectedConversation['contact_history'] as $history): ?><a class="talk-history-item" href="/talk/tickets/<?= (int)$history['id'] ?>"><strong><?= htmlspecialchars((string)$history['protocol'], ENT_QUOTES, 'UTF-8') ?></strong><small><?= htmlspecialchars((string)$history['status'], ENT_QUOTES, 'UTF-8') ?> · <?= htmlspecialchars((string)$history['created_at'], ENT_QUOTES, 'UTF-8') ?></small></a><?php endforeach; endif; ?></details>
        <?php if(!empty($canManageTalk)): ?><details class="talk-context-section"><summary>Agente virtual</summary><form method="post"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="action" value="jack_settings"><label>Nome do agente<input name="jack_name" maxlength="60" value="<?= htmlspecialchars((string)($talkSettings['jack.name']??'Jack'),ENT_QUOTES,'UTF-8') ?>" required></label><small>O padrão é Jack. Cada administradora pode usar sua própria identidade.</small><button type="submit">Salvar nome</button></form></details>
        <details class="talk-context-section"><summary>Números do WhatsApp</summary><?php if(empty($channels)): ?><p>Nenhum número cadastrado nesta administradora.</p><?php else: foreach($channels as $channel): ?><article><strong><?= htmlspecialchars((string)$channel['name'],ENT_QUOTES,'UTF-8') ?></strong><p><?= htmlspecialchars((string)($channel['phone_number']??'Número não informado'),ENT_QUOTES,'UTF-8') ?> · <?= htmlspecialchars((string)$channel['status'],ENT_QUOTES,'UTF-8') ?><?= !empty($channel['queue_name'])?' · '.htmlspecialchars((string)$channel['queue_name'],ENT_QUOTES,'UTF-8'):'' ?></p><small>Phone Number ID: <?= htmlspecialchars((string)($channel['external_account_id']??'não informado'),ENT_QUOTES,'UTF-8') ?><?= !empty($channel['last_connected_at'])?' · validado em '.htmlspecialchars((string)$channel['last_connected_at'],ENT_QUOTES,'UTF-8'):'' ?></small><form method="post"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="action" value="channel_test"><input type="hidden" name="channel_id" value="<?= (int)$channel['id'] ?>"><button type="submit">Testar conexão<?= ($channel['status']??'')==='active'?' novamente':'' ?></button></form></article><?php endforeach; endif; ?><form method="post"><input type="hidden" name="_token" value="<?= htmlspecialchars(\Moves\Core\Csrf::token(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="action" value="channel_save"><label>Nome do número<input name="channel_name" maxlength="120" placeholder="Ex.: Atendimento" required></label><label>WhatsApp<input name="phone_number" maxlength="32" inputmode="tel" placeholder="+55 31 99999-9999" required></label><label>Phone Number ID da Meta<input name="external_account_id" maxlength="190" inputmode="numeric" autocomplete="off" placeholder="Ex.: 123456789012345" required></label><small>O token e o App Secret ficam somente no ambiente seguro do servidor e nunca são gravados neste formulário.</small><label>Fila<select name="channel_queue_id"><option value="">Sem fila padrão</option><?php foreach(($tenantQueues??[]) as $queue): if(($queue['status']??'')!=='active')continue; ?><option value="<?= (int)$queue['id'] ?>"><?= htmlspecialchars((string)$queue['name'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label><button type="submit">Salvar número</button></form></details><?php endif; ?>
        <section class="talk-context-section"><h3>Notas</h3><?php if (empty($selectedConversation['notes'])): ?><p>Nenhuma nota interna.</p><?php else: foreach ($selectedConversation['notes'] as $note): ?><article><p><?= nl2br(htmlspecialchars((string)$note['body'], ENT_QUOTES, 'UTF-8')) ?></p><small><?= htmlspecialchars((string)($note['user_name'] ?? 'Equipe'), ENT_QUOTES, 'UTF-8') ?> · <?= htmlspecialchars((string)($note['created_at'] ?? ''), ENT_QUOTES, 'UTF-8') ?></small></article><?php endforeach; endif; ?></section><?php endif; ?>
    </aside>
</div></section>
<dialog class="talk-confirm-dialog" data-talk-confirm-dialog aria-labelledby="talk-confirm-title"><form method="dialog"><h2 id="talk-confirm-title">Confirmar ação</h2><p data-talk-confirm-message>Deseja continuar?</p><div><button value="cancel">Cancelar</button><button value="confirm" class="is-danger">Confirmar</button></div></form></dialog>
