<?php declare(strict_types=1); $this->layout('layouts/default',['title'=>$title,'currentPage'=>'tags']); ?>
<script src="/themes/admin/js/cms-workspace.js?v=20260920" defer></script>
<section class="studio-page cms-workspace-page">
<header class="knowledge-header"><div><p class="studio-eyebrow">MOVES · CMS</p><h1>Tags</h1><p>Gerencie termos transversais usados pelos conteúdos do CMS.</p></div><div class="knowledge-header-actions"><button class="studio-btn primary" type="button" data-cms-modal-open="#cms-tag-modal"><?= studio_icon('add') ?> Nova tag</button></div></header>
<nav class="support-knowledge-tabs cms-workspace-tabs" aria-label="Organização do CMS"><a href="/studio/articles"><?= studio_icon('newspaper') ?> Artigos</a><a href="/studio/categories"><?= studio_icon('archive') ?> Categorias</a><a class="active" href="/studio/tags"><?= studio_icon('tag') ?> Tags</a><a href="/studio/media"><?= studio_icon('image') ?> Mídia</a><a href="/studio/trash"><?= studio_icon('trash') ?> Lixeira</a></nav>
<form class="studio-filter-bar" method="get"><label><span>Buscar</span><input type="search" name="q" value="<?= $this->e($q) ?>" placeholder="Nome ou slug"></label><button class="studio-btn" type="submit">Filtrar</button><a class="studio-btn" href="/studio/tags">Limpar</a></form>
<div class="knowledge-table-meta"><span><?= count($tags) ?> tag(s)</span><span>Classificação editorial</span></div>
<div class="studio-table-wrap"><table><thead><tr><th>Nome</th><th>Slug</th><th>Conteúdos</th><th>Ações</th></tr></thead><tbody><?php if($tags===[]):?><tr><td colspan="4"><div class="knowledge-empty"><?= studio_icon('tag') ?><strong>Nenhuma tag encontrada.</strong><span>Crie a primeira tag para classificar conteúdos.</span><button class="studio-btn primary" type="button" data-cms-modal-open="#cms-tag-modal"><?= studio_icon('add') ?> Nova tag</button></div></td></tr><?php endif;?><?php foreach($tags as $tag):?><tr><td><strong><?= $this->e($tag['name']) ?></strong></td><td>/<?= $this->e($tag['slug']) ?></td><td><span class="studio-status <?= (int)$tag['usage_count']>0?'studio-status-success':'' ?>"><?= (int)$tag['usage_count'] ?> em uso</span></td><td><button class="studio-icon-action" type="button" title="Editar" data-cms-modal-open="#cms-tag-modal" data-cms-edit="1" data-id="<?= (int)$tag['id'] ?>" data-name="<?= $this->e($tag['name']) ?>" data-modal-title="Editar tag"><?= studio_icon('pencil') ?></button> <form class="support-inline-form" method="post" data-confirm-submit="Excluir esta tag?"><?= $this->csrf() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$tag['id'] ?>"><button class="studio-icon-action danger" type="submit" title="<?= (int)$tag['usage_count']>0?'Tag em uso':'Excluir' ?>"<?= (int)$tag['usage_count']>0?' disabled':'' ?>><?= studio_icon('trash') ?></button></form></td></tr><?php endforeach;?></tbody></table></div>
<dialog class="moves-modal" id="cms-tag-modal"><form method="post"><?= $this->csrf() ?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="0"><h2 data-modal-title>Nova tag</h2><p>Cadastre ou edite a tag sem sair da listagem.</p><label class="studio-field"><span>Nome</span><input name="name" minlength="2" maxlength="120" required placeholder="Ex.: estratégia"></label><footer class="moves-modal-actions"><button class="studio-btn" type="button" data-cms-modal-close>Cancelar</button><button class="studio-btn primary" type="submit"><?= studio_icon('save') ?> Salvar tag</button></footer></form></dialog>
</section>