<?php declare(strict_types=1); $this->layout('layouts/default',['title'=>$title,'currentPage'=>'categories']); $labels=['article_category'=>'Artigos','project_category'=>'Projetos','faq_category'=>'FAQ']; ?>
<script src="/themes/admin/js/cms-workspace.js?v=20260920" defer></script>
<section class="studio-page cms-workspace-page">
<header class="knowledge-header"><div><p class="studio-eyebrow">MOVES · CMS</p><h1>Categorias</h1><p>Organize artigos, projetos e perguntas usando a mesma estrutura editorial do Moves.</p></div><div class="knowledge-header-actions"><button class="studio-btn primary" type="button" data-cms-modal-open="#cms-category-modal"><?= studio_icon('add') ?> Nova categoria</button></div></header>
<nav class="support-knowledge-tabs cms-workspace-tabs" aria-label="Organização do CMS"><a href="/studio/articles"><?= studio_icon('newspaper') ?> Artigos</a><a class="active" href="/studio/categories"><?= studio_icon('archive') ?> Categorias</a><a href="/studio/tags"><?= studio_icon('tag') ?> Tags</a><a href="/studio/media"><?= studio_icon('image') ?> Mídia</a><a href="/studio/trash"><?= studio_icon('trash') ?> Lixeira</a></nav>
<form class="studio-filter-bar" method="get"><label><span>Buscar</span><input type="search" name="q" value="<?= $this->e($q) ?>" placeholder="Nome ou slug"></label><label><span>Tipo</span><select name="type"><option value="">Todos</option><?php foreach($labels as $value=>$label):?><option value="<?= $value ?>"<?= $type===$value?' selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label><button class="studio-btn" type="submit">Filtrar</button><a class="studio-btn" href="/studio/categories">Limpar</a></form>
<div class="knowledge-table-meta"><span><?= count($categories) ?> categoria(s)</span><span>Organização editorial</span></div>
<div class="studio-table-wrap"><table><thead><tr><th>Categoria</th><th>Tipo</th><th>Conteúdos</th><th>Ações</th></tr></thead><tbody><?php if($categories===[]):?><tr><td colspan="4"><div class="knowledge-empty"><?= studio_icon('archive') ?><strong>Nenhuma categoria encontrada.</strong><span>Crie a primeira categoria para organizar o conteúdo.</span><button class="studio-btn primary" type="button" data-cms-modal-open="#cms-category-modal"><?= studio_icon('add') ?> Nova categoria</button></div></td></tr><?php endif;?><?php foreach($categories as $category):?><tr><td><strong><?= $this->e($category['name']) ?></strong><small>/<?= $this->e($category['slug']) ?></small></td><td><?= $this->e($labels[$category['type']]??$category['type']) ?></td><td><span class="studio-status <?= (int)$category['usage_count']>0?'studio-status-success':'' ?>"><?= (int)$category['usage_count'] ?> em uso</span></td><td><button class="studio-icon-action" type="button" title="Editar" aria-label="Editar categoria" data-cms-modal-open="#cms-category-modal" data-cms-edit="1" data-id="<?= (int)$category['id'] ?>" data-name="<?= $this->e($category['name']) ?>" data-type="<?= $this->e($category['type']) ?>" data-modal-title="Editar categoria"><?= studio_icon('pencil') ?></button> <form class="support-inline-form" method="post" data-confirm-submit="Excluir esta categoria?"><?= $this->csrf() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$category['id'] ?>"><button class="studio-icon-action danger" type="submit" title="<?= (int)$category['usage_count']>0?'Categoria em uso':'Excluir' ?>"<?= (int)$category['usage_count']>0?' disabled':'' ?>><?= studio_icon('trash') ?></button></form></td></tr><?php endforeach;?></tbody></table></div>
<dialog class="moves-modal" id="cms-category-modal"><form method="post"><?= $this->csrf() ?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="0"><h2 data-modal-title>Nova categoria</h2><p>Cadastre a categoria sem sair da página.</p><label class="studio-field"><span>Nome</span><input name="name" minlength="2" maxlength="120" required placeholder="Ex.: Tutoriais"></label><label class="studio-field"><span>Usar em</span><select name="type" required><?php foreach($labels as $value=>$label):?><option value="<?= $value ?>"><?= $label ?></option><?php endforeach;?></select></label><footer class="moves-modal-actions"><button class="studio-btn" type="button" data-cms-modal-close>Cancelar</button><button class="studio-btn primary" type="submit"><?= studio_icon('save') ?> Salvar categoria</button></footer></form></dialog>
</section>