<?php declare(strict_types=1); $this->layout('layouts/default',['title'=>$title,'currentPage'=>'menus']); ?>
<section class="studio-page cms-management-page">
<header class="studio-page-heading"><div><p class="studio-eyebrow">NAVEGAÇÃO</p><h2>Menus</h2><p>Crie navegação com páginas internas ou URLs externas, ordem e hierarquia.</p></div></header>
<div class="studio-management-grid">
<aside class="studio-panel"><h3><?= $selectedMenu?'Editar menu':'Novo menu' ?></h3>
<form method="post"><?= $this->csrf() ?><input type="hidden" name="action" value="save_menu"><?php if($selectedMenu):?><input type="hidden" name="id" value="<?= (int)$selectedMenu['id'] ?>"><?php endif;?><div class="studio-field"><label>Nome</label><input name="name" required maxlength="120" value="<?= $this->e($selectedMenu['name']??'') ?>"></div><div class="studio-field"><label>Localização</label><input name="location" required maxlength="80" placeholder="principal" value="<?= $this->e($selectedMenu['location']??'') ?>"></div><div class="studio-field"><label>Status</label><select name="status"><option value="active"<?= ($selectedMenu['status']??'active')==='active'?' selected':'' ?>>Ativo</option><option value="inactive"<?= ($selectedMenu['status']??'')==='inactive'?' selected':'' ?>>Inativo</option></select></div><div class="studio-actions"><button class="studio-btn primary"><?= $selectedMenu?'Salvar menu':'Criar menu' ?></button><?php if($selectedMenu):?><a class="studio-btn" href="/studio/menus">Novo</a><?php endif;?></div></form>
<?php if($selectedMenu):?><form method="post" class="studio-delete-menu"><?= $this->csrf() ?><input type="hidden" name="action" value="delete_menu"><input type="hidden" name="id" value="<?= (int)$selectedMenu['id'] ?>"><button class="studio-btn danger" data-confirm="Excluir este menu? Seus itens precisam ser removidos primeiro.">Excluir menu</button></form><?php endif;?>
<nav class="studio-side-list"><?php foreach($menus as $menu):?><a class="<?= (int)$menu['id']===$menuId?'active':'' ?>" href="?menu=<?= (int)$menu['id'] ?>"><strong><?= $this->e($menu['name']) ?></strong><small><?= (int)$menu['item_count'] ?> item(ns)</small></a><?php endforeach;?></nav></aside>
<main class="studio-panel"><?php if(!$menuId):?><p class="studio-empty">Crie um menu para começar.</p><?php else:?><h3>Itens do menu</h3>
<form class="studio-menu-item-form" method="post"><?= $this->csrf() ?><input type="hidden" name="action" value="save_item"><input type="hidden" name="menu_id" value="<?= $menuId ?>"><?php $item=[]; include __DIR__.'/partials/menu-item-fields.php'; ?><button class="studio-btn primary">Adicionar item</button></form>
<div class="studio-menu-items"><?php if($items===[]):?><p class="studio-empty">Nenhum item neste menu.</p><?php endif;?><?php foreach($items as $item):?><details class="studio-menu-item"><summary><span><strong><?= $this->e($item['label']) ?></strong><small><?= $this->e($item['type']==='page'?($item['page_title']??'Página'):$item['url']) ?> · ordem <?= (int)$item['position'] ?></small></span><span class="studio-status <?= $item['status']==='active'?'studio-status-success':'' ?>"><?= $this->e($item['status']) ?></span></summary><form method="post"><?= $this->csrf() ?><input type="hidden" name="action" value="save_item"><input type="hidden" name="id" value="<?= (int)$item['id'] ?>"><input type="hidden" name="menu_id" value="<?= $menuId ?>"><?php include __DIR__.'/partials/menu-item-fields.php'; ?><div class="studio-actions"><button class="studio-btn primary">Salvar item</button></div></form><form method="post" class="studio-inline-form"><?= $this->csrf() ?><input type="hidden" name="action" value="delete_item"><input type="hidden" name="menu_id" value="<?= $menuId ?>"><input type="hidden" name="id" value="<?= (int)$item['id'] ?>"><button class="studio-btn danger" data-confirm="Remover item?">Remover item</button></form></details><?php endforeach;?></div><?php endif;?></main>
</div></section>
