<?php declare(strict_types=1); $this->layout('layouts/default',['title'=>$title,'currentPage'=>$module]); $meta=$edit['meta']??[]; $showEditor=$edit!==null||isset($_GET['create']); ?>
<section class="studio-page">
<header class="studio-page-heading"><div><p class="studio-eyebrow"><?= $module==='articles'?'BLOG':($module==='faq'?'ATENDIMENTO':'CONTEÚDO') ?></p><h2><?= $showEditor ? ($edit ? 'Editar ' : 'Novo ').$this->e(strtolower($singular)) : $this->e($title) ?></h2><p><?= $showEditor ? 'Crie conteúdo otimizado, organize a publicação e acompanhe o resultado no site.' : 'Gerencie publicação, mídia, SEO e ordenação em um fluxo seguro.' ?></p></div><a class="studio-button<?= $showEditor?' secondary':'' ?>" href="/admin/<?= $this->e($module) ?><?= $showEditor?'':'?create=1' ?>"><?= $showEditor?'Voltar':(($singular==='Pergunta'?'Nova':'Novo').' '.$this->e(strtolower($singular))) ?></a></header>
<?php if($module==='faq'&&!$showEditor):?><nav class="studio-section-tabs"><a class="active" href="#questions"><?= studio_icon('message-square') ?> Perguntas <b><?= count($records) ?></b></a><a href="?create=1"><?= studio_icon('circle-help') ?> Nova pergunta</a><a href="#categories"><?= studio_icon('archive') ?> Categorias <b><?= count($categories) ?></b></a></nav><?php endif;?>
<?php if(!$showEditor): ?>
<form class="studio-filter-bar" method="get"><label><span>Busca</span><input name="q" value="<?= $this->e($search) ?>" placeholder="Título ou slug"></label><label><span>Status</span><select name="status"><option value="">Todos</option><?php foreach(['draft'=>'Rascunho','published'=>'Publicado','archived'=>'Arquivado'] as $value=>$label):?><option value="<?= $value ?>"<?= $status===$value?' selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label><button>Filtrar</button><a href="/admin/<?= $this->e($module) ?>">Limpar</a></form>
<?php if(in_array($module,['articles','faq'],true)):?><details id="categories" class="studio-category-create"><summary>Gerenciar categorias</summary><form class="studio-inline-create" method="post"><?= $this->csrf() ?><input type="hidden" name="action" value="category"><label><span>Nova categoria</span><input name="category_name" minlength="2" maxlength="120" required placeholder="Ex.: <?= $module==='faq'?'Atendimento':'Tecnologia' ?>"></label><button>Criar categoria</button></form></details><?php endif;?>
<div id="questions" class="studio-table-wrap"><table><thead><tr><th><?= $module==='faq'?'Pergunta':'Título' ?></th><th>Slug</th><th>Status</th><th>Mídia</th><th>Ordem</th><th>Ações</th></tr></thead><tbody><?php if($records===[]):?><tr><td colspan="6" class="studio-empty">Nenhum registro encontrado.</td></tr><?php endif;?><?php foreach($records as $record):?><tr><td><strong><?= $this->e($record['title']) ?></strong></td><td>/<?= $this->e($record['slug']) ?></td><td><span class="studio-status"><?= $this->e($record['status']) ?></span></td><td><?= $record['media_id']?'Associada':'—' ?></td><td><?= $this->e((string)$record['position']) ?></td><td><a class="studio-icon-action" href="?edit=<?= $this->e((string)$record['id']) ?>" title="Editar"><?= studio_icon('pencil') ?></a></td></tr><?php endforeach;?></tbody></table></div>
<?php else: ?>
<form id="editor" class="studio-form-card studio-editor" method="post" action="/admin/<?= $this->e($module) ?>"><?= $this->csrf() ?><input type="hidden" name="id" value="<?= $this->e((string)($edit['id']??'')) ?>"><input type="hidden" name="action" value="save">
<div class="studio-editor-grid"><div class="studio-editor-main"><p class="studio-eyebrow"><?= $edit?'EDIÇÃO':'NOVO REGISTRO' ?></p><h2><?= $edit?'Editar':'Criar' ?> <?= $this->e(strtolower($singular)) ?></h2>
<div class="studio-field"><label for="title"><?= $module==='faq'?'Pergunta':'Título' ?></label><input id="title" name="title" required minlength="3" maxlength="180" value="<?= $this->e($edit['title']??'') ?>"></div><div class="studio-field"><label for="slug">Slug</label><input id="slug" name="slug" maxlength="190" value="<?= $this->e($edit['slug']??'') ?>" placeholder="Gerado a partir do título"></div><div class="studio-field"><label for="excerpt"><?= $module==='testimonials'?'Depoimento':'Resumo' ?></label><textarea id="excerpt" name="excerpt" maxlength="1000"><?= $this->e($edit['excerpt']??'') ?></textarea></div><?php if($module!=='testimonials'&&$module!=='highlights'):?><div class="studio-field"><label for="content"><?= $module==='faq'?'Resposta':'Conteúdo' ?></label><textarea id="content" name="content" maxlength="50000" rows="10"><?= $this->e($edit['content']??'') ?></textarea></div><?php endif;?>
<fieldset><legend>SEO</legend><div class="studio-field"><label for="seo_title">Título SEO</label><input id="seo_title" name="seo_title" maxlength="160" value="<?= $this->e($edit['seo_title']??'') ?>"></div><div class="studio-field"><label for="seo_description">Descrição SEO</label><textarea id="seo_description" name="seo_description" maxlength="320"><?= $this->e($edit['seo_description']??'') ?></textarea></div></fieldset></div>
<aside class="studio-editor-side"><div class="studio-field"><label for="media_id"><?= $module==='testimonials'?'Foto':'Imagem' ?></label><select id="media_id" name="media_id"><option value="">Sem imagem</option><?php foreach($media as $image):?><option value="<?= $this->e((string)$image['id']) ?>"<?= (int)($edit['media_id']??0)===(int)$image['id']?' selected':'' ?>><?= $this->e($image['name']) ?> (<?= (int)$image['width'] ?>×<?= (int)$image['height'] ?>)</option><?php endforeach;?></select><small>Envie e recorte imagens na Biblioteca de Mídia.</small></div>
<?php if($module==='articles'):?><div class="studio-field"><label for="category_id">Categoria</label><select id="category_id" name="category_id" required><option value="">Selecione</option><?php foreach($categories as $category):?><option value="<?= (int)$category['id'] ?>"<?= (int)($edit['category_id']??0)===(int)$category['id']?' selected':'' ?>><?= $this->e($category['name']) ?></option><?php endforeach;?></select></div><div class="studio-field"><label for="video">Vídeo do YouTube</label><input id="video" name="video" maxlength="255" value="<?= $this->e($meta['video']??'') ?>"></div><?php endif;?>
<?php if($module==='faq'):?><div class="studio-field"><label for="category_id">Categoria</label><select id="category_id" name="category_id" required><option value="">Selecione</option><?php foreach($categories as $category):?><option value="<?= (int)$category['id'] ?>"<?= (int)($edit['category_id']??0)===(int)$category['id']?' selected':'' ?>><?= $this->e($category['name']) ?></option><?php endforeach;?></select></div><?php endif;?>
<?php if($module==='pages'):?><div class="studio-field"><label for="template">Template</label><select id="template" name="template"><?php foreach(['default'=>'Padrão','landing'=>'Landing page','wide'=>'Largura ampla'] as $value=>$label):?><option value="<?= $value ?>"<?= ($edit['template']??'default')===$value?' selected':'' ?>><?= $label ?></option><?php endforeach;?></select></div><?php endif;?>
<?php if($module==='highlights'):?><div class="studio-field"><label for="cta_label">Texto do CTA</label><input id="cta_label" name="cta_label" maxlength="80" value="<?= $this->e($meta['cta_label']??'') ?>"></div><div class="studio-field"><label for="cta_url">URL do CTA</label><input id="cta_url" name="cta_url" maxlength="500" value="<?= $this->e($meta['cta_url']??'') ?>"></div><div class="studio-field"><label for="alignment">Alinhamento</label><select id="alignment" name="alignment"><?php foreach(['left'=>'Esquerda','center'=>'Centro','right'=>'Direita'] as $value=>$label):?><option value="<?= $value ?>"<?= ($meta['alignment']??'left')===$value?' selected':'' ?>><?= $label ?></option><?php endforeach;?></select></div><div class="studio-field"><label for="starts_at">Início</label><input id="starts_at" type="datetime-local" name="starts_at" value="<?= $this->e(isset($edit['starts_at'])?str_replace(' ','T',substr((string)$edit['starts_at'],0,16)):'') ?>"></div><div class="studio-field"><label for="ends_at">Fim</label><input id="ends_at" type="datetime-local" name="ends_at" value="<?= $this->e(isset($edit['ends_at'])?str_replace(' ','T',substr((string)$edit['ends_at'],0,16)):'') ?>"></div><?php endif;?>
<?php if($module==='testimonials'):?><div class="studio-field"><label for="company">Empresa</label><input id="company" name="company" maxlength="160" value="<?= $this->e($meta['company']??'') ?>"></div><div class="studio-field"><label for="job_title">Cargo</label><input id="job_title" name="job_title" maxlength="120" value="<?= $this->e($meta['job_title']??'') ?>"></div><?php endif;?>
<div class="studio-field"><label for="status">Status</label><select id="status" name="status"><?php foreach(['draft'=>'Rascunho','published'=>'Publicado','archived'=>'Arquivado'] as $value=>$label):?><option value="<?= $value ?>"<?= ($edit['status']??'draft')===$value?' selected':'' ?>><?= $label ?></option><?php endforeach;?></select></div><div class="studio-field"><label for="position">Ordem</label><input id="position" type="number" name="position" min="0" max="9999" value="<?= $this->e((string)($edit['position']??0)) ?>"></div></aside></div>
<div class="studio-editor-actions"><button>Salvar <?= $this->e(strtolower($singular)) ?></button><?php if($edit):?><button class="studio-danger-button" type="submit" name="action" value="delete" onclick="return confirm('Excluir este registro?')">Excluir</button><?php endif;?></div></form>
<?php endif; ?></section>
