<?php
declare(strict_types=1);
$this->layout('layouts/default',compact('title','productName','activeProduct','currentPage'));
?>
<main class="erp-page erp-page-people">
<?php $this->insert('components/erp-page-header',['heading'=>'Pessoas','description'=>'Cadastros e vínculos da administradora.','kicker'=>'MOVES · ERP','actionHref'=>'/erp/people/new','actionLabel'=>'Cadastrar pessoa']); ?>
<form method="get" action="/erp/people" class="erp-filter-bar" role="search"><label class="erp-search-field"><span class="sr-only">Buscar pessoa</span><i class="icon-search-outline" aria-hidden="true"></i><input type="search" name="q" value="<?= $this->e($filters['q']) ?>" placeholder="Nome, documento ou contato"></label><label><span class="sr-only">Condomínio</span><select name="condominium"><option value="">Todos os condomínios</option><?php foreach($condominiums as $condominium): ?><option value="<?= (int)$condominium['id'] ?>" <?= $filters['condominium']===(string)$condominium['id']?'selected':'' ?>><?= $this->e((string)($condominium['trade_name']?:$condominium['legal_name'])) ?></option><?php endforeach; ?></select></label><label><span class="sr-only">Vínculo</span><select name="role"><option value="">Todos os vínculos</option><?php foreach(['owner'=>'Proprietário','tenant'=>'Inquilino','resident'=>'Morador','manager'=>'Síndico','deputy_manager'=>'Subsíndico','council'=>'Conselheiro','proxy'=>'Procurador'] as $role=>$label): ?><option value="<?= $this->e($role) ?>" <?= $filters['role']===$role?'selected':'' ?>><?= $this->e($label) ?></option><?php endforeach; ?></select></label><label><span class="sr-only">Status</span><select name="status"><option value="">Todos os status</option><option value="active" <?= $filters['status']==='active'?'selected':'' ?>>Ativa</option><option value="inactive" <?= $filters['status']==='inactive'?'selected':'' ?>>Inativa</option></select></label><button class="erp-button" type="submit">Filtrar</button></form>
<section class="erp-panel erp-data-panel"><header class="erp-panel-head"><div><h2>Cadastro de pessoas</h2><p><?= count($people) ?> registro(s) · dados reais desta administradora</p></div></header>
<?php if($people===[]): ?><div class="erp-empty-state"><strong>Nenhuma pessoa encontrada</strong><p>Cadastre uma pessoa ou ajuste os filtros. Os dados desta tela vêm dos cadastros persistidos.</p><a class="erp-button erp-button-primary" href="/erp/people/new">Cadastrar pessoa</a></div>
<?php else: ?><div class="erp-table-wrap"><table><thead><tr><th>Pessoa</th><th>Documento</th><th>Vínculos ativos</th><th>Condomínios</th><th>Unidades</th><th>Contato</th><th>Status</th></tr></thead><tbody><?php foreach($people as $person): ?><tr><td><a class="erp-record-link" href="/erp/people/<?= (int)$person['id'] ?>"><strong><?= $this->e((string)$person['full_name']) ?></strong><?php if(!empty($person['trade_name'])): ?><small><?= $this->e((string)$person['trade_name']) ?></small><?php endif; ?></a></td><td><?= $this->e((string)$person['document_display']) ?></td><td><?= $this->e((string)$person['roles_label']) ?></td><td><?= $this->e((string)$person['condominiums_label']) ?></td><td><?= $this->e((string)$person['units_label']) ?></td><td><?= $this->e((string)$person['contact_display']) ?></td><td><span class="erp-status <?= $person['status']==='active'?'ativo':'' ?>"><?= $person['status']==='active'?'Ativa':'Inativa' ?></span></td></tr><?php endforeach; ?></tbody></table></div><footer class="erp-table-foot">Documentos são mascarados na listagem. A consulta detalhada é restrita aos usuários com acesso ao ERP da administradora.</footer><?php endif; ?></section>
</main>
