<?php
declare(strict_types=1);
$this->layout('layouts/default',compact('title','productName','activeProduct','currentPage'));
$person=$detail['person'];$roleLabels=['owner'=>'Proprietário','tenant'=>'Inquilino','resident'=>'Morador','manager'=>'Síndico','deputy_manager'=>'Subsíndico','council'=>'Conselheiro','proxy'=>'Procurador'];
?>
<main class="erp-page"><nav class="erp-breadcrumb"><a href="/erp/people">Pessoas</a><span aria-hidden="true">/</span><span><?= $this->e((string)$person['full_name']) ?></span></nav><?php $this->insert('components/erp-page-header',['heading'=>(string)$person['full_name'],'description'=>$person['entity_type']==='organization'?'Pessoa jurídica':'Pessoa física','kicker'=>'CADASTRO · ERP','actionHref'=>'/erp/people','actionLabel'=>'Voltar à lista']); ?>
<section class="erp-panel erp-person-summary"><div><span>Documento</span><strong><?= $this->e(($person['document_type']??'')==='cnpj'?'CNPJ':'CPF') ?> · <?= $this->e((string)($person['document_number']?:'Não informado')) ?></strong></div><div><span>Nome fantasia</span><strong><?= $this->e((string)($person['trade_name']?:'—')) ?></strong></div><div><span>E-mail</span><strong><?= $this->e((string)($person['email']?:'—')) ?></strong></div><div><span>Telefone</span><strong><?= $this->e((string)($person['phone']?:'—')) ?></strong></div></section>
<section class="erp-panel erp-data-panel erp-detail-section"><header class="erp-panel-head"><div><h2>Vínculos e histórico</h2><p><?= count($detail['links']) ?> vínculo(s) registrado(s); encerramentos preservam o histórico</p></div></header><?php if($detail['links']===[]): ?><div class="erp-empty-state"><strong>Sem vínculos cadastrados</strong><p>Adicione um vínculo abaixo.</p></div><?php else: ?><div class="erp-table-wrap"><table><thead><tr><th>Tipo</th><th>Condomínio</th><th>Unidade</th><th>Período</th><th>Situação</th><th>Ação</th></tr></thead><tbody><?php foreach($detail['links'] as $link): ?><tr><td><strong><?= $this->e($roleLabels[$link['role']]??(string)$link['role']) ?></strong></td><td><?= $this->e((string)($link['condominium_name']?:$link['condominium_legal_name'])) ?></td><td><?= $this->e(trim(($link['block_name']?((string)$link['block_name'].' · '):'').(string)($link['unit_code']??'Condomínio'))) ?></td><td><?= $this->e((string)$link['starts_at']) ?> → <?= $this->e((string)($link['ends_at']?:'Atual')) ?></td><td><span class="erp-status <?= (int)$link['is_current']===1?'ativo':'' ?>"><?= (int)$link['is_current']===1?'Ativo':'Histórico' ?></span></td><td><?php if((int)$link['is_current']===1): ?><form method="post" action="/erp/people/<?= (int)$person['id'] ?>/links/<?= (int)$link['id'] ?>/close" class="erp-inline-form"><?= $this->csrf() ?><label class="sr-only" for="end-<?= (int)$link['id'] ?>">Data de encerramento</label><input id="end-<?= (int)$link['id'] ?>" type="date" name="ends_at" required value="<?= date('Y-m-d') ?>"><button class="erp-button" type="submit">Encerrar</button></form><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<section class="erp-panel erp-detail-section"><header class="erp-panel-head"><div><h2>Adicionar vínculo</h2><p>Uma pessoa pode ter vários vínculos em condomínios e unidades diferentes.</p></div></header><form method="post" action="/erp/people/<?= (int)$person['id'] ?>/links" class="erp-form-panel"><?= $this->csrf() ?><div class="erp-form-grid"><label>Condomínio<select name="condominium_id" required><option value="">Selecione</option><?php foreach($condominiums as $condominium): ?><option value="<?= (int)$condominium['id'] ?>"><?= $this->e((string)($condominium['trade_name']?:$condominium['legal_name'])) ?></option><?php endforeach; ?></select></label><label>Unidade (opcional)<select name="unit_id"><option value="">Sem unidade específica</option><?php foreach($units as $unit): ?><option value="<?= (int)$unit['id'] ?>"><?= $this->e((string)($unit['condominium_name']?:$unit['condominium_legal_name']).' · '.($unit['block_name']?((string)$unit['block_name'].' · '):'').$unit['code']) ?></option><?php endforeach; ?></select></label><label>Tipo de vínculo<select name="role" required><?php foreach($roleLabels as $role=>$label): ?><option value="<?= $this->e($role) ?>"><?= $this->e($label) ?></option><?php endforeach; ?></select></label><label>Início<input type="date" name="starts_at" required value="<?= date('Y-m-d') ?>"></label><label>Encerramento (opcional)<input type="date" name="ends_at"></label></div><footer class="erp-form-actions"><button class="erp-button erp-button-primary" type="submit">Adicionar vínculo</button></footer></form></section></main>
