<?php declare(strict_types=1); $this->layout('layouts/default', compact('title','productName','activeProduct','currentPage')); $natureLabels=['asset'=>'Ativo','liability'=>'Passivo','equity'=>'Patrimônio líquido','revenue'=>'Receita','expense'=>'Despesa']; ?>
<main class="erp-page erp-page-chart-detail"><nav class="erp-breadcrumb"><a href="/erp/chart-of-accounts">Plano de Contas</a><span>/</span><span><?= $this->e((string)$plan['name']) ?></span></nav>
    <?php $this->insert('components/erp-page-header',['heading'=>(string)$plan['name'],'description'=>(string)($plan['trade_name']?:$plan['legal_name']),'kicker'=>'PLANO DE CONTAS · ERP','actionHref'=>'/erp/chart-of-accounts/'.$plan['id'].'/accounts/new','actionLabel'=>'Adicionar conta']); ?>
    <section class="erp-panel erp-chart-plan-summary"><div><span>Condomínio</span><strong><?= $this->e((string)($plan['trade_name']?:$plan['legal_name'])) ?></strong></div><div><span>Situação</span><strong><?= $plan['status']==='active'?'Ativo':'Inativo' ?></strong></div><div><span>Contas</span><strong><?= (int)$accountCount ?></strong></div><div><span>Hierarquia</span><strong>Até 8 níveis</strong></div></section>
    <form method="get" action="/erp/chart-of-accounts/<?= (int)$plan['id'] ?>" class="erp-filter-bar" role="search"><label class="erp-search-field"><span class="sr-only">Pesquisar por código ou nome</span><input type="search" name="q" value="<?= $this->e($filters['query']) ?>" placeholder="Código ou nome da conta"></label><label><span class="sr-only">Natureza</span><select name="nature"><option value="">Todas as naturezas</option><?php foreach($natureLabels as $value=>$label): ?><option value="<?= $value ?>" <?= $filters['nature']===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label><label><span class="sr-only">Situação</span><select name="status"><option value="">Todas as situações</option><option value="active" <?= $filters['status']==='active'?'selected':'' ?>>Ativa</option><option value="inactive" <?= $filters['status']==='inactive'?'selected':'' ?>>Inativa</option></select></label><button class="erp-button" type="submit">Filtrar</button><?php if($filters['query']!==''||$filters['nature']!==''||$filters['status']!==''): ?><a class="erp-filter-reset" href="/erp/chart-of-accounts/<?= (int)$plan['id'] ?>">Limpar</a><?php endif; ?></form>
    <section class="erp-panel erp-data-panel"><header class="erp-panel-head"><div><h2>Estrutura de contas</h2><p><?= count($accounts) ?> conta(s) nesta visualização</p></div></header>
        <?php if($accounts===[]): ?><div class="erp-empty-state"><strong>Nenhuma conta encontrada.</strong><p>Adicione uma conta sintética para iniciar a hierarquia ou ajuste os filtros.</p><a class="erp-button erp-button-primary" href="/erp/chart-of-accounts/<?= (int)$plan['id'] ?>/accounts/new">Adicionar conta</a></div>
        <?php else: ?><div class="erp-table-wrap erp-chart-tree-wrap"><table class="erp-responsive-directory-table erp-chart-tree"><thead><tr><th>Código e conta</th><th>Natureza</th><th>Tipo</th><th>Nível</th><th>Situação</th><th></th></tr></thead><tbody><?php foreach($accounts as $account): ?><tr><td data-label="Conta"><a class="erp-record-link erp-tree-node" style="--account-level:<?= max(0,(int)$account['level']-1) ?>" href="/erp/chart-of-accounts/<?= (int)$plan['id'] ?>/accounts/<?= (int)$account['id'] ?>"><strong><?= $this->e((string)$account['code']) ?></strong><span><?= $this->e((string)$account['name']) ?></span></a></td><td data-label="Natureza"><?= $this->e($natureLabels[(string)$account['nature']]??(string)$account['nature']) ?></td><td data-label="Tipo"><?= $account['account_type']==='synthetic'?'Sintética':'Analítica' ?></td><td data-label="Nível"><?= (int)$account['level'] ?></td><td data-label="Situação"><span class="erp-status <?= $account['status']==='active'?'ativo':'' ?>"><?= $account['status']==='active'?'Ativa':'Inativa' ?></span></td><td data-label="Ação"><a class="erp-record-link" href="/erp/chart-of-accounts/<?= (int)$plan['id'] ?>/accounts/<?= (int)$account['id'] ?>">Detalhe</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
        <footer class="erp-table-foot">Contas analíticas são folhas classificáveis futuramente. Lançamentos, razão e efeitos financeiros não fazem parte deste ciclo.</footer>
    </section>
</main>
