<?php declare(strict_types=1); $this->layout('layouts/default', compact('title','productName','activeProduct','currentPage')); ?>
<main class="erp-page erp-page-payables">
    <?php $this->insert('components/erp-page-header', ['heading'=>'Contas a pagar','description'=>'Obrigações registradas por fornecedor, condomínio e competência.','kicker'=>'MOVES · ERP','actionHref'=>'/erp/payables/new','actionLabel'=>'Registrar obrigação']); ?>
    <form method="get" action="/erp/payables" class="erp-filter-bar" role="search"><label class="erp-search-field"><span class="sr-only">Buscar obrigação</span><input type="search" name="q" maxlength="100" value="<?= $this->e($query) ?>" placeholder="Descrição, fornecedor ou condomínio"></label><button class="erp-button" type="submit">Buscar</button></form>
    <section class="erp-panel erp-data-panel"><header class="erp-panel-head"><div><h2>Obrigações registradas</h2><p><?= count($payables) ?> registro(s) · tenant atual</p></div></header>
        <?php if ($payables===[]): ?><div class="erp-empty-state"><strong>Nenhuma obrigação registrada.</strong><p>Informe valores e vencimentos previstos. Esta etapa não executa pagamentos nem atualiza saldos.</p><a class="erp-button erp-button-primary" href="/erp/payables/new">Registrar obrigação</a></div>
        <?php else: ?><div class="erp-table-wrap"><table class="erp-responsive-directory-table"><thead><tr><th>Descrição / fornecedor</th><th>Condomínio</th><th>Parcelas</th><th>Vencimentos</th><th class="numeric">Total</th><th></th></tr></thead><tbody><?php foreach ($payables as $row): ?><tr><td data-label="Descrição / fornecedor"><a class="erp-record-link" href="/erp/payables/<?= (int)$row['id'] ?>"><strong><?= $this->e((string)$row['description']) ?></strong><small><?= $this->e((string)$row['supplier_name']) ?></small></a></td><td data-label="Condomínio"><?= $this->e((string)$row['condominium_name']) ?></td><td data-label="Parcelas"><?= (int)$row['installment_count'] ?></td><td data-label="Vencimentos"><?= $this->e((string)$row['first_due_date']) ?><?= $row['last_due_date']!==$row['first_due_date']?' – '.$this->e((string)$row['last_due_date']):'' ?></td><td class="numeric" data-label="Total">R$ <?= $this->e(number_format((float)$row['total_amount'],2,',','.')) ?></td><td data-label="Ação"><a class="erp-record-link" href="/erp/payables/<?= (int)$row['id'] ?>">Visualizar</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
        <footer class="erp-table-foot">Registro previsto; aprovação, pagamento, baixa e saldo não estão disponíveis nesta etapa.</footer>
    </section>
</main>
