<?php declare(strict_types=1); $this->layout('layouts/default', compact('title','productName','activeProduct','currentPage')); ?>
<main class="erp-page erp-page-payable-form"><nav class="erp-breadcrumb"><a href="/erp/payables">Contas a pagar</a><span>/</span><span>Nova obrigação</span></nav>
    <?php $this->insert('components/erp-page-header',['heading'=>'Registrar obrigação','description'=>'Informe o fornecedor, a classificação contábil e cada parcela prevista.','kicker'=>'CONTAS A PAGAR · ERP']); ?>
    <?php $liabilities=array_values(array_filter($accounts,static fn(array $row):bool=>$row['nature']==='liability')); $expenses=array_values(array_filter($accounts,static fn(array $row):bool=>$row['nature']==='expense')); ?>
    <form method="post" action="/erp/payables" class="erp-panel erp-form-panel" data-erp-payable-form><?= $this->csrf() ?>
        <section class="erp-form-section"><h2>Origem e classificação</h2><p class="erp-form-help">O fornecedor precisa ter vínculo ativo com o condomínio. Valores e contas são informados explicitamente; nenhuma baixa é gerada.</p><div class="erp-form-grid">
            <label class="wide">Fornecedor · condomínio<select name="supplier_id" required data-payable-supplier><option value="">Selecione</option><?php foreach($suppliers as $supplier): ?><option value="<?= (int)$supplier['supplier_id'] ?>" data-condominium="<?= (int)$supplier['condominium_id'] ?>"><?= $this->e((string)($supplier['trade_name']?:$supplier['full_name']).' · '.$supplier['condominium_name']) ?></option><?php endforeach; ?></select><input type="hidden" name="condominium_id" value="" data-payable-condominium></label>
            <label class="wide">Descrição<input type="text" name="description" maxlength="200" required autocomplete="off" placeholder="Ex.: Manutenção de elevadores"></label>
            <label>Conta de obrigação (passivo)<select name="liability_account_id" required data-payable-account><option value="">Selecione</option><?php foreach($liabilities as $account): ?><option value="<?= (int)$account['account_id'] ?>" data-condominium="<?= (int)$account['condominium_id'] ?>"><?= $this->e((string)$account['code'].' · '.$account['name']) ?></option><?php endforeach; ?></select></label>
            <label>Conta de despesa<select name="expense_account_id" required data-payable-account><option value="">Selecione</option><?php foreach($expenses as $account): ?><option value="<?= (int)$account['account_id'] ?>" data-condominium="<?= (int)$account['condominium_id'] ?>"><?= $this->e((string)$account['code'].' · '.$account['name']) ?></option><?php endforeach; ?></select></label>
            <label>Total da obrigação (R$)<input type="number" name="total_amount" min="0.01" step="0.01" inputmode="decimal" required></label>
        </div></section>
        <section class="erp-form-section erp-form-subsection"><header class="erp-installment-heading"><div><h2>Parcelas</h2><p class="erp-form-help">Informe competência aberta, vencimento e valor de cada parcela. A soma precisa corresponder ao total.</p></div><button class="erp-button" type="button" data-add-payable-installment>Adicionar parcela</button></header>
            <div class="erp-installments" data-payable-installments><fieldset class="erp-installment-row"><legend>Parcela 1</legend><label>Competência<select name="installments[period_id][]" required data-payable-period><option value="">Selecione</option><?php foreach($periods as $period): ?><option value="<?= (int)$period['id'] ?>" data-condominium="<?= (int)$period['condominium_id'] ?>"><?= sprintf('%02d/%04d',(int)$period['period_month'],(int)$period['period_year']) ?></option><?php endforeach; ?></select></label><label>Vencimento<input type="date" name="installments[due_date][]" required></label><label>Valor (R$)<input type="number" name="installments[amount][]" min="0.01" step="0.01" inputmode="decimal" required></label><button class="erp-button erp-installment-remove" type="button" data-remove-payable-installment disabled>Remover</button></fieldset></div>
            <template data-payable-installment-template><fieldset class="erp-installment-row"><legend>Parcela</legend><label>Competência<select name="installments[period_id][]" required data-payable-period><option value="">Selecione</option><?php foreach($periods as $period): ?><option value="<?= (int)$period['id'] ?>" data-condominium="<?= (int)$period['condominium_id'] ?>"><?= sprintf('%02d/%04d',(int)$period['period_month'],(int)$period['period_year']) ?></option><?php endforeach; ?></select></label><label>Vencimento<input type="date" name="installments[due_date][]" required></label><label>Valor (R$)<input type="number" name="installments[amount][]" min="0.01" step="0.01" inputmode="decimal" required></label><button class="erp-button erp-installment-remove" type="button" data-remove-payable-installment>Remover</button></fieldset></template>
            <?php if($suppliers===[]||$liabilities===[]||$expenses===[]||$periods===[]): ?><p class="erp-inline-notice">É necessário ter fornecedor atendendo condomínio, plano com contas analíticas de passivo/despesa e competência aberta.</p><?php endif; ?>
        </section><footer class="erp-form-actions"><a class="erp-button" href="/erp/payables">Cancelar</a><button class="erp-button erp-button-primary" type="submit" <?= $suppliers===[]||$liabilities===[]||$expenses===[]||$periods===[]?'disabled':'' ?>>Salvar obrigação</button></footer>
    </form>
</main>
