<?php declare(strict_types=1); $this->layout('layouts/default', compact('title','productName','activeProduct','currentPage')); ?>
<main class="erp-page erp-page-receivable-form"><nav class="erp-breadcrumb"><a href="/erp/receivables">Contas a receber</a><span>/</span><span>Novo título</span></nav>
    <?php $this->insert('components/erp-page-header',['heading'=>'Registrar título a receber','description'=>'Informe o responsável, as contas de classificação e cada parcela prevista.','kicker'=>'CONTAS A RECEBER · ERP']); ?>
    <?php $assetAccounts=array_values(array_filter($accounts,static fn(array $row):bool=>$row['nature']==='asset')); $revenueAccounts=array_values(array_filter($accounts,static fn(array $row):bool=>$row['nature']==='revenue')); ?>
    <form method="post" action="/erp/receivables" class="erp-panel erp-form-panel" data-erp-receivable-form><?= $this->csrf() ?>
        <section class="erp-form-section"><h2>Origem</h2><p class="erp-form-help">Selecione um vínculo ativo de proprietário, inquilino ou morador. Condomínio e unidade são derivados desse vínculo no servidor.</p><div class="erp-form-grid">
            <label class="wide">Responsável e unidade<select name="person_link_id" required data-receivable-person><option value="">Selecione</option><?php foreach($links as $link): $condominium=(int)$link['condominium_id']; $unit=($link['block_name']?(string)$link['block_name'].' · ':'').(string)$link['unit_code']; ?><option value="<?= (int)$link['person_link_id'] ?>" data-condominium="<?= $condominium ?>"><?= $this->e((string)($link['trade_name']?:$link['full_name']).' · '.$link['condominium_trade_name'].' · '.$unit) ?></option><?php endforeach; ?></select></label>
            <label class="wide">Descrição<input type="text" name="description" minlength="1" maxlength="200" required autocomplete="off" placeholder="Ex.: Cota condominial — competência"></label>
            <label>Conta de recebíveis (ativo)<select name="receivable_account_id" required data-receivable-account><option value="">Selecione</option><?php foreach($assetAccounts as $account): ?><option value="<?= (int)$account['account_id'] ?>" data-condominium="<?= (int)$account['condominium_id'] ?>"><?= $this->e((string)$account['code'].' · '.$account['name']) ?></option><?php endforeach; ?></select></label>
            <label>Conta de receita<select name="revenue_account_id" required data-receivable-account><option value="">Selecione</option><?php foreach($revenueAccounts as $account): ?><option value="<?= (int)$account['account_id'] ?>" data-condominium="<?= (int)$account['condominium_id'] ?>"><?= $this->e((string)$account['code'].' · '.$account['name']) ?></option><?php endforeach; ?></select></label>
            <label>Total do título (R$)<input type="number" name="total_amount" min="0.01" step="0.01" inputmode="decimal" required></label>
        </div></section>
        <section class="erp-form-section erp-form-subsection"><header class="erp-installment-heading"><div><h2>Parcelas</h2><p class="erp-form-help">Informe valor, vencimento e competência aberta de cada parcela. A soma precisa corresponder ao total do título.</p></div><button class="erp-button" type="button" data-add-installment>Adicionar parcela</button></header>
            <div class="erp-installments" data-installments><?php $index=0; ?><fieldset class="erp-installment-row"><legend>Parcela 1</legend><label>Competência<select name="installments[period_id][]" required><?php foreach($periods as $period): ?><option value="<?= (int)$period['id'] ?>" data-condominium="<?= (int)$period['condominium_id'] ?>"><?= sprintf('%02d/%04d',(int)$period['period_month'],(int)$period['period_year']) ?></option><?php endforeach; ?></select></label><label>Vencimento<input type="date" name="installments[due_date][]" required></label><label>Valor (R$)<input type="number" name="installments[amount][]" min="0.01" step="0.01" inputmode="decimal" required></label><button class="erp-button erp-installment-remove" type="button" data-remove-installment aria-label="Remover parcela 1" disabled>Remover</button></fieldset></div>
            <template data-installment-template><fieldset class="erp-installment-row"><legend>Parcela</legend><label>Competência<select name="installments[period_id][]" required><?php foreach($periods as $period): ?><option value="<?= (int)$period['id'] ?>" data-condominium="<?= (int)$period['condominium_id'] ?>"><?= sprintf('%02d/%04d',(int)$period['period_month'],(int)$period['period_year']) ?></option><?php endforeach; ?></select></label><label>Vencimento<input type="date" name="installments[due_date][]" required></label><label>Valor (R$)<input type="number" name="installments[amount][]" min="0.01" step="0.01" inputmode="decimal" required></label><button class="erp-button erp-installment-remove" type="button" data-remove-installment>Remover</button></fieldset></template>
            <?php if($links===[]||$assetAccounts===[]||$revenueAccounts===[]||$periods===[]): ?><p class="erp-inline-notice">Para registrar o título, este tenant precisa de vínculos ativos com unidade, plano com contas analíticas de ativo e receita, e competências abertas.</p><?php endif; ?>
        </section><footer class="erp-form-actions"><a class="erp-button" href="/erp/receivables">Cancelar</a><button class="erp-button erp-button-primary" type="submit" <?= $links===[]||$assetAccounts===[]||$revenueAccounts===[]||$periods===[]?'disabled':'' ?>>Salvar título</button></footer>
    </form>
</main>
