<?php
declare(strict_types=1);
$isEdit=is_array($administrator);$id=$isEdit?(int)$administrator['tenant_id']:0;
$this->layout('layouts/default',['title'=>$title,'productName'=>'Master','activeProduct'=>'master','currentPage'=>'administrators']);
$v=static fn(string $key):string=>$isEdit?(string)($administrator[$key]??''):'';
?>
<header class="page-heading"><div><span class="kicker">MOVES MASTER</span><h1><?= $this->e($title) ?></h1><p><?= $isEdit?'Atualize dados empresariais e o estado de acesso.':'Crie a empresa e seu tenant canônico na plataforma.' ?></p></div><?php if($isEdit):?><a class="secondary-btn" href="/master/administrators/<?= $id ?>">Cancelar</a><?php else:?><a class="secondary-btn" href="/master/administrators">Cancelar</a><?php endif;?></header>
<form class="surface mst-form" method="post" action="<?= $isEdit?'/master/administrators/'.$id:'/master/administrators' ?>"><?= $this->csrf() ?>
<div class="mst-form-section"><div><h2>Dados empresariais</h2><p>Identificação oficial da administradora.</p></div><div class="mst-fields"><label>Razão social <input required maxlength="180" name="legal_name" value="<?= $this->e($v('legal_name')) ?>"></label><label>Nome de exibição <input maxlength="160" name="trade_name" value="<?= $this->e($v('trade_name')) ?>"></label><label>CNPJ / identificador fiscal <input required maxlength="20" name="tax_id" value="<?= $this->e($v('tax_id')) ?>"></label><?php if(!$isEdit):?><label>Status inicial <select name="status"><option value="active" selected>Ativa</option><option value="inactive">Inativa</option></select></label><?php else:?><div class="mst-readonly"><span>Status</span><strong><?= $this->e(['active'=>'Ativa','inactive'=>'Inativa','suspended'=>'Suspensa'][$v('status')]??$v('status')) ?></strong><small>Altere o lifecycle somente na página da administradora.</small></div><?php endif;?></div></div>
<?php if(!$isEdit):?><div class="mst-form-section"><div><h2>Identidade inicial</h2><p>Configuração visual inicial do tenant.</p></div><div class="mst-fields"><label>Cor principal <input type="color" name="primary_color" value="#6E00B3"></label><label>Cor secundária <input name="secondary_color" value="" placeholder="#FFFFFF" pattern="#[0-9A-Fa-f]{6}"></label></div></div><?php endif;?>
<div class="mst-form-section"><div><h2>Contato principal</h2><p>Referência administrativa para relacionamento Moves.</p></div><div class="mst-fields"><label>Nome <input maxlength="120" name="contact_name" value="<?= $this->e($v('contact_name')) ?>"></label><label>E-mail <input type="email" maxlength="190" name="contact_email" value="<?= $this->e($v('contact_email')) ?>"></label><label>Telefone <input maxlength="40" name="contact_phone" value="<?= $this->e($v('contact_phone')) ?>"></label></div></div>
<div class="mst-form-section"><div><h2>Observações</h2><p>Informação interna do Moves Master.</p></div><label class="mst-wide">Notas <textarea maxlength="1000" name="notes" rows="4"><?= $this->e($v('notes')) ?></textarea></label></div>
<footer class="mst-form-actions"><button class="primary-btn" type="submit"><i class="icon-checkmark-outline"></i><?= $isEdit?'Salvar alterações':'Criar administradora' ?></button></footer></form>