<?php
declare(strict_types=1);
$this->layout('layouts/default',['title'=>$title,'productName'=>'Master','activeProduct'=>'master','currentPage'=>'administrators']);
$label=['active'=>'Ativa','inactive'=>'Inativa','suspended'=>'Suspensa'];
?>
<header class="page-heading"><div><span class="kicker">MOVES MASTER</span><h1>Administradoras</h1><p>Empresas, acesso à plataforma e situação operacional.</p></div><a class="primary-btn" href="/master/administrators/create"><i class="icon-add-outline"></i>Nova administradora</a></header>
<form class="mst-filter surface" method="get" action="/master/administrators"><label><i class="icon-search-outline"></i><input type="search" name="q" value="<?= $this->e($q) ?>" placeholder="Buscar por nome, CNPJ ou identificador"></label><select name="status"><option value="">Todos os status</option><?php foreach($label as $key=>$text):?><option value="<?= $key ?>"<?= $status===$key?' selected':'' ?>><?= $text ?></option><?php endforeach;?></select><button class="secondary-btn" type="submit">Filtrar</button></form>
<section class="data-panel"><div class="panel-toolbar"><div><span class="kicker">CADASTRO CENTRAL</span><h3><?= (int)$data['total'] ?> administradoras</h3></div></div><div class="table-wrap"><table><thead><tr><th>Administradora</th><th>Fiscal</th><th>Status</th><th>Produtos</th><th>Usuários</th><th>Canais</th><th>Atualização</th><th></th></tr></thead><tbody>
<?php if(!$data['items']):?><tr><td colspan="8"><div class="mst-empty"><strong>Nenhuma administradora encontrada</strong><span>Ajuste os filtros ou crie um novo cadastro.</span></div></td></tr><?php endif;?>
<?php foreach($data['items'] as $item):?><tr><td><strong><?= $this->e((string)($item['trade_name']?:$item['legal_name'])) ?></strong><small><?= $this->e((string)$item['legal_name']) ?> · <?= $this->e((string)$item['slug']) ?></small></td><td><?= $this->e((string)$item['tax_id']) ?></td><td><span class="badge mst-status <?= $this->e((string)$item['status']) ?>"><?= $this->e($label[$item['status']]??$item['status']) ?></span></td><td><?= $this->e((string)($item['products']?:'—')) ?></td><td><?= (int)$item['users_count'] ?></td><td><?= (int)$item['channels_count'] ?></td><td><?= $this->e((string)$item['updated_at']) ?></td><td><a class="icon-btn" href="/master/administrators/<?= (int)$item['tenant_id'] ?>" aria-label="Abrir administradora"><i class="icon-chevron-forward"></i></a></td></tr><?php endforeach;?>
</tbody></table></div></section>
<?php if(($data['pages']??1)>1):?><nav class="mst-pagination" aria-label="Paginação"><?php for($page=1;$page<=$data['pages'];$page++):?><a class="<?= $page===$data['page']?'is-active':'' ?>" href="?<?= http_build_query(array_filter(['q'=>$q,'status'=>$status,'page'=>$page],static fn($v)=>$v!==''&&$v!==null)) ?>"><?= $page ?></a><?php endfor;?></nav><?php endif;?>