<?php
/** @var array<string,mixed> $company @var array<string,bool> $products @var list<array<string,mixed>> $members @var list<array<string,mixed>> $roles @var list<array<string,mixed>> $condominiums */
$this->layout('layouts/default', compact('title','activeProduct','productName','currentPage'));
?>
<section class="page studio-page"><header class="page-heading"><div><p class="kicker">MOVES PLATFORM</p><h1><?= $this->e($title) ?></h1><p>Administradora, acessos, produtos e estrutura condominial em um só lugar.</p></div></header>
<div class="content-grid" style="grid-template-columns:1fr 1fr">
<section class="surface"><h2>Administradora</h2><form method="post" action="/settings"><?= $this->csrf() ?><input type="hidden" name="action" value="company"><label>Nome<input name="name" required value="<?= $this->e((string)($company['name']??'')) ?>"></label><label>Razão social<input name="legal_name" required value="<?= $this->e((string)($company['legal_name']??'')) ?>"></label><label>CNPJ<input name="tax_id" type="text" inputmode="text" autocapitalize="characters" maxlength="18" value="<?= $this->e((string)($company['tax_id']??'')) ?>"></label><label>E-mail<input type="email" name="email" value="<?= $this->e((string)($company['email']??'')) ?>"></label><button class="primary-btn">Salvar administradora</button></form></section>
<section class="surface"><h2>Produtos</h2><form method="post" action="/settings"><?= $this->csrf() ?><input type="hidden" name="action" value="products"><?php foreach ($products as $product=>$enabled): ?><label><input type="checkbox" name="products[]" value="<?= $this->e($product) ?>" <?= $enabled?'checked':'' ?>> <?= $this->e(strtoupper($product)) ?></label><?php endforeach; ?><button class="primary-btn">Atualizar produtos</button></form></section>
<section class="surface"><h2>Equipe</h2><form method="post" action="/settings"><?= $this->csrf() ?><input type="hidden" name="action" value="member"><label>E-mail do usuário<input type="email" name="email" required></label><label>Papel<select name="role_id"><?php foreach($roles as $role): ?><option value="<?= (int)$role['id'] ?>"><?= $this->e((string)$role['name']) ?></option><?php endforeach; ?></select></label><button class="primary-btn">Vincular usuário</button></form><ul><?php foreach($members as $member): ?><li><?= $this->e((string)$member['name']) ?> · <?= $this->e((string)$member['role_name']) ?></li><?php endforeach; ?></ul></section>
<section class="surface"><h2>Condomínios</h2><form method="post" action="/settings"><?= $this->csrf() ?><input type="hidden" name="action" value="condominium"><label>Razão social<input name="legal_name" required></label><label>Nome fantasia<input name="trade_name"></label><label>CNPJ<input name="tax_id" type="text" inputmode="text" autocapitalize="characters" maxlength="18" required></label><button class="primary-btn">Cadastrar condomínio</button></form><ul><?php foreach($condominiums as $condominium): ?><li><?= $this->e((string)$condominium['legal_name']) ?> · <?= $this->e((string)$condominium['status']) ?></li><?php endforeach; ?></ul></section>
</div></section>
