<?php
declare(strict_types=1);
$this->layout('layouts/default', ['title' => $title, 'productName' => 'Suporte', 'activeProduct' => 'support', 'currentPage' => 'articles']);
$statusLabels = ['draft' => 'Rascunho', 'published' => 'Publicado', 'archived' => 'Arquivado'];
$statusTones = ['draft' => 'warning', 'published' => 'success', 'archived' => 'neutral'];
$productNames = [];
foreach ($products as $product) { $productNames[(int) $product->id] = (string) $product->name; }
$categoryNames = [];
foreach ($categories as $category) { $categoryNames[(int) $category->id] = (string) $category->name; }
$detailJson = json_encode($articleDetails ?? [], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
$listMode = $listMode ?? 'articles';
$isDrafts = $listMode === 'drafts';
$listPath = $isDrafts ? '/support/drafts' : '/support/articles';
$queryBase = array_filter([
    'q' => $search,
    'category' => $categoryId > 0 ? $categoryId : null,
    'product' => $productId > 0 ? $productId : null,
    'status' => !$isDrafts && $status !== '' ? $status : null,
], static fn ($value): bool => $value !== null && $value !== '');
$pageUrl = static fn (int $page): string => $listPath . '?' . http_build_query([...$queryBase, 'page' => $page]);
$pageNumbers = range(1, (int) $pagination['pages']);
if ($pagination['pages'] > 7) {
    $window = range(max(2, $pagination['page'] - 1), min($pagination['pages'] - 1, $pagination['page'] + 1));
    $pageNumbers = [1, ...($window[0] > 2 ? [null] : []), ...$window, ...((int) end($window) < $pagination['pages'] - 1 ? [null] : []), $pagination['pages']];
}
?>
<link rel="stylesheet" href="/themes/admin/css/support.css?v=20260919c">
<script src="/themes/admin/js/support-knowledge.js?v=20260919" defer></script>
<section class="studio-page support-knowledge-page support-articles-workspace" data-knowledge-page="articles">
    <header class="knowledge-header">
        <div><p class="studio-eyebrow">MOVES STUDIO · SUPORTE</p><h1>Base de conhecimento</h1><p><?= $isDrafts ? 'Rascunhos de conteúdo ainda não publicados.' : 'Crie e gerencie conteúdos para ajudar seus usuários.' ?></p></div>
        <div class="knowledge-header-actions"><button class="studio-btn" type="button" disabled title="Importação ainda não disponível"><i class="icon-cloud-upload-outline" aria-hidden="true"></i> Importar artigos</button><a class="studio-btn primary" href="/support/articles/create"><i class="icon-copy-outline" aria-hidden="true"></i> Novo artigo</a></div>
    </header>
    <nav class="support-knowledge-tabs" aria-label="Base de conhecimento"><a class="<?= !$isDrafts ? 'active' : '' ?>" href="/support/articles"><i class="icon-newspaper-outline" aria-hidden="true"></i> Artigos</a><a href="/support/categories"><i class="icon-archive-outline" aria-hidden="true"></i> Categorias</a><a href="/support/products"><i class="icon-briefcase-outline" aria-hidden="true"></i> Produtos</a><a href="/support/tags"><i class="icon-pricetag-outline" aria-hidden="true"></i> Tags</a><a href="/support/trash"><i class="icon-trash-outline" aria-hidden="true"></i> Lixeira</a></nav>
    <div class="knowledge-toolbar"><form class="knowledge-filters" method="get" action="<?= $listPath ?>"><label class="knowledge-search"><span class="sr-only">Buscar artigos</span><i class="icon-search-outline" aria-hidden="true"></i><input type="search" name="q" value="<?= $this->e((string) $search) ?>" placeholder="Buscar artigos..."></label><label><span class="sr-only">Categoria</span><select name="category"><option value="0">Todas as categorias</option><?php foreach ($categories as $category): ?><option value="<?= (int) $category->id ?>"<?= $categoryId === (int) $category->id ? ' selected' : '' ?>><?= $this->e((string) $category->name) ?></option><?php endforeach; ?></select></label><label><span class="sr-only">Produto</span><select name="product"><option value="0">Todos os produtos</option><?php foreach ($products as $product): ?><option value="<?= (int) $product->id ?>"<?= $productId === (int) $product->id ? ' selected' : '' ?>><?= $this->e((string) $product->name) ?></option><?php endforeach; ?></select></label><?php if (!$isDrafts): ?><label><span class="sr-only">Status</span><select name="status"><option value="">Todos os status</option><?php foreach ($statusLabels as $value => $label): ?><option value="<?= $value ?>"<?= $status === $value ? ' selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></label><?php endif; ?><button class="studio-btn" type="submit">Filtrar</button></form><div class="knowledge-view-toggle" aria-label="Visualização"><button class="is-active" type="button" aria-label="Visualização em lista"><i class="icon-document-text-outline" aria-hidden="true"></i></button><button type="button" disabled aria-label="Visualização em grade" title="Visualização em grade ainda não disponível"><i class="icon-grid-outline" aria-hidden="true"></i></button></div></div>
    <div class="knowledge-table-meta"><span><?= (int) $pagination['total'] ?> artigo(s)</span><span><?= $isDrafts ? 'Somente rascunhos' : 'Dados reais do Support' ?></span></div>
    <div class="studio-table-wrap knowledge-table-wrap"><table><thead><tr><th class="knowledge-check"><span class="sr-only">Selecionar</span></th><th>Artigo</th><th>Categoria</th><th>Produto</th><th>Status</th><th>Atualizado em</th><th class="knowledge-actions-cell">Ações</th></tr></thead><tbody><?php if ($articles === []): ?><tr><td colspan="7"><div class="knowledge-empty"><i class="icon-newspaper-outline" aria-hidden="true"></i><strong><?= $isDrafts ? 'Nenhum rascunho.' : 'Nenhum artigo encontrado.' ?></strong><span><?= $queryBase !== [] ? 'Nenhum artigo corresponde aos filtros selecionados.' : 'Crie o primeiro artigo da base.' ?></span><a class="studio-btn primary" href="/support/articles/create"><i class="icon-add-outline" aria-hidden="true"></i> Novo artigo</a></div></td></tr><?php endif; ?><?php foreach ($articles as $article): ?><?php $articleId = (int) $article->id; $articleStatus = (string) $article->status; ?><tr data-article-row data-article-id="<?= $articleId ?>"><td class="knowledge-check"><input type="checkbox" aria-label="Selecionar <?= $this->e((string) $article->title) ?>"></td><td><button class="knowledge-title-button" type="button" data-knowledge-open-drawer="<?= $articleId ?>"><strong><?= $this->e((string) $article->title) ?></strong><small><?= $this->e((string) ($article->excerpt ?? '')) ?></small></button></td><td><span class="knowledge-category-badge"><?= $this->e($categoryNames[(int) ($article->category_id ?? 0)] ?? 'Sem categoria') ?></span></td><td><?= $this->e($productNames[(int) ($article->product_id ?? 0)] ?? 'Sem produto') ?></td><td><span class="studio-status studio-status-<?= $statusTones[$articleStatus] ?? 'neutral' ?>"><?= $this->e($statusLabels[$articleStatus] ?? $articleStatus) ?></span></td><td><?= $this->e((string) ($article->updated_at ?? '—')) ?></td><td class="knowledge-actions-cell"><button class="knowledge-more" type="button" aria-label="Ações do artigo" data-knowledge-menu="<?= $articleId ?>"><i class="icon-ellipsis-horizontal-outline" aria-hidden="true"></i></button><div class="knowledge-context-menu" data-knowledge-menu-panel="<?= $articleId ?>"><a href="/support/articles/<?= $this->e(rawurlencode((string) $article->slug)) ?>/edit"><i class="icon-pencil-outline" aria-hidden="true"></i> Editar</a><button type="button" data-knowledge-trash="<?= $articleId ?>" data-article-title="<?= $this->e((string) $article->title) ?>"><i class="icon-trash-outline" aria-hidden="true"></i> Mover para a lixeira</button></div></td></tr><?php endforeach; ?></tbody></table></div>
    <footer class="knowledge-pagination"><span>Mostrando <?= (int) $pagination['from'] ?> a <?= (int) $pagination['to'] ?> de <?= (int) $pagination['total'] ?> artigos</span><span class="knowledge-page-numbers"><a class="<?= $pagination['page'] <= 1 ? 'is-disabled' : '' ?>" href="<?= $pagination['page'] > 1 ? $this->e($pageUrl($pagination['page'] - 1)) : '#' ?>" aria-label="Página anterior"><i class="icon-chevron-back-outline" aria-hidden="true"></i></a><?php foreach ($pageNumbers as $pageNumber): ?><?php if ($pageNumber === null): ?><span class="knowledge-page-gap">…</span><?php else: ?><a class="<?= $pageNumber === $pagination['page'] ? 'active' : '' ?>" href="<?= $this->e($pageUrl($pageNumber)) ?>"><?= $pageNumber ?></a><?php endif; ?><?php endforeach; ?><a class="<?= $pagination['page'] >= $pagination['pages'] ? 'is-disabled' : '' ?>" href="<?= $pagination['page'] < $pagination['pages'] ? $this->e($pageUrl($pagination['page'] + 1)) : '#' ?>" aria-label="Próxima página"><i class="icon-chevron-forward-outline" aria-hidden="true"></i></a></span></footer>
    <dialog class="support-modal knowledge-confirm-dialog" data-knowledge-trash-dialog aria-labelledby="trash-dialog-title"><form method="post" action="/support/articles/trash"><?= $this->csrf() ?><input type="hidden" name="id" value="0"><h2 id="trash-dialog-title">Mover artigo para a lixeira?</h2><p><strong data-trash-title></strong></p><p>O artigo deixará as listagens normais, mas poderá ser restaurado.</p><footer class="support-modal-actions"><button class="studio-btn" type="button" data-knowledge-cancel-trash>Cancelar</button><button class="studio-btn danger" type="submit"><i class="icon-trash-outline" aria-hidden="true"></i> Mover para a lixeira</button></footer></form></dialog>
    <aside class="knowledge-drawer" data-knowledge-drawer aria-hidden="true"><div class="knowledge-drawer-header"><div><span class="studio-eyebrow">DETALHES DO ARTIGO</span><h2 data-drawer-title>Artigo</h2></div><button class="knowledge-drawer-close" type="button" data-knowledge-close-drawer aria-label="Fechar painel"><i class="icon-close-outline" aria-hidden="true"></i></button></div><div class="knowledge-drawer-status" data-drawer-status></div><nav class="knowledge-drawer-tabs" role="tablist"><button class="active" type="button" data-drawer-tab="overview">Visão geral</button><button type="button" data-drawer-tab="content">Conteúdo</button><button type="button" data-drawer-tab="seo">SEO</button><button type="button" data-drawer-tab="history">Histórico</button></nav><div class="knowledge-drawer-body"><section data-drawer-panel="overview"><p class="knowledge-drawer-excerpt" data-drawer-excerpt></p><a class="studio-btn primary" data-drawer-edit href="#"><i class="icon-pencil-outline" aria-hidden="true"></i> Editar artigo</a><dl class="knowledge-facts"><div><dt>Categoria</dt><dd data-drawer-category>—</dd></div><div><dt>Produto</dt><dd data-drawer-product>—</dd></div><div><dt>Tags</dt><dd data-drawer-tags>—</dd></div><div><dt>Autor</dt><dd data-drawer-author>—</dd></div><div><dt>Criado em</dt><dd data-drawer-created>—</dd></div><div><dt>Atualizado em</dt><dd data-drawer-updated>—</dd></div><div><dt>Leitura</dt><dd data-drawer-reading>—</dd></div></dl></section><section class="is-hidden" data-drawer-panel="content"><div class="moves-content knowledge-drawer-content" data-drawer-content></div></section><section class="is-hidden" data-drawer-panel="seo"><dl class="knowledge-facts"><div><dt>Palavra-chave</dt><dd data-drawer-focus>—</dd></div><div><dt>Título SEO</dt><dd data-drawer-meta-title>—</dd></div><div><dt>Meta description</dt><dd data-drawer-meta-description>—</dd></div><div><dt>Canonical</dt><dd data-drawer-canonical>—</dd></div><div><dt>Indexação</dt><dd data-drawer-index>—</dd></div><div><dt>Follow</dt><dd data-drawer-follow>—</dd></div></dl></section><section class="is-hidden" data-drawer-panel="history"><p class="knowledge-note">As revisões registram título, resumo e conteúdo disponíveis no histórico. Não representam restauração completa do artigo.</p><div data-drawer-history></div></section></div></aside><div class="knowledge-drawer-backdrop" data-knowledge-close-drawer></div><script type="application/json" data-knowledge-article-data><?= $detailJson ?></script>
</section>
