<?php
declare(strict_types=1);
$this->layout('layouts/default', ['title' => $title, 'productName' => 'Suporte', 'activeProduct' => 'support', 'currentPage' => 'categories']);
$productNames = [];
foreach ($products as $product) { $productNames[(int) $product->id] = (string) $product->name; }
$categoryNames = [];
foreach ($allCategories as $category) { $categoryNames[(int) $category->id] = (string) $category->name; }
?>
<link rel="stylesheet" href="/themes/admin/css/support.css?v=20260918">
<script src="/themes/admin/js/support-knowledge.js?v=20260918" defer></script>
<section class="studio-page support-knowledge-page" data-knowledge-page="categories">
    <header class="knowledge-header"><div><p class="studio-eyebrow">MOVES STUDIO · SUPORTE</p><h1>Base de conhecimento</h1><p>Crie e gerencie conteúdos para ajudar seus usuários.</p></div><button class="studio-btn primary" type="button" data-knowledge-open="category"><?= studio_icon('archive') ?> Nova categoria</button></header>
    <nav class="support-knowledge-tabs" aria-label="Base de conhecimento"><a href="/support/articles"><?= studio_icon('newspaper') ?> Artigos</a><a class="active" href="/support/categories"><?= studio_icon('archive') ?> Categorias</a><a href="/support/products"><?= studio_icon('briefcase') ?> Produtos</a><a href="/support/tags"><?= studio_icon('tag') ?> Tags</a><span class="knowledge-tab-muted"><?= studio_icon('trash') ?> Lixeira</span></nav>
    <form class="studio-filter-bar" method="get"><label><span>Buscar</span><input type="search" name="q" value="<?= $this->e($search) ?>" placeholder="Nome ou descrição"></label><label><span>Produto</span><select name="product"><option value="0">Todos</option><?php foreach ($products as $product): ?><option value="<?= (int) $product->id ?>"<?= $productId === (int) $product->id ? ' selected' : '' ?>><?= $this->e((string) $product->name) ?></option><?php endforeach; ?></select></label><label><span>Status</span><select name="status"><option value="">Todos</option><option value="active"<?= $status === 'active' ? ' selected' : '' ?>>Ativas</option><option value="inactive"<?= $status === 'inactive' ? ' selected' : '' ?>>Inativas</option></select></label><button class="studio-btn" type="submit">Filtrar</button><a class="studio-btn" href="/support/categories">Limpar</a></form>
    <div class="studio-table-wrap"><table><thead><tr><th>Categoria</th><th>Produto</th><th>Categoria pai</th><th>Artigos</th><th>Posição</th><th>Status</th><th>Atualizado</th><th>Ações</th></tr></thead><tbody>
    <?php if ($categories === []): ?><tr><td colspan="8" class="studio-empty">Nenhuma categoria encontrada.</td></tr><?php endif; ?>
    <?php foreach ($categories as $category): ?><tr><td><strong><?= $this->e((string) $category->name) ?></strong><small>/<?= $this->e((string) $category->slug) ?></small></td><td><?= $this->e($productNames[(int) ($category->product_id ?? 0)] ?? 'Global') ?></td><td><?= $this->e($categoryNames[(int) ($category->parent_id ?? 0)] ?? '—') ?></td><td><?= (int) ($articleCounts[(int) $category->id] ?? 0) ?></td><td><?= (int) $category->position ?></td><td><span class="studio-status studio-status-<?= $category->status === 'active' ? 'success' : 'neutral' ?>"><?= $category->status === 'active' ? 'Ativa' : 'Inativa' ?></span></td><td><?= $this->e((string) ($category->updated_at ?? '—')) ?></td><td><button class="studio-icon-action" type="button" title="Editar" data-knowledge-edit="category" data-id="<?= (int) $category->id ?>" data-name="<?= $this->e((string) $category->name) ?>" data-description="<?= $this->e((string) ($category->description ?? '')) ?>" data-product-id="<?= (int) ($category->product_id ?? 0) ?>" data-parent-id="<?= (int) ($category->parent_id ?? 0) ?>" data-position="<?= (int) $category->position ?>" data-status="<?= $this->e((string) $category->status) ?>">✎</button><form class="support-inline-form" method="post" action="/support/categories/delete" data-confirm-submit="Excluir esta categoria?"><?= $this->csrf() ?><input type="hidden" name="id" value="<?= (int) $category->id ?>"><button class="studio-icon-action danger" type="submit" title="Excluir">×</button></form></td></tr><?php endforeach; ?></tbody></table></div>
    <dialog class="support-modal" data-knowledge-dialog="category" aria-labelledby="category-modal-title"><form method="post" action="/support/categories/save" data-knowledge-form data-reload-on-success><?= $this->csrf() ?><input type="hidden" name="id" value="0"><input type="hidden" name="response" value="json"><h2 id="category-modal-title">Nova categoria</h2><p class="support-modal-error" data-modal-error role="alert"></p><label class="studio-field"><span>Produto</span><select name="product_id" data-modal-product required><option value="">Selecione um produto</option><?php foreach ($products as $product): ?><option value="<?= (int) $product->id ?>"><?= $this->e((string) $product->name) ?></option><?php endforeach; ?></select></label><label class="studio-field"><span>Categoria pai</span><select name="parent_id" data-modal-parent><option value="">Sem categoria pai</option><?php foreach ($allCategories as $parent): ?><option value="<?= (int) $parent->id ?>" data-product-id="<?= (int) ($parent->product_id ?? 0) ?>"><?= $this->e((string) $parent->name) ?></option><?php endforeach; ?></select></label><label class="studio-field"><span>Nome</span><input name="name" maxlength="150" required></label><label class="studio-field"><span>Descrição</span><textarea name="description" rows="3"></textarea></label><div class="studio-fields-two"><label class="studio-field"><span>Posição</span><input type="number" name="position" min="0" value="0"></label><label class="studio-field"><span>Status</span><select name="status"><option value="active">Ativa</option><option value="inactive">Inativa</option></select></label></div><footer class="support-modal-actions"><button class="studio-btn" type="button" data-knowledge-close>Cancelar</button><button class="studio-btn primary" type="submit">Salvar categoria</button></footer></form></dialog>
</section>
