<?php
declare(strict_types=1);
$this->layout('layouts/default', ['title' => $title, 'productName' => 'Suporte', 'activeProduct' => 'support', 'currentPage' => 'trash']);
$pageUrl = static fn (int $page): string => '/support/trash?' . http_build_query(array_filter(['q' => $search, 'page' => $page], static fn ($value): bool => $value !== ''));
$pageNumbers = range(1, (int) $pagination['pages']);
?>
<link rel="stylesheet" href="/themes/admin/css/support.css?v=20260919c">
<script src="/themes/admin/js/support-knowledge.js?v=20260919" defer></script>
<section class="studio-page support-knowledge-page" data-knowledge-page="trash">
    <header class="knowledge-header"><div><p class="studio-eyebrow">MOVES STUDIO · SUPORTE</p><h1>Base de conhecimento</h1><p>Restaure artigos ou confirme a exclusão permanente.</p></div></header>
    <nav class="support-knowledge-tabs" aria-label="Base de conhecimento"><a href="/support/articles"><i class="icon-newspaper-outline" aria-hidden="true"></i> Artigos</a><a href="/support/categories"><i class="icon-archive-outline" aria-hidden="true"></i> Categorias</a><a href="/support/products"><i class="icon-briefcase-outline" aria-hidden="true"></i> Produtos</a><a href="/support/tags"><i class="icon-pricetag-outline" aria-hidden="true"></i> Tags</a><a class="active" href="/support/trash"><i class="icon-trash-outline" aria-hidden="true"></i> Lixeira</a></nav>
    <div class="knowledge-toolbar"><form class="knowledge-filters" method="get" action="/support/trash"><label class="knowledge-search"><span class="sr-only">Buscar na lixeira</span><i class="icon-search-outline" aria-hidden="true"></i><input type="search" name="q" value="<?= $this->e($search) ?>" placeholder="Buscar na lixeira..."></label><button class="studio-btn" type="submit">Buscar</button></form></div>
    <div class="studio-table-wrap knowledge-table-wrap"><table><thead><tr><th>Título</th><th>Status editorial</th><th>Autor</th><th>Excluído em</th><th>Excluído por</th><th>Ações</th></tr></thead><tbody>
    <?php if ($articles === []): ?><tr><td colspan="6"><div class="knowledge-empty"><i class="icon-trash-outline" aria-hidden="true"></i><strong>A lixeira está vazia.</strong><span>Os artigos movidos para a lixeira aparecerão aqui.</span></div></td></tr><?php endif; ?>
    <?php foreach ($articles as $article): ?><tr><td><strong><?= $this->e((string) $article->title) ?></strong><small>/<?= $this->e((string) $article->slug) ?></small></td><td><?= $this->e(['draft' => 'Rascunho', 'published' => 'Publicado', 'archived' => 'Arquivado'][(string) $article->status] ?? (string) $article->status) ?></td><td><?= $this->e($users[(int) ($article->author_id ?? 0)] ?? '—') ?></td><td><?= $this->e((string) ($article->deleted_at ?? '—')) ?></td><td><?= $this->e($users[(int) ($article->deleted_by ?? 0)] ?? '—') ?></td><td class="knowledge-row-actions"><form method="post" action="/support/articles/restore"><?= $this->csrf() ?><input type="hidden" name="id" value="<?= (int) $article->id ?>"><button class="studio-btn" type="submit"><i class="icon-refresh-outline" aria-hidden="true"></i> Restaurar</button></form><button class="studio-btn danger" type="button" data-knowledge-delete="<?= (int) $article->id ?>" data-article-title="<?= $this->e((string) $article->title) ?>"><i class="icon-trash-outline" aria-hidden="true"></i> Excluir permanentemente</button></td></tr><?php endforeach; ?></tbody></table></div>
    <footer class="knowledge-pagination"><span>Mostrando <?= (int) $pagination['from'] ?> a <?= (int) $pagination['to'] ?> de <?= (int) $pagination['total'] ?> artigos</span><span class="knowledge-page-numbers"><a class="<?= $pagination['page'] <= 1 ? 'is-disabled' : '' ?>" href="<?= $pagination['page'] > 1 ? $this->e($pageUrl($pagination['page'] - 1)) : '#' ?>" aria-label="Página anterior"><i class="icon-chevron-back-outline" aria-hidden="true"></i></a><?php foreach ($pageNumbers as $number): ?><a class="<?= $number === $pagination['page'] ? 'active' : '' ?>" href="<?= $this->e($pageUrl($number)) ?>"><?= $number ?></a><?php endforeach; ?><a class="<?= $pagination['page'] >= $pagination['pages'] ? 'is-disabled' : '' ?>" href="<?= $pagination['page'] < $pagination['pages'] ? $this->e($pageUrl($pagination['page'] + 1)) : '#' ?>" aria-label="Próxima página"><i class="icon-chevron-forward-outline" aria-hidden="true"></i></a></span></footer>
    <dialog class="support-modal knowledge-confirm-dialog" data-knowledge-delete-dialog aria-labelledby="delete-dialog-title"><form method="post" action="/support/articles/delete"><?= $this->csrf() ?><input type="hidden" name="id" value="0"><h2 id="delete-dialog-title">Excluir artigo permanentemente?</h2><p><strong data-delete-title></strong></p><p>Esta ação não pode ser desfeita. As tags vinculadas e os snapshots de conteúdo também serão removidos.</p><footer class="support-modal-actions"><button class="studio-btn" type="button" data-knowledge-cancel-delete>Cancelar</button><button class="studio-btn danger" type="submit"><i class="icon-trash-outline" aria-hidden="true"></i> Excluir permanentemente</button></footer></form></dialog>
</section>
