<?php
declare(strict_types=1);
$this->layout('layouts/default', ['title' => $title, 'productName' => 'Suporte', 'activeProduct' => 'support', 'currentPage' => 'revisions']);
$pageUrl = static fn (int $page): string => '/support/revisions?' . http_build_query(array_filter(['q' => $search, 'page' => $page], static fn ($value): bool => $value !== ''));
$pageNumbers = range(1, (int) $pagination['pages']);
?>
<link rel="stylesheet" href="/themes/admin/css/support.css?v=20260919c">
<script src="/themes/admin/js/support-knowledge.js?v=20260919" defer></script>
<section class="studio-page support-knowledge-page" data-knowledge-page="revisions">
    <header class="knowledge-header"><div><p class="studio-eyebrow">MOVES STUDIO · SUPORTE</p><h1>Revisões de conteúdo</h1><p>Consulte snapshots de conteúdo registrados antes de cada alteração.</p></div></header>
    <div class="knowledge-toolbar"><form class="knowledge-filters" method="get" action="/support/revisions"><label class="knowledge-search"><span class="sr-only">Buscar revisões</span><i class="icon-search-outline" aria-hidden="true"></i><input type="search" name="q" value="<?= $this->e($search) ?>" placeholder="Buscar por artigo ou título salvo..."></label><button class="studio-btn" type="submit">Buscar</button></form></div>
    <div class="studio-table-wrap knowledge-table-wrap"><table><thead><tr><th>Artigo</th><th>Título salvo</th><th>Autor da revisão</th><th>Data/hora</th><th>Ação</th></tr></thead><tbody>
    <?php if ($revisions === []): ?><tr><td colspan="5"><div class="knowledge-empty"><i class="icon-time-outline" aria-hidden="true"></i><strong>Nenhuma revisão encontrada.</strong><span>Uma revisão de conteúdo é criada quando título, resumo ou conteúdo são alterados.</span></div></td></tr><?php endif; ?>
    <?php foreach ($revisions as $revision): ?><tr><td><strong><?= $this->e((string) $revision->article_title) ?></strong></td><td><?= $this->e((string) $revision->title) ?></td><td><?= $this->e((string) ($revision->author_name ?? 'Sistema')) ?></td><td><?= $this->e((string) $revision->created_at) ?></td><td><button class="studio-btn" type="button" data-revision-preview data-title="<?= $this->e((string) $revision->title) ?>" data-article="<?= $this->e((string) $revision->article_title) ?>" data-author="<?= $this->e((string) ($revision->author_name ?? 'Sistema')) ?>" data-created="<?= $this->e((string) $revision->created_at) ?>" data-excerpt="<?= $this->e((string) ($revision->excerpt ?? '')) ?>" data-content="<?= $this->e(\Moves\Core\HtmlSanitizer::clean((string) ($revision->content ?? ''))) ?>"><i class="icon-eye-outline" aria-hidden="true"></i> Visualizar</button></td></tr><?php endforeach; ?></tbody></table></div>
    <footer class="knowledge-pagination"><span>Mostrando <?= (int) $pagination['from'] ?> a <?= (int) $pagination['to'] ?> de <?= (int) $pagination['total'] ?> revisões</span><span class="knowledge-page-numbers"><a class="<?= $pagination['page'] <= 1 ? 'is-disabled' : '' ?>" href="<?= $pagination['page'] > 1 ? $this->e($pageUrl($pagination['page'] - 1)) : '#' ?>" aria-label="Página anterior"><i class="icon-chevron-back-outline" aria-hidden="true"></i></a><?php for ($number = 1; $number <= $pagination['pages']; $number++): ?><a class="<?= $number === $pagination['page'] ? 'active' : '' ?>" href="<?= $this->e($pageUrl($number)) ?>"><?= $number ?></a><?php endfor; ?><a class="<?= $pagination['page'] >= $pagination['pages'] ? 'is-disabled' : '' ?>" href="<?= $pagination['page'] < $pagination['pages'] ? $this->e($pageUrl($pagination['page'] + 1)) : '#' ?>" aria-label="Próxima página"><i class="icon-chevron-forward-outline" aria-hidden="true"></i></a></span></footer>
    <dialog class="support-modal revision-preview-dialog" data-revision-dialog aria-labelledby="revision-dialog-title"><article><header><div><p class="studio-eyebrow">SNAPSHOT DE CONTEÚDO</p><h2 id="revision-dialog-title" data-revision-title></h2><p data-revision-meta></p></div><button class="studio-icon-action" type="button" data-revision-close aria-label="Fechar"><i class="icon-close-outline" aria-hidden="true"></i></button></header><p data-revision-excerpt></p><div class="moves-content" data-revision-content></div><footer class="support-modal-actions"><button class="studio-btn" type="button" data-revision-close>Fechar</button></footer></article></dialog>
</section>
