<?php $this->layout('layouts/default', compact('title', 'productName', 'activeProduct', 'currentPage')); ?>
<link rel="stylesheet" href="/themes/admin/css/support.css?v=20260919c">
<section class="support-workspace-page">
<?php $this->insert('components/support-page-header', ['heading' => 'Central de suporte', 'description' => 'Acompanhe a base de conhecimento e acesse as áreas de atendimento.', 'actionHref' => '/support/articles/create', 'actionLabel' => 'Novo artigo']); ?>
<div class="support-metric-grid">
<?php foreach ([['icon-newspaper-outline','Artigos',(int)$counts['articles']],['icon-checkmark-circle-outline','Publicados',(int)$counts['published']],['icon-document-text-outline','Rascunhos',(int)$counts['drafts']],['icon-cube-outline','Produtos',(int)$counts['products']]] as [$icon,$label,$value]): ?><article class="support-metric"><i class="<?= $icon ?>"></i><div><span><?= $this->e($label) ?></span><strong><?= $value ?></strong></div></article><?php endforeach; ?>
</div>
<div class="support-dashboard-grid"><section class="support-panel"><header><div><h2>Conteúdo atualizado recentemente</h2><p>Artigos ativos, sem itens da lixeira.</p></div><a href="/support/articles">Ver todos</a></header><?php if ($recent === []): ?><?php $this->insert('components/support-empty-state', ['icon'=>'icon-newspaper-outline','heading'=>'Nenhum artigo cadastrado','description'=>'Crie o primeiro conteúdo da base de conhecimento.']); ?><?php else: ?><div class="support-compact-list"><?php foreach ($recent as $article): ?><a href="/support/articles/<?= $this->e(rawurlencode($article['slug'])) ?>/edit"><span><strong><?= $this->e($article['title']) ?></strong><small><?= $this->e($article['product_name'] ?? 'Sem produto') ?> · <?= $this->e($article['category_name'] ?? 'Sem categoria') ?></small></span><em class="support-state <?= $article['status']==='published'?'success':'' ?>"><?= $this->e($article['status']) ?></em></a><?php endforeach; ?></div><?php endif; ?></section>
<aside class="support-panel"><header><div><h2>Acessos rápidos</h2><p>Atalhos do workspace.</p></div></header><nav class="support-shortcuts"><a href="/support/articles"><i class="icon-newspaper-outline"></i><span><strong>Base de conhecimento</strong><small>Gerenciar artigos</small></span></a><a href="/support/users"><i class="icon-people-outline"></i><span><strong>Usuários</strong><small>Consultar acessos</small></span></a><a href="/support/reports"><i class="icon-stats-chart-outline"></i><span><strong>Relatórios</strong><small>Métricas disponíveis</small></span></a><a href="/support/inbox"><i class="icon-mail-outline"></i><span><strong>Atendimento</strong><small>Estrutura preparada</small></span></a></nav></aside></div>
</section>
