<?php declare(strict_types=1);
$this->layout('layouts/default',['title'=>'Talk','productName'=>'Talk','activeProduct'=>'talk','currentPage'=>'dashboard']);
$talkView=$talkView??'inbox';$conversations=$conversations??[];$queue=$queue??[];$contacts=$contacts??[];$tickets=$tickets??[];$channels=$channels??[];$users=$users??[];$settings=$settings??[];$jack_interactions=$jack_interactions??[];
?>
<link rel="stylesheet" href="/themes/admin/css/support.css?v=20260919c"><link rel="stylesheet" href="<?= $this->e($this->asset('css/talk.css')) ?>">
<section class="support-workspace-page studio-page talk-page talk-inbox-page" data-talk-view="<?= $this->e($talkView) ?>">
<?php $this->insert('components/support-page-header',['heading'=>'Talk','description'=>'Central de atendimento WhatsApp da Moves.','actionHref'=>'/talk?view=connection','actionLabel'=>'Conexão WhatsApp']); ?>
<nav class="talk-workspace-nav" aria-label="Áreas do Talk">
<?php foreach(['inbox'=>'Conversas','queue'=>'Fila','contacts'=>'Contatos','history'=>'Histórico','connection'=>'Conexão','jack'=>'Jack','team'=>'Equipe','settings'=>'Configurações'] as $key=>$label): ?><a href="/talk?view=<?= $key ?>" data-talk-view-link="<?= $key ?>" class="<?= $talkView===$key?'active':'' ?>"><?= $this->e($label) ?></a><?php endforeach; ?>
</nav>
<?php if($talkView==='inbox'): ?>
<div class="talk-home-shell"><aside class="talk-inbox-list"><?php $scope=(string)($_GET['scope']??'all'); ?><div class="talk-inbox-tabs talk-inbox-tabs-three"><a class="<?= $scope==='all'?'active':'' ?>" href="/talk?view=inbox&scope=all">Todos</a><a class="<?= $scope==='attending'?'active':'' ?>" href="/talk?view=inbox&scope=attending">Atendendo</a><a class="<?= $scope==='unread'?'active':'' ?>" href="/talk?view=inbox&scope=unread">Não lidos</a></div><form class="talk-inbox-search" action="/talk" method="get"><input type="hidden" name="view" value="inbox"><i class="icon-search-outline"></i><input name="q" placeholder="Buscar conversas, nome, telefone..."></form><div class="talk-inbox-list-body"><?php if(!$conversations): ?><div class="talk-list-empty"><i class="icon-chatbubbles-outline"></i><strong>Nenhuma conversa</strong><span>As conversas recebidas pelo WhatsApp aparecerão aqui.</span></div><?php else: foreach($conversations as $row): $id=(int)($row['ticket_id']??0); ?><a class="talk-inbox-row" href="/talk/tickets/<?= $id ?>"><span class="talk-contact-avatar"><?= $this->e(strtoupper(substr((string)($row['contact_name']??$row['phone']??'?'),0,1))) ?></span><span class="talk-inbox-row-copy"><strong><?= $this->e((string)($row['contact_name']??$row['phone']??'Sem identificação')) ?></strong><small><?= $this->e((string)($row['last_message_preview']??'Conversa do WhatsApp')) ?></small><span class="talk-inbox-row-meta"><em><?= $this->e((string)($row['queue_name']??'WhatsApp')) ?></em><?php if((int)($row['unread_count']??0)>0): ?><b><?= (int)$row['unread_count'] ?></b><?php endif; ?></span></span></a><?php endforeach; endif; ?></div></aside><main class="talk-home-empty"><div><span class="talk-whatsapp-mark large"><i class="icon-logo-whatsapp"></i></span><h2>Selecione uma conversa</h2><p>Escolha uma conversa à esquerda para iniciar ou continuar o atendimento.</p></div></main><aside class="talk-home-context"><div class="talk-context-tabs"><button class="active">Contato</button><button>Chamados</button><button>Histórico</button><button>Notas</button></div><div class="talk-list-empty"><i class="icon-person-outline"></i><strong>Dados do contato</strong><span>Selecione uma conversa.</span></div></aside></div>
<?php elseif($talkView==='connection'): ?>
<div class="talk-module-grid"><section class="support-panel talk-connection-card"><header><div><h2>Conexão com WhatsApp</h2><p>Canal usado para receber e enviar mensagens.</p></div><span class="support-state <?= !empty($whatsappStatus['connected'])?'success':'' ?>"><?= !empty($whatsappStatus['connected'])?'Conectado':'Desconectado' ?></span></header><div class="talk-connection-hero"><span class="talk-whatsapp-mark large"><i class="icon-logo-whatsapp"></i></span><div><strong>WhatsApp</strong><p><?= $this->e((string)($whatsappStatus['detail']??'Configure o provedor para ativar o canal.')) ?></p></div></div></section><section class="support-panel"><header><div><h2>Configuração do canal</h2><p>Credenciais permanecem no ambiente do servidor e não são exibidas aqui.</p></div></header><div class="talk-connection-checks"><p><span>Driver</span><strong><?= !empty($whatsappStatus['connected'])?'Meta Cloud API':'Não configurado' ?></strong></p><p><span>Recebimento</span><strong><?= !empty($whatsappStatus['connected'])?'Disponível':'Aguardando conexão' ?></strong></p><p><span>Envio</span><strong><?= !empty($whatsappStatus['connected'])?'Disponível':'Aguardando conexão' ?></strong></p></div><div class="support-info"><i class="icon-information-circle-outline"></i> Configure TALK_WHATSAPP_DRIVER, TALK_WHATSAPP_PHONE_NUMBER_ID e TALK_WHATSAPP_ACCESS_TOKEN no ambiente do servidor. O token nunca deve ser salvo ou exibido nesta tela.</div></section></div>
<?php elseif($talkView==='queue'): ?><section class="support-panel"><header><div><h2>Fila de atendimento</h2><p>Conversas aguardando atendimento.</p></div></header><?php if(!$queue): ?><div class="support-empty-state"><h2>Fila vazia</h2><p>Nenhum atendimento aguardando.</p></div><?php else: ?><div class="support-table"><table><thead><tr><th>Protocolo</th><th>Contato</th><th>Fila</th><th>Prioridade</th></tr></thead><tbody><?php foreach($queue as $row): ?><tr><td><?= $this->e((string)$row['protocol']) ?></td><td><?= $this->e((string)($row['contact_name']??'—')) ?></td><td><?= $this->e((string)($row['queue_name']??'Geral')) ?></td><td><?= $this->e((string)$row['priority']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php elseif($talkView==='contacts'): ?><section class="support-panel"><header><div><h2>Contatos</h2><p>Contatos criados pelas conversas recebidas.</p></div></header><?php if(!$contacts): ?><div class="support-empty-state"><h2>Nenhum contato</h2></div><?php else: ?><div class="support-table"><table><thead><tr><th>Nome</th><th>Telefone</th><th>E-mail</th><th>Canal</th></tr></thead><tbody><?php foreach($contacts as $row): ?><tr><td><?= $this->e((string)($row['name']??'Sem nome')) ?></td><td><?= $this->e((string)($row['phone']??'—')) ?></td><td><?= $this->e((string)($row['email']??'—')) ?></td><td><?= $this->e((string)($row['channel']??'WhatsApp')) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php elseif($talkView==='history'): ?><section class="support-panel"><header><div><h2>Histórico</h2><p>Atendimentos finalizados.</p></div></header><?php if(!$tickets): ?><div class="support-empty-state"><h2>Nenhum atendimento finalizado</h2></div><?php else: ?><div class="support-table"><table><thead><tr><th>Protocolo</th><th>Contato</th><th>Status</th><th>Atualizado</th></tr></thead><tbody><?php foreach($tickets as $row): ?><tr><td><?= $this->e((string)$row['protocol']) ?></td><td><?= $this->e((string)($row['contact_name']??'—')) ?></td><td><?= $this->e((string)$row['status']) ?></td><td><?= $this->e((string)($row['closed_at']??$row['updated_at'])) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php elseif($talkView==='jack'): ?><section class="support-panel"><header><div><h2>Jack</h2><p>Interações do agente virtual no atendimento.</p></div></header><?php if(!$jack_interactions): ?><div class="support-empty-state"><h2>Sem interações</h2><p>As ações do Jack aparecerão aqui.</p></div><?php endif; ?></section>
<?php elseif($talkView==='team'): ?><section class="support-panel"><header><div><h2>Equipe</h2><p>Atendentes, presença e capacidade.</p></div></header><div class="support-table"><table><thead><tr><th>Usuário</th><th>Perfil</th><th>Presença</th><th>Ativos</th></tr></thead><tbody><?php foreach($users as $row): ?><tr><td><?= $this->e((string)$row['name']) ?></td><td><?= $this->e((string)$row['talk_role']) ?></td><td><?= $this->e((string)$row['presence']) ?></td><td><?= (int)$row['active_tickets'] ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php else: ?><section class="support-panel"><header><div><h2>Configurações</h2><p>Regras gerais do atendimento.</p></div></header><div class="talk-connection-checks"><p><span>Autoatribuição</span><strong><?= ($settings['auto_assign.enabled']??'1')==='1'?'Ativa':'Inativa' ?></strong></p><p><span>Tempo padrão</span><strong><?= (int)($settings['auto_assign.default_seconds']??30) ?> segundos</strong></p></div></section><?php endif; ?>
</section><script src="<?= $this->e($this->asset('js/talk.js')) ?>" defer></script>