<?php
declare(strict_types=1);
$this->layout('layouts/default',['title'=>$title,'productName'=>'Talk','activeProduct'=>'talk','currentPage'=>$currentPage]);
$closed=$ticket['status']==='closed';
$queuedAt=new DateTimeImmutable((string)($ticket['queued_at']??$ticket['created_at']));
$firstDue=!empty($ticket['sla_due_at'])?new DateTimeImmutable((string)$ticket['sla_due_at']):$queuedAt->modify('+15 minutes');
$resolveDue=$queuedAt->modify('+240 minutes');
$now=new DateTimeImmutable();
$firstResponseAt=!empty($ticket['first_response_at'])?new DateTimeImmutable((string)$ticket['first_response_at']):null;
$closedAt=!empty($ticket['closed_at'])?new DateTimeImmutable((string)$ticket['closed_at']):null;
$firstBreached=$firstResponseAt?$firstResponseAt>$firstDue:(!$closed&&$now>$firstDue);
$resolveBreached=$closedAt?$closedAt>$resolveDue:(!$closed&&$now>$resolveDue);
$firstLabel=$firstResponseAt?($firstBreached?'Respondido fora do SLA':'Primeira resposta no SLA'):($firstBreached?'Primeira resposta vencida':'Aguardando primeira resposta');
$resolveLabel=$closed?($resolveBreached?'Finalizado fora do SLA':'Finalizado no SLA'):($resolveBreached?'SLA de resolução vencido':'SLA de resolução em andamento');
$assetUrl=static fn(array $a):string=>'/talk/attachments/'.(int)$a['id'];
?>
<link rel="stylesheet" href="<?= $this->e($this->asset('css/talk.css')) ?>">
<script src="<?= $this->e($this->asset('js/talk.js')) ?>" defer></script>
<section class="studio-page talk-page talk-inbox-page">
<header class="knowledge-header talk-attendance-header talk-inbox-topbar"><div><p class="studio-eyebrow">MOVES TALK · ATENDIMENTO</p><div class="talk-contact-title"><span class="talk-contact-avatar" aria-hidden="true"><?= $this->e(strtoupper(substr((string)$ticket['contact_name'],0,1))) ?></span><div><h1><?= $this->e((string)$ticket['contact_name']) ?></h1><p><?= $this->e((string)$ticket['protocol']) ?> · <?= $this->e((string)($ticket['queue_name']??'Sem fila')) ?> · <?= $this->e((string)$ticket['status']) ?></p></div></div></div><div class="knowledge-header-actions"><a class="studio-btn" href="<?= $closed?'/talk/history':'/talk/my-tickets' ?>"><i class="icon-arrow-back-outline"></i> Voltar</a></div></header>
<div class="studio-dashboard-kpis talk-attendance-kpis talk-inbox-kpis"><article><span>Prioridade</span><strong><?= $this->e(ucfirst((string)$ticket['priority'])) ?></strong></article><article class="talk-sla-item<?= $firstBreached?' is-breached':'' ?>" data-sla-due="<?= $this->e($firstDue->format('Y-m-d H:i:s')) ?>"><span>Primeira resposta</span><strong><?= $this->e($firstLabel) ?></strong><small data-sla-relative><?= $firstResponseAt?$this->e($firstResponseAt->format('d/m H:i')):'Limite '.$this->e($firstDue->format('d/m H:i')) ?></small></article><article class="talk-sla-item<?= $resolveBreached?' is-breached':'' ?>" data-sla-due="<?= $this->e($resolveDue->format('Y-m-d H:i:s')) ?>"><span>Resolução</span><strong><?= $this->e($resolveLabel) ?></strong><small data-sla-relative><?= $closedAt?$this->e($closedAt->format('d/m H:i')):'Limite '.$this->e($resolveDue->format('d/m H:i')) ?></small></article><article><span>Última atividade</span><strong><?= $this->e((string)($ticket['last_activity_at']??$ticket['updated_at'])) ?></strong></article></div>
<div class="talk-inbox-shell"><aside class="talk-inbox-list"><div class="talk-inbox-tabs"><a href="/talk/conversations" class="active">Todas</a><a href="/talk/queue">Fila</a><a href="/talk/my-tickets">Minhas</a><a href="/talk/notifications">Não lidas</a></div><form class="talk-inbox-search" action="/talk/conversations" method="get"><i class="icon-search-outline"></i><input name="q" placeholder="Buscar conversas, nome, telefone..." aria-label="Buscar conversas"></form><div class="talk-inbox-list-body"><a class="talk-inbox-row active" href="/talk/tickets/<?= (int)$ticket['id'] ?>"><span class="talk-contact-avatar"><?= $this->e(strtoupper(substr((string)$ticket['contact_name'],0,1))) ?></span><span class="talk-inbox-row-copy"><strong><?= $this->e((string)$ticket['contact_name']) ?></strong><small><?= $this->e((string)($ticket['last_message_preview']??$ticket['protocol'])) ?></small><em><?= $this->e((string)($ticket['queue_name']??'Geral')) ?></em></span></a></div></aside><div class="support-editor-layout talk-attendance-layout"><main class="support-editor-main talk-conversation-column">
<section class="studio-panel talk-conversation-panel"><div class="studio-panel-body"><div class="talk-conversation-toolbar"><div><h2>Conversa</h2><small><?= $this->e((string)$ticket['channel']) ?> · <?= $this->e((string)($ticket['assigned_name']??'Não atribuído')) ?></small></div><span class="studio-status"><?= $closed?'Finalizado':'Em atendimento' ?></span></div><div class="talk-thread" aria-live="polite"><?php foreach(($ticket['messages']??[]) as $message): ?><article class="talk-message talk-message-<?= $this->e((string)$message['direction']) ?>"><small><?= $this->e((string)($message['sender_name']??($message['sender_type']==='contact'?$ticket['contact_name']:'Sistema'))) ?> · <?= $this->e((string)$message['sent_at']) ?></small><p><?= nl2br($this->e((string)$message['body'])) ?></p></article><?php endforeach; ?></div>
<?php if(!empty($ticket['attachments'])): ?><div class="talk-attachments"><h3>Anexos da conversa</h3><?php foreach($ticket['attachments'] as $attachment): ?><?php $mime=(string)$attachment['mime_type'];$url=$assetUrl($attachment); ?><article class="talk-attachment-card"><?php if(str_starts_with($mime,'image/')): ?><a class="talk-media-preview" href="<?= $url ?>" target="_blank" rel="noopener"><img src="<?= $url ?>" alt="<?= $this->e((string)$attachment['original_name']) ?>" loading="lazy"></a><?php elseif(str_starts_with($mime,'audio/')): ?><audio controls preload="metadata" src="<?= $url ?>"></audio><?php elseif(str_starts_with($mime,'video/')): ?><video controls preload="metadata" src="<?= $url ?>"></video><?php endif; ?><div class="talk-attachment-meta"><strong><?= $this->e((string)$attachment['original_name']) ?></strong><small><?= $this->e($mime) ?> · <?= number_format(((int)$attachment['size_bytes'])/1024,1,',','.') ?> KB<?= !empty($attachment['uploaded_by_name'])?' · '.$this->e((string)$attachment['uploaded_by_name']):'' ?></small><a class="studio-btn" href="<?= $url ?>" target="_blank" rel="noopener"><?= $mime==='application/pdf'?'Abrir':'Baixar / abrir' ?></a></div></article><?php endforeach; ?></div><?php endif; ?>
<?php if(!empty($ticket['attachment_error'])): ?><p class="studio-alert studio-alert-danger"><?= $this->e((string)$ticket['attachment_error']) ?></p><?php endif; ?>
<?php if(!$closed&&$ticket['status']==='assigned'): ?><form class="talk-upload" method="post" enctype="multipart/form-data" action="/talk/tickets/<?= (int)$ticket['id'] ?>"><?= $this->csrf() ?><input type="hidden" name="action" value="attachment"><div class="studio-field"><label for="talk-attachment">Anexar arquivo</label><input id="talk-attachment" data-talk-file type="file" name="attachment" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,audio/mpeg,audio/ogg,audio/mp4,video/mp4" required><small data-talk-file-name>Nenhum arquivo selecionado</small><small>Imagem, PDF, TXT, áudio ou vídeo MP4. Máximo de 10 MB.</small></div><button class="studio-btn" type="submit"><i class="icon-add-outline"></i> Anexar</button></form><?php endif; ?>
<?php if(!empty($ticket['outbound_error'])): ?><p class="studio-alert studio-alert-danger" role="alert"><i class="icon-alert-circle-outline"></i> <?= $this->e((string)$ticket['outbound_error']) ?></p><?php elseif(($ticket['outbound_status']??null)==='sent'): ?><p class="studio-alert studio-alert-success" role="status"><i class="icon-checkmark-circle-outline"></i> Mensagem enviada.</p><?php endif; ?>
<?php if(!$closed&&$ticket['status']==='assigned'): ?><form class="talk-composer" method="post" action="/talk/tickets/<?= (int)$ticket['id'] ?>"><?= $this->csrf() ?><input type="hidden" name="action" value="send"><div class="studio-field"><label for="talk-body">Mensagem</label><textarea id="talk-body" data-talk-composer name="body" rows="3" maxlength="4000" placeholder="Digite uma mensagem…" required></textarea></div><div class="talk-composer-actions"><small>Ctrl/⌘ + Enter para enviar</small><button class="studio-btn studio-btn-primary" type="submit"><i class="icon-send-outline"></i> Enviar</button></div></form><?php endif; ?></div></section>
<section class="studio-panel"><div class="studio-panel-body"><h2>Notas internas</h2><?php foreach(($ticket['notes']??[]) as $note): ?><p><small><?= $this->e((string)$note['user_name']) ?> · <?= $this->e((string)$note['created_at']) ?></small><br><?= nl2br($this->e((string)$note['body'])) ?></p><?php endforeach; ?><?php if(!$closed): ?><form method="post" action="/talk/tickets/<?= (int)$ticket['id'] ?>"><?= $this->csrf() ?><input type="hidden" name="action" value="note"><div class="studio-field"><label for="note-body">Adicionar nota</label><textarea id="note-body" name="body" rows="2" maxlength="4000" required></textarea></div><button class="studio-btn" type="submit">Adicionar nota</button></form><?php endif; ?></div></section>
</main><aside class="support-editor-sidebar talk-context-column"><div class="talk-context-tabs" role="tablist" aria-label="Contexto do atendimento"><button class="active" type="button">Dados</button><button type="button">Histórico</button><button type="button">Arquivos</button></div>
<section class="studio-panel"><div class="studio-panel-body"><h3>Atendimento</h3><p><strong>Contato</strong><br><?= $this->e((string)$ticket['contact_name']) ?></p><p><strong>Telefone</strong><br><?= $this->e((string)($ticket['contact_phone']??'—')) ?></p><p><strong>Canal</strong><br><?= $this->e((string)$ticket['channel']) ?></p><p><strong>Atendente</strong><br><?= $this->e((string)($ticket['assigned_name']??'Não atribuído')) ?></p></div></section>
<section class="studio-panel"><div class="studio-panel-body"><h3><i class="icon-pricetag-outline"></i> Classificação</h3><form method="post" action="/talk/tickets/<?= (int)$ticket['id'] ?>"><?= $this->csrf() ?><input type="hidden" name="action" value="priority"><div class="studio-field"><label>Prioridade</label><select name="priority"><option value="low" <?= $ticket['priority']==='low'?'selected':'' ?>>Baixa</option><option value="normal" <?= $ticket['priority']==='normal'?'selected':'' ?>>Normal</option><option value="high" <?= $ticket['priority']==='high'?'selected':'' ?>>Alta</option><option value="urgent" <?= $ticket['priority']==='urgent'?'selected':'' ?>>Urgente</option></select></div><button class="studio-btn" type="submit">Atualizar prioridade</button></form><p><strong>Tags</strong></p><div class="talk-tags"><?php if(empty($ticket['tags'])): ?><small>Nenhuma tag aplicada.</small><?php else: ?><?php foreach($ticket['tags'] as $tag): ?><form method="post" action="/talk/tickets/<?= (int)$ticket['id'] ?>"><?= $this->csrf() ?><input type="hidden" name="action" value="detach_tag"><input type="hidden" name="tag_id" value="<?= (int)$tag['id'] ?>"><button class="talk-tag" type="submit" title="Remover tag"><?= $this->e((string)$tag['name']) ?> ×</button></form><?php endforeach; ?><?php endif; ?></div><form method="post" action="/talk/tickets/<?= (int)$ticket['id'] ?>"><?= $this->csrf() ?><input type="hidden" name="action" value="attach_tag"><div class="studio-field"><select name="tag_id" required><option value="">Adicionar tag existente</option><?php foreach(($ticket['available_tags']??[]) as $tag): ?><option value="<?= (int)$tag['id'] ?>"><?= $this->e((string)$tag['name']) ?></option><?php endforeach; ?></select></div><button class="studio-btn" type="submit"><i class="icon-add-outline"></i> Adicionar</button></form><form method="post" action="/talk/tickets/<?= (int)$ticket['id'] ?>"><?= $this->csrf() ?><input type="hidden" name="action" value="create_tag"><div class="studio-field"><input name="tag_name" maxlength="80" placeholder="Nova tag" required></div><button class="studio-btn" type="submit">Criar e aplicar</button></form></div></section>
<section class="studio-panel"><div class="studio-panel-body"><h3><i class="icon-stats-chart-outline"></i> SLA</h3><div class="talk-sla"><div class="talk-sla-item<?= $firstBreached?' is-breached':'' ?>" data-sla-due="<?= $this->e($firstDue->format('Y-m-d H:i:s')) ?>"><strong>Primeira resposta</strong><span><?= $this->e($firstLabel) ?></span><small data-sla-relative><?= $firstResponseAt?$this->e($firstResponseAt->format('d/m/Y H:i')):'Limite '.$this->e($firstDue->format('d/m/Y H:i')) ?></small></div><div class="talk-sla-item<?= $resolveBreached?' is-breached':'' ?>" data-sla-due="<?= $this->e($resolveDue->format('Y-m-d H:i:s')) ?>"><strong>Resolução</strong><span><?= $this->e($resolveLabel) ?></span><small data-sla-relative><?= $closedAt?$this->e($closedAt->format('d/m/Y H:i')):'Limite '.$this->e($resolveDue->format('d/m/Y H:i')) ?></small></div></div></div></section>
<?php if(!$closed): ?><section class="studio-panel"><div class="studio-panel-body"><h3>Transferir</h3><form method="post" action="/talk/tickets/<?= (int)$ticket['id'] ?>"><?= $this->csrf() ?><input type="hidden" name="action" value="transfer"><div class="studio-field"><label>Fila</label><select name="to_queue_id"><option value="">Manter fila</option><?php foreach(($ticket['queues']??[]) as $q): ?><option value="<?= (int)$q['id'] ?>"><?= $this->e((string)$q['name']) ?></option><?php endforeach; ?></select></div><div class="studio-field"><label>Atendente</label><select name="to_user_id"><option value="">Somente fila</option><?php foreach(($ticket['eligible_users']??[]) as $u): ?><option value="<?= (int)$u['id'] ?>"><?= $this->e((string)$u['name']) ?></option><?php endforeach; ?></select></div><div class="studio-field"><label>Motivo</label><input name="reason" maxlength="500"></div><button class="studio-btn" data-confirm="Transferir este atendimento?" type="submit">Transferir</button></form></div></section><section class="studio-panel"><div class="studio-panel-body"><h3>Ações</h3><div class="talk-actions-stack"><form method="post" action="/talk/tickets/<?= (int)$ticket['id'] ?>"><?= $this->csrf() ?><input type="hidden" name="action" value="return_queue"><button class="studio-btn" data-confirm="Devolver este atendimento para a fila?" type="submit">Devolver para fila</button></form><form method="post" action="/talk/tickets/<?= (int)$ticket['id'] ?>"><?= $this->csrf() ?><input type="hidden" name="action" value="close"><button class="studio-btn studio-btn-primary" data-confirm="Finalizar este atendimento?" type="submit">Finalizar atendimento</button></form></div></div></section><?php else: ?><section class="studio-panel"><div class="studio-panel-body"><h3>Ações</h3><form method="post" action="/talk/tickets/<?= (int)$ticket['id'] ?>"><?= $this->csrf() ?><input type="hidden" name="action" value="reopen"><button class="studio-btn studio-btn-primary" type="submit">Reabrir atendimento</button></form></div></section><?php endif; ?>
<section class="studio-panel"><div class="studio-panel-body"><h3>Timeline</h3><?php foreach(($ticket['events']??[]) as $event): ?><p><small><?= $this->e((string)$event['created_at']) ?></small><br><?= $this->e((string)$event['event_type']) ?></p><?php endforeach; ?></div></section>
</aside></div></div></section>