import test from 'node:test';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs/promises';
import {EventEmitter} from 'node:events';
import {SessionManager,normalizeJid,normalizePhoneNumber,profileIdentity} from '../session-manager.js';

function harness(root,{reconnectDelay=5,postInbound=null,logger=null}={}){
  const sockets=[],inbound=[];
  const manager=new SessionManager({authRoot:root,reconnectDelay,loggedOutCode:401,logger:logger||{info(){},error(){},warn(){}},qrFactory:async(qr)=>`data:${qr}`,authFactory:async(directory)=>({state:{directory},saveCreds(){}}),versionFactory:async()=>({version:[1,0,0]}),postInbound:postInbound||(async(payload)=>{inbound.push(payload);}),socketFactory:({auth})=>{const ev=new EventEmitter();const socket={ev,user:{id:`${path.basename(auth.directory)}@s.whatsapp.net`,name:path.basename(auth.directory)},signalRepository:{lidMapping:{async getPNForLID(){return null;}}},sent:[],logoutCalls:0,endCalls:0,async sendMessage(to,payload){this.sent.push({to,payload});return{key:{id:`msg-${sockets.length}`}};},async logout(){this.logoutCalls+=1;},end(){this.endCalls+=1;}};sockets.push(socket);return socket;}});
  return{manager,sockets,inbound};
}

test('separa JID, LID, PN e normaliza telefone móvel brasileiro',()=>{
  assert.equal(normalizeJid('553196920154:3@s.whatsapp.net'),'553196920154@s.whatsapp.net');
  assert.equal(normalizePhoneNumber('+55 31 99692-0154'),'5531996920154');
  assert.equal(normalizePhoneNumber('553196920154'),'5531996920154');
  assert.deepEqual(profileIdentity({id:'553196920154:3@s.whatsapp.net',lid:'150350380150964:3@lid',name:'DM'}),{id:'553196920154:3@s.whatsapp.net',jid:'553196920154@s.whatsapp.net',lid:'150350380150964@lid',phone_jid:'553196920154@s.whatsapp.net',phone_number:'5531996920154',name:'DM'});
  assert.equal(normalizePhoneNumber('150350380150964@lid'),'');
});

test('messages.upsert aceita notify e append, resolve PN/LID e ignora fromMe',async(t)=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'moves-wa-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const{manager,sockets,inbound}=harness(root);await manager.connect('inbound','wa-inbound');const socket=sockets[0];socket.signalRepository.lidMapping.getPNForLID=async()=> '553196920154:7@s.whatsapp.net';socket.ev.emit('messages.upsert',{type:'notify',messages:[{key:{id:'msg-1',remoteJid:'150350380150964@lid'},pushName:'Contato',message:{conversation:'Teste'}}]});socket.ev.emit('messages.upsert',{type:'append',messages:[{key:{id:'msg-2',remoteJid:'553196920154@s.whatsapp.net'},message:{conversation:'Offline'}},{key:{id:'msg-3',remoteJid:'553196920154@s.whatsapp.net',fromMe:true},message:{conversation:'Minha'}}]});await new Promise((resolve)=>setImmediate(resolve));assert.equal(inbound.length,2);const lidMessage=inbound.find((item)=>item.external_id==='msg-1'),pnMessage=inbound.find((item)=>item.external_id==='msg-2');assert.equal(lidMessage.from_lid,'150350380150964@lid');assert.equal(lidMessage.phone_jid,'553196920154@s.whatsapp.net');assert.equal(lidMessage.phone_number,'5531996920154');assert.equal(lidMessage.session_key,'inbound');assert.ok(pnMessage);});

test('QR, cancelamento e reconexão preservam credenciais do canal',async(t)=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'moves-wa-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const{manager,sockets}=harness(root);await manager.connect('lifecycle','wa-lifecycle');const first=sockets[0];first.ev.emit('connection.update',{qr:'qr-value'});await new Promise((resolve)=>setImmediate(resolve));assert.equal(manager.state('lifecycle').status,'qr');assert.equal(manager.state('lifecycle').qr,'data:qr-value');await manager.disconnect('lifecycle');assert.equal(first.endCalls,1);assert.equal(first.logoutCalls,0);assert.equal(JSON.parse(await fs.readFile(path.join(root,'lifecycle','channel.json'),'utf8')).channel_external_id,'wa-lifecycle');await manager.connect('lifecycle','wa-lifecycle');assert.equal(sockets.length,2);sockets[1].ev.emit('connection.update',{connection:'open'});assert.equal(manager.state('lifecycle').status,'connected');});

test('erro da API inbound é registrado com etapa sem conteúdo privado',async(t)=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'moves-wa-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const errors=[];const{manager,sockets}=harness(root,{postInbound:async()=>{const error=new Error('HTTP 500');error.stage='moves_http_500';throw error;},logger:{info(){},warn(){},error(data,message){errors.push({data,message});}}});await manager.connect('api-error','wa-api-error');sockets[0].ev.emit('messages.upsert',{type:'notify',messages:[{key:{id:'msg-fail',remoteJid:'553196920154@s.whatsapp.net'},message:{conversation:'conteúdo privado'}}]});await new Promise((resolve)=>setImmediate(resolve));assert.equal(errors[0].data.stage,'moves_http_500');assert.equal(JSON.stringify(errors).includes('conteúdo privado'),false);});

test('duas sessões conectam, enviam e encerram isoladamente',async(t)=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'moves-wa-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const{manager,sockets}=harness(root);await Promise.all([manager.connect('channel-a','wa-a'),manager.connect('channel-b','wa-b')]);assert.equal(sockets.length,2);const socketA=sockets.find((socket)=>socket.user.id.startsWith('channel-a@')),socketB=sockets.find((socket)=>socket.user.id.startsWith('channel-b@'));socketA.ev.emit('connection.update',{connection:'open'});socketB.ev.emit('connection.update',{connection:'open'});assert.equal(manager.state('channel-a').connected,true);assert.equal(manager.state('channel-b').connected,true);await manager.sendText('channel-b','5511999999999','oi','intent-channel-b-0001');assert.equal(socketA.sent.length,0);assert.equal(socketB.sent.length,1);await manager.logout('channel-a');assert.equal(socketA.logoutCalls,1);assert.equal(manager.state('channel-a').connected,false);assert.equal(manager.state('channel-b').connected,true);});

test('auth path rejeita traversal e cada canal usa diretório próprio',async(t)=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'moves-wa-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const{manager,sockets}=harness(root);assert.throws(()=>manager.state('../escape'),/Canal inválido/);await Promise.all([manager.connect('safe-a','wa-a'),manager.connect('safe-b','wa-b')]);assert.notEqual(sockets[0].user.id,sockets[1].user.id);assert.equal((await fs.stat(path.join(root,'safe-a'))).isDirectory(),true);assert.equal((await fs.stat(path.join(root,'safe-b'))).isDirectory(),true);});

test('reconexão e falha de um canal não afetam o outro',async(t)=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'moves-wa-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const{manager,sockets}=harness(root);await Promise.all([manager.connect('channel-a','wa-a'),manager.connect('channel-b','wa-b')]);const socketA=sockets.find((socket)=>socket.user.id.startsWith('channel-a@')),socketB=sockets.find((socket)=>socket.user.id.startsWith('channel-b@'));socketA.ev.emit('connection.update',{connection:'open'});socketB.ev.emit('connection.update',{connection:'open'});socketA.ev.emit('connection.update',{connection:'close',lastDisconnect:{error:{output:{statusCode:500}}}});await new Promise((resolve)=>setImmediate(resolve));assert.equal(manager.state('channel-a').status,'reconnecting');assert.equal(manager.state('channel-b').status,'connected');await new Promise((resolve)=>setTimeout(resolve,20));assert.equal(sockets.length,3);});

test('reinício restaura sessões persistidas',async(t)=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'moves-wa-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const first=harness(root);await first.manager.connect('restored','wa-restored');await first.manager.shutdown();const second=harness(root);await second.manager.restore();assert.equal(second.sockets.length,1);assert.equal(second.manager.sessions.get('restored').externalId,'wa-restored');});

test('sessão histórica é migrada sem reutilizar auth nos demais canais',async(t)=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'moves-wa-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));await fs.writeFile(path.join(root,'creds.json'),'{}');const{manager}=harness(root);await manager.restore();assert.equal(manager.sessions.has('whatsapp-default'),true);assert.equal(await fs.readFile(path.join(root,'whatsapp-default','creds.json'),'utf8'),'{}');await manager.connect('outro-canal','outro-canal');await assert.rejects(fs.access(path.join(root,'outro-canal','creds.json')));});

test('idempotência evita envio duplicado concorrente e sobrevive ao restart',async(t)=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'moves-wa-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const first=harness(root);await first.manager.connect('idempotent','wa-idempotent');const socket=first.sockets[0];socket.ev.emit('connection.update',{connection:'open'});const key='intent-idempotent-0001';const [a,b]=await Promise.all([first.manager.sendText('idempotent','5511999999999','mensagem',key),first.manager.sendText('idempotent','5511999999999','mensagem',key)]);assert.equal(a.message_id,b.message_id);assert.equal(socket.sent.length,1);await first.manager.shutdown();const second=harness(root);await second.manager.restore();const restored=second.sockets[0];restored.ev.emit('connection.update',{connection:'open'});const replay=await second.manager.sendText('idempotent','5511999999999','mensagem',key);assert.equal(replay.message_id,a.message_id);assert.equal(restored.sent.length,0);});
